require('./register-tests.cjs');const test=require('node:test'),assert=require('node:assert/strict');
const E=require('./app/src/engine.ts'),A=require('./app/src/active-edit-v04.ts'),M=require('./app/src/multiplan-v04.ts'),P=require('./app/src/persistence-v04.ts'),{library}=require('./app/src/library-v04.ts');
function plan(){return E.activate({...E.newDraft(library[0]),stages:[{id:'stage-a',amountMg:'1',amountUnit:'mg',weeks:'2',override:null},{id:'stage-b',amountMg:'2',amountUnit:'mg',weeks:'2',override:null}],defaultSchedule:{kind:'daily',days:[],times:['00:00'],interval:null},startDate:E.addDays(E.localDate(),-3),breakWeeks:'0',vialMg:'10',waterMl:'2',initialVials:'5',reviewed:true});}
test('active edit updates pending events from today forward while retaining earlier and logged events byte-for-byte',()=>{let p=plan();p=E.logEvent(p,p.events[0].id,'completed');p=E.logEvent(p,p.events[1].id,'skipped');const today=E.localDate(),before=JSON.stringify(p.events.filter(e=>e.status!=='pending'||e.localDate<today));const edit=A.beginActiveEdit(p);edit.draft.stages[0].amountMg='3';edit.draft.waterMl='3';edit.draft.defaultSchedule.times=['12:00'];edit.draft.syringeCapacityUnits=100;const unrelated=plan(),draft=E.newDraft(library[1]);let s=M.withActivePlans({...E.blankStore(),draft},[p,unrelated]);s=A.applyActiveEdit(s,edit);assert.equal(s.activePlans.length,2);assert.deepEqual(s.activePlans[1],unrelated);assert.deepEqual(s.draft,draft);const revised=s.activePlans[0];assert.equal(JSON.stringify(revised.events.filter(e=>e.status!=='pending'||e.localDate<today)),before);assert.ok(revised.events.filter(e=>e.status==='pending'&&e.localDate>=today&&e.stageIndex===0).every(e=>e.amountMg===3&&e.calculation.concentration===10/3));assert.equal(revised.id,p.id);assert.equal(revised.inventoryTotalMg,p.inventoryTotalMg);assert.equal(revised.syringeCapacityUnits,100);assert.ok(revised.events.filter(e=>new Date(e.scheduledAt)>new Date()&&e.stageIndex===0).every(e=>e.amountMg===3&&e.calculation.concentration===10/3));assert.deepEqual(revised.revisions[0].previous,A.planDraft(p));assert.deepEqual(P.decodePlannerStore(P.encodePlannerStore(s)),JSON.parse(JSON.stringify(s)));});
test('saved edit survives restart without replacing an unfinished new plan draft',()=>{const p=plan(),edit=A.beginActiveEdit(p);edit.draft.waterMl='4';const s=M.addPlan({...E.blankStore(),draft:E.newDraft(library[2]),activeEdit:edit},p);assert.deepEqual(P.decodePlannerStore(P.encodePlannerStore(s)),s);});
test('editing uses latest event logs, corrects remaining inventory without altering consumed mass',()=>{const p=plan(),edit=A.beginActiveEdit(p);edit.supplyVials='2';edit.draft.vialMg='20';const logged=E.logEvent(p,p.events[0].id,'completed');const s=A.applyActiveEdit(M.addPlan(E.blankStore(),logged),edit);assert.equal(s.active.inventoryTotalMg,41);assert.equal(E.inventoryCoverage(s.active).supply,40);assert.deepEqual(s.active.events.find(e=>e.id===p.events[0].id),logged.events[0]);});
test('concurrent settings change or invalid edit fails without mutating original plan',()=>{const p=plan(),edit=A.beginActiveEdit(p),before=JSON.stringify(p);assert.throws(()=>A.applyActiveEdit(M.addPlan(E.blankStore(),{...p,waterMl:'4'}),edit),/changed while/);edit.draft.stages[0].amountMg='';assert.throws(()=>A.applyActiveEdit(M.addPlan(E.blankStore(),p),edit));assert.equal(JSON.stringify(p),before);});
test('logged future events and unchanged snooze are retained, duplicate timestamps are not regenerated',()=>{const p=plan(),future=p.events.find(e=>new Date(e.scheduledAt)>new Date());future.status='skipped';future.skippedAt=new Date().toISOString();const next=p.events.find(e=>e!==future&&new Date(e.scheduledAt)>new Date());next.snoozedUntil=next.scheduledAt;const edited=A.applyActiveEdit(M.addPlan(E.blankStore(),p),A.beginActiveEdit(p)).active;assert.deepEqual(edited.events.find(e=>e.id===future.id),future);assert.equal(edited.events.filter(e=>e.scheduledAt===future.scheduledAt).length,1);assert.equal(edited.events.find(e=>e.id===next.id).snoozedUntil,next.snoozedUntil);});

