require('./register-tests.cjs');
const test=require('node:test'),assert=require('node:assert/strict');
const E=require('./app/src/engine.ts'),D=require('./app/src/duration.ts'),P=require('./app/src/persistence-v04.ts'),M=require('./app/src/multiplan-v04.ts'),{library}=require('./app/src/library-v04.ts');
const stage=(value,unit='days',i=0)=>({id:'s'+i,amountMg:String(i+1),amountUnit:'mg',override:null,...D.durationPatch(String(value),unit)});
const draft=stages=>({...E.newDraft(library[0]),stages,startDate:'2026-09-06',defaultSchedule:{kind:'daily',days:[],times:['00:00'],interval:null},breakWeeks:'0',vialMg:'10',waterMl:'2',reviewed:true});
test('legacy weeks and durationWeeks default to Weeks without changing stored plans or logs',()=>{
 for(const s of [{...stage(2),duration:undefined,weeks:'2'},{...stage(2),duration:undefined,weeks:undefined,durationWeeks:2}]){
 assert.equal(D.stageDays(s),14);assert.equal(D.stageDuration(s).unit,'weeks');let p=E.activate(draft([s]));p=E.logEvent(p,p.events[0].id,'completed',new Date(2026,8,6,12));const raw=P.encodePlannerStore({...E.blankStore(),active:p,activePlans:[p]});const read=P.decodePlannerStore(raw);assert.deepEqual(JSON.parse(P.encodePlannerStore(read)),JSON.parse(raw));assert.equal(read.activePlans[0].events.length,14);
 }
});
for(const n of [3,5])test(n+' calendar-day stage has inclusive boundaries and no fractional weeks',()=>{const d=draft([stage(n)]),events=E.generateEvents(d);assert.equal(d.stages[0].weeks,'');assert.equal(events.length,n);assert.equal(events[0].localDate,d.startDate);assert.equal(events.at(-1).localDate,E.addDays(d.startDate,n-1));});
test('mixed days/weeks stages generate contiguous, non-overlapping dates and correct progress',()=>{const p=E.activate(draft([stage(3),stage(2,'weeks',1),stage(5,'days',2)]));assert.equal(p.events.length,22);assert.deepEqual([0,1,2].map(i=>{const rows=p.events.filter(e=>e.stageIndex===i);return [rows[0].localDate,rows.at(-1).localDate,rows.length]}),[['2026-09-06','2026-09-08',3],['2026-09-09','2026-09-22',14],['2026-09-23','2026-09-27',5]]);for(const [day,index]of [[8,0],[9,1],[22,1],[23,2]])assert.equal(E.actualProgress(p,new Date(2026,8,day,12)).stageIndex,index);assert.equal(E.actualProgress(p,new Date(2026,8,23,12)).totalDays,22);});
test('mixed duration Today, Tomorrow, calendar and history survive multi-plan reload',()=>{let p=E.activate(draft([stage(3),stage(2,'weeks',1)]));p=E.logEvent(p,p.events[0].id,'completed',new Date(2026,8,8,12));const q=E.activate({...draft([stage(5)]),id:'second',compoundId:library[1].id});const plans=P.decodePlannerStore(P.encodePlannerStore({...E.blankStore(),active:p,activePlans:[p,q]})).activePlans;assert.equal(plans.length,2);assert.equal(M.eventsForDay(plans,'2026-09-08').length,2);assert.equal(M.eventsForDay(plans,'2026-09-09')[0].event.stageIndex,1);assert.equal(M.aggregateEvents(plans).filter(x=>x.event.status==='completed').length,1);assert.equal(M.aggregateEvents(plans).length,22);});
test('day intervals continue across mixed stage boundaries and invalid durations fail',()=>{const d=draft([stage(3),stage(1,'weeks',1)]);d.defaultSchedule={kind:'intervalDays',days:[],times:['09:00'],interval:2};assert.deepEqual(E.generateEvents(d).map(e=>e.localDate),[6,8,10,12,14].map(n=>'2026-09-'+String(n).padStart(2,'0')));for(const value of ['0','1.5','729'])assert.throws(()=>E.generateEvents(draft([stage(value)])));});

test('editing legacy weeks to mixed durations preserves historical event records',()=>{const A=require('./app/src/active-edit-v04.ts');let p=E.activate({...draft([{...stage(2),duration:undefined,weeks:'2'},stage(2,'weeks',1)]),startDate:E.addDays(E.localDate(),-2)});p=E.logEvent(p,p.events[0].id,'completed');const edit=A.beginActiveEdit(p);Object.assign(edit.draft.stages[0],D.durationPatch('3','days'));const next=A.applyActiveEdit(M.addPlan(E.blankStore(),p),edit).active;assert.deepEqual(next.events.filter(e=>new Date(e.scheduledAt)<=new Date()),p.events.filter(e=>new Date(e.scheduledAt)<=new Date()));assert.equal(next.events.find(e=>e.localDate===E.addDays(E.localDate(),1)).stageIndex,1);assert.equal(next.stages[0].weeks,'');});

test('cycle schedule and taper builder generate explicit editable events',()=>{const d=draft([stage(14,'days')]);d.defaultSchedule={kind:'cycle',days:[],times:['09:00'],interval:null,cycleOn:5,cycleOff:2};assert.equal(E.generateEvents(d).length,10);const first=stage(1,'weeks');first.amountMg='1';assert.deepEqual(E.buildTaperStages(first,{type:'fixed',increment:'.5',period:'2',periodUnit:'weeks',steps:'3'}).map(s=>s.amountMg),['1','1.5','2']);});
test('repeating week cycle suppresses break events and reports automatic resume',()=>{const d={...draft([stage(20,'weeks')]),cycleOnWeeks:'12',cycleOffWeeks:'4'},events=E.generateEvents(d);assert.equal(events.some(e=>e.localDate===E.addDays(d.startDate,83)),true);assert.equal(events.some(e=>e.localDate===E.addDays(d.startDate,84)),false);assert.equal(events.some(e=>e.localDate===E.addDays(d.startDate,112)),true);const p=E.activate(d),progress=E.actualProgress(p,new Date(2026,11,1,12));assert.equal(progress.repeatingBreak,true);assert.equal(progress.repeatingBreakEnd,E.addDays(d.startDate,112));});
