import test from 'node:test';import assert from 'node:assert/strict';import fs from 'node:fs';
import {validateScreenshot,screenshotPath,uploadFeedback} from './app/src/cloud/feedback-attachments.ts';
import {createHandler} from './supabase/functions/beta-request-code/core.mjs';
const user='00000000-0000-4000-8000-000000000001',report='00000000-0000-4000-8000-000000000002',id='00000000-0000-4000-8000-000000000003';
test('screenshot limits and types',()=>{validateScreenshot({size:100,type:'image/png'},0);for(const [type,size,count]of [['image/svg+xml',100,0],['image/png',5242881,0],['image/jpeg',100,3]])assert.throws(()=>validateScreenshot({type,size},count));});
test('paths prevent traversal and omit filenames',()=>{assert.equal(screenshotPath(user,report,id,'image/png'),`${user}/${report}/${id}.png`);assert.throws(()=>screenshotPath('../x',report,id,'image/png'));});
test('retry preserves report ID and image bytes',async()=>{const file=new File(['synthetic'],'test.png',{type:'image/png'}),shots=[{id,file,preview:'blob:local'}],seen=[];let complete=0,fail=true;const port={upload:async(path,f)=>seen.push([path,await f.text()]),complete:async()=>{if(fail){fail=false;throw Error('temporary');}complete++;}};await assert.rejects(uploadFeedback(port,user,report,shots));await uploadFeedback(port,user,report,shots);assert.deepEqual(seen[0],seen[1]);assert.equal(complete,1);assert.equal(shots[0].file,file);});
const request=email=>new Request('https://example.invalid',{method:'POST',headers:{origin:'https://app.ezpepplanner.com','x-forwarded-for':'192.0.2.1','content-type':'application/json'},body:JSON.stringify({email})});
for(const route of ['invite','otp',null])test(`resend route ${route}`,async()=>{const calls=[];const handler=createHandler({hashIP:async()=> 'a'.repeat(64),gate:async(e)=>{assert.equal(e,'synthetic@example.invalid');return route?{route}:null;},invite:async e=>calls.push(['invite',e]),otp:async e=>calls.push(['otp',e])});const r=await handler(request(' Synthetic@Example.Invalid '));assert.equal(r.status,202);assert.deepEqual(calls,route?[[route,'synthetic@example.invalid']]:[]);assert.ok(!(await r.text()).includes('synthetic@'));});
test('malformed email never queries',async()=>{let calls=0;const handler=createHandler({hashIP:async()=>'',gate:async()=>{calls++;}});assert.equal((await handler(request('bad'))).status,202);assert.equal(calls,0);});
test('delivery errors sanitized',async()=>{const handler=createHandler({hashIP:async()=>'',gate:async()=>({route:'invite'}),invite:async()=>{throw Error('SECRET/PII');}});const r=await handler(request('synthetic@example.invalid'));assert.equal(r.status,503);assert.ok(!(await r.text()).includes('SECRET'));});
test('unapproved browser origin rejected',async()=>{assert.equal((await createHandler({})(new Request('https://example.invalid',{method:'POST',headers:{origin:'https://attacker.invalid'}}))).status,403);});
test('UI preview/removal/retry and authenticated image retrieval',()=>{const ui=fs.readFileSync('app/src/cloud/FeedbackAttachments.tsx','utf8'),app=fs.readFileSync('app/App.tsx','utf8'),client=fs.readFileSync('app/src/cloud/client.ts','utf8');assert.match(ui,/Remove screenshot/);assert.match(ui,/preview/);assert.match(app,/Retry feedback/);assert.match(app,/feedbackAttempt.current.id/);assert.match(client,/\.download\(path\)/);assert.doesNotMatch(client,/getPublicUrl|createSignedUrl/);});

test('invalid feedback stays editable before a retry snapshot is frozen',()=>{const app=fs.readFileSync('app/App.tsx','utf8');const start=app.indexOf('const sendCloudFeedback=async()=>');const body=app.slice(start,app.indexOf('const saveBetaConsent',start));assert.ok(body.indexOf('feedbackText.trim().length>4000')<body.indexOf('feedbackAttempt.current={'));assert.match(body,/feedbackAttempt.current.userId/);});

import {feedbackDeadline,submitRecoverableFeedback} from './app/src/cloud/feedback-attachments.ts';
test('recovery: stalled operation releases within a bounded deadline',async()=>{const t=Date.now();await assert.rejects(feedbackDeadline(new Promise(()=>{}),10),/timed out/);assert.ok(Date.now()-t<1000);});
test('recovery: text survives screenshot failure and repeated retries reuse one report',async()=>{const saved=new Set(),images=new Set(),calls=[];let fail=true;const shots=[{id,file:new File(['original'],'x.png',{type:'image/png'}),preview:'blob:fixture'}];const port={saveText:async()=>{saved.add(report);calls.push('text');},upload:async path=>{calls.push('image');if(fail)throw Error('offline');images.add(path);},complete:async()=>calls.push('complete')};await assert.rejects(submitRecoverableFeedback(port,user,report,shots),/written report was saved/);assert.equal(saved.size,1);assert.deepEqual(calls,['text','image']);fail=false;await submitRecoverableFeedback(port,user,report,shots);await submitRecoverableFeedback(port,user,report,shots);assert.equal(saved.size,1);assert.equal(images.size,1);assert.equal(await shots[0].file.text(),'original');});
test('recovery: ambiguous text-save response does not start image upload',async()=>{let uploaded=0,saved=0;const port={saveText:async()=>{saved++;throw Error('lost response');},upload:async()=>{uploaded++;},complete:async()=>{}};await assert.rejects(submitRecoverableFeedback(port,user,report,[]));assert.equal(saved,1);assert.equal(uploaded,0);});
test('recovery: UI preserves retry snapshots, permits reset, prevents same-tick double submit and cleans previews',()=>{const app=fs.readFileSync('app/App.tsx','utf8');assert.match(app,/feedbackBusy.current\|\|feedbackSent/);assert.match(app,/finally\{feedbackBusy.current=false;setFeedbackSubmitting\(false\)/);assert.match(app,/Start another report \(keeps saved retry\)/);assert.doesNotMatch(app,/disabled=\{feedbackSubmitting\|\|!!feedbackAttempt.current&&!feedbackSent\}/);assert.ok(app.indexOf('await saveFeedbackDraft(feedbackAttempt.current)')<app.indexOf('await submitBetaFeedback(feedbackAttempt.current.input'));assert.match(app,/pendingFeedbackDrafts/);assert.match(app,/feedbackUrls.current.forEach/);assert.match(app,/I agree to send this report/);});
