import test from 'node:test';import assert from 'node:assert/strict';import fs from 'node:fs';
import {validateScreenshot,screenshotPath,uploadFeedback} from './app/src/cloud/feedback-attachments.ts';
import {createHandler} from './supabase/functions/beta-request-code/core.mjs';
const user='00000000-0000-4000-8000-000000000001',report='00000000-0000-4000-8000-000000000002',id='00000000-0000-4000-8000-000000000003';
test('screenshot limits and types',()=>{validateScreenshot({size:100,type:'image/png'},0);for(const [type,size,count]of [['image/svg+xml',100,0],['image/png',5242881,0],['image/jpeg',100,3]])assert.throws(()=>validateScreenshot({type,size},count));});
test('paths prevent traversal and omit filenames',()=>{assert.equal(screenshotPath(user,report,id,'image/png'),`${user}/${report}/${id}.png`);assert.throws(()=>screenshotPath('../x',report,id,'image/png'));});
test('retry preserves report ID and image bytes',async()=>{const file=new File(['synthetic'],'test.png',{type:'image/png'}),shots=[{id,file,preview:'blob:local'}],seen=[];let complete=0,fail=true;const port={upload:async(path,f)=>seen.push([path,await f.text()]),complete:async()=>{if(fail){fail=false;throw Error('temporary');}complete++;}};await assert.rejects(uploadFeedback(port,user,report,shots));await uploadFeedback(port,user,report,shots);assert.deepEqual(seen[0],seen[1]);assert.equal(complete,1);assert.equal(shots[0].file,file);});
const request=email=>new Request('https://example.invalid',{method:'POST',headers:{origin:'https://app.ezpepplanner.com','x-forwarded-for':'192.0.2.1','content-type':'application/json'},body:JSON.stringify({email})});
for(const route of ['invite','otp',null])test(`resend route ${route}`,async()=>{const calls=[];const handler=createHandler({hashIP:async()=> 'a'.repeat(64),gate:async(e)=>{assert.equal(e,'synthetic@example.invalid');return route?{route}:null;},invite:async e=>calls.push(['invite',e]),otp:async e=>calls.push(['otp',e])});const r=await handler(request(' Synthetic@Example.Invalid '));assert.equal(r.status,202);assert.deepEqual(calls,route?[[route,'synthetic@example.invalid']]:[]);assert.ok(!(await r.text()).includes('synthetic@'));});
test('malformed email never queries',async()=>{let calls=0;const handler=createHandler({hashIP:async()=>'',gate:async()=>{calls++;}});assert.equal((await handler(request('bad'))).status,202);assert.equal(calls,0);});
test('delivery errors sanitized',async()=>{const handler=createHandler({hashIP:async()=>'',gate:async()=>({route:'invite'}),invite:async()=>{throw Error('SECRET/PII');}});const r=await handler(request('synthetic@example.invalid'));assert.equal(r.status,503);assert.ok(!(await r.text()).includes('SECRET'));});
test('unapproved browser origin rejected',async()=>{assert.equal((await createHandler({})(new Request('https://example.invalid',{method:'POST',headers:{origin:'https://attacker.invalid'}}))).status,403);});
test('UI preview/removal/retry and authenticated image retrieval',()=>{const ui=fs.readFileSync('app/src/cloud/FeedbackAttachments.tsx','utf8'),app=fs.readFileSync('app/App.tsx','utf8'),client=fs.readFileSync('app/src/cloud/client.ts','utf8');assert.match(ui,/Remove screenshot/);assert.match(ui,/preview/);assert.match(app,/Retry feedback/);assert.match(app,/feedbackAttempt.current.id/);assert.match(client,/\.download\(path\)/);assert.doesNotMatch(client,/getPublicUrl|createSignedUrl/);});

test('invalid feedback stays editable before a retry snapshot is frozen',()=>{const app=fs.readFileSync('app/App.tsx','utf8');const start=app.indexOf('const sendCloudFeedback=async()=>');const body=app.slice(start,app.indexOf('const saveBetaConsent',start));assert.ok(body.indexOf('feedbackText.trim().length>4000')<body.indexOf('feedbackAttempt.current={'));assert.match(body,/feedbackAttempt.current.userId/);});
