require('./register-tests.cjs');
const test=require('node:test'),assert=require('node:assert/strict');
const E=require('./app/src/engine.ts'),M=require('./app/src/multiplan-v04.ts'),P=require('./app/src/persistence-v04.ts'),A=require('./app/src/plan-actions-v04.ts'),{library}=require('./app/src/library-v04.ts');
function plan(id){let d=E.newDraft(library.find(c=>c.id===id)||library[0]);d={...d,stages:[{id:E.uid(),amountMg:'1',amountUnit:'mg',weeks:'2',override:null}],defaultSchedule:{kind:'daily',days:[],times:['00:00'],interval:null},breakWeeks:'0',startDate:E.addDays(E.localDate(),-1),vialMg:'10',waterMl:'2',initialVials:'2',reviewed:true};return E.activate(d);}
test('v3 migration retains draft, archive, events and exact original backup data',()=>{const legacy={...E.blankStore(),draft:E.newDraft(library[0]),active:plan('kpv'),archives:[plan('ghk-cu')]};const raw=JSON.stringify(legacy),loaded=P.decodePlannerStore(raw);assert.equal(JSON.stringify(legacy),raw);assert.deepEqual(loaded.activePlans,[legacy.active]);assert.deepEqual(loaded.draft,legacy.draft);assert.deepEqual(loaded.archives,legacy.archives);assert.deepEqual(P.decodePlannerStore(P.encodePlannerStore(loaded)),loaded);});
test('six simultaneous plans survive start, reload, scoped logging and inventory edits',()=>{let s={...E.blankStore(),activePlans:[]};for(const id of ['retatrutide','ghk-cu','5-amino-1mq','ss-31','nad-plus','mots-c'])s=M.addPlan(s,plan(id));assert.equal(s.archives.length,0);const original=JSON.parse(JSON.stringify(s));const target=s.activePlans[3];s=A.scopedPlanUpdate(s,target.id,x=>({...x,active:E.logEvent(x.active,target.events[0].id,'completed',new Date())}));assert.equal(s.activePlans[3].events[0].status,'completed');assert.deepEqual(s.activePlans.filter(p=>p.id!==target.id),original.activePlans.filter(p=>p.id!==target.id));s=A.scopedPlanUpdate(s,target.id,x=>({...x,active:{...x.active,inventoryTotalMg:50,syringeCapacityUnits:100}}));assert.equal(s.activePlans[3].inventoryTotalMg,50);assert.equal(s.activePlans[3].syringeCapacityUnits,100);assert.deepEqual(P.decodePlannerStore(P.encodePlannerStore(s)),JSON.parse(JSON.stringify(s)));});
test('archiving last plan leaves an empty collection and history survives reload',()=>{let s=M.addPlan(E.blankStore(),plan('kpv'));s=A.archivePlan(s,s.active.id);assert.equal(M.getActivePlans(s).length,0);assert.equal(s.active,null);assert.equal(s.archives.length,1);assert.equal(M.getActivePlans(P.decodePlannerStore(P.encodePlannerStore(s))).length,0);assert.deepEqual(M.getActivePlans({activePlans:[],active:plan('kpv')}),[]);});
test('malformed v4 collections fail closed instead of losing a plan',()=>{const p=plan('kpv');for(const activePlans of [[p,p],[null],[{id:'bad'}]])assert.throws(()=>P.decodePlannerStore(JSON.stringify({version:4,draft:null,active:null,archives:[],activePlans})));});
test('expanded library keeps custom-only compounds free of invented administration inputs',()=>{assert.equal(library.length,21);for(const id of ['5-amino-1mq','ss-31','nad-plus','mots-c','bpc-157','tb-500','ipamorelin','tesamorelin','cagrilintide','wolverine','klow','melanotan-i','melanotan-ii','kisspeptin','semax']){const c=library.find(c=>c.id===id),d=E.newDraft(c);assert.equal(c.school.referenceSchedules.length,0);assert.equal(d.defaultSchedule,null);assert.equal(d.vialMg,'');assert.equal(d.waterMl,'');assert.ok(d.stages.every(s=>s.amountMg===''&&s.weeks===''));}});
