require('./register-tests.cjs');
const {chromium}=require('playwright'),assert=require('node:assert/strict'),fs=require('fs');
const E=require('./app/src/engine.ts'),{library}=require('./app/src/library-v04.ts');
const KEY='peptide-planner:local:v04',LEGACY='peptide-planner:local:v03';
const six=['retatrutide','ghk-cu','5-amino-1mq','ss-31','nad-plus','mots-c'];
function fixture(n){const ids=[...six,'tirzepatide','semaglutide','glow-70','kpv'];const plans=ids.slice(0,n).map((id,i)=>{const c=library.find(c=>c.id===id);const d={...E.newDraft(c),stages:[{id:'stage-'+i,amountMg:'1',amountUnit:'mg',weeks:'2',override:null}],defaultSchedule:{kind:'daily',days:[],times:['00:'+String(i).padStart(2,'0')],interval:null},breakWeeks:'0',startDate:E.addDays(E.localDate(),-1),vialMg:id==='glow-70'?'70':'10',waterMl:'2',initialVials:'2',reviewed:true};return E.activate(d)});return{version:4,draft:null,active:plans[0],activePlans:plans,archives:[]};}
(async()=>{fs.mkdirSync('checks/integration04',{recursive:true});const browser=await chromium.launch({headless:true,channel:'msedge'});const errors=[];try{
 for(const width of [320,412,1366])for(const n of [1,3,6,10]){const context=await browser.newContext({viewport:{width,height:915}});const page=await context.newPage();page.on('pageerror',e=>errors.push(e.message));page.on('console',m=>{if(['error','warning'].includes(m.type()))errors.push(m.text());});const data=fixture(n);await page.addInitScript(({key,data})=>{if(!localStorage.getItem(key))localStorage.setItem(key,JSON.stringify(data));},{key:KEY,data});await page.goto('http://localhost:8081');await page.getByText('Saved on this device',{exact:true}).waitFor();assert.equal(await page.getByRole('button',{name:'Open 0.3.3 core'}).count(),0);assert.equal(await page.getByText('STRESS TEST',{exact:true}).count(),0);
 const tab=name=>page.getByRole('tab',{name,exact:true}),button=name=>page.getByRole('button',{name,exact:true});const fit=async()=>{assert.ok(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),'page overflow');for(const name of ['Pep School','Guide','My Peptides','TODAY','More']){const r=await tab(name).boundingBox();assert.ok(r&&r.x>=0&&r.x+r.width<=width+1,'nav '+name);}};
 await tab('My Peptides').click();assert.equal(await page.getByRole('button',{name:/^View .* plan$/}).count(),n);await fit();await page.screenshot({path:`checks/integration04/plans-${width}-${n}.png`});
 await tab('TODAY').click();await tab('Today').waitFor();for(const p of data.activePlans)await page.getByText(p.compoundName,{exact:true}).first().waitFor();await fit();await page.screenshot({path:`checks/integration04/today-${width}-${n}.png`});
 await tab('Calendar').click();const day=E.localDate();await button(`Calendar ${day}, ${n} events`).click();assert.equal(await page.getByRole('button',{name:/^Event details /}).count(),n);await fit();await page.screenshot({path:`checks/integration04/calendar-${width}-${n}.png`});
 if(n===6&&width===412){const p=data.activePlans[3],event=p.events.find(e=>e.localDate===day);await page.getByRole('button',{name:'Complete '+p.compoundName+' '+E.prettyTime(event.scheduledAt),exact:true}).click();await page.getByText('Event saved.',{exact:true}).waitFor();let saved=await page.evaluate(k=>JSON.parse(localStorage.getItem(k)),KEY);assert.equal(saved.activePlans[3].events.find(e=>e.id===event.id).status,'completed');assert.ok(saved.activePlans.filter(x=>x.id!==p.id).every(x=>x.events.every(e=>e.status==='pending')));await tab('History').click();await page.getByText(p.compoundName,{exact:true}).waitFor();await page.reload();await tab('My Peptides').click();await button('View '+p.compoundName+' plan').click();await button('Plan inventory').click();await button('Add vials').click();await page.getByLabel('Number of individual vials',{exact:true}).fill('3');await button('Save changes').click();await button('Plan inventory').waitFor();await page.getByText('Saved on this device',{exact:true}).waitFor();saved=await page.evaluate(k=>JSON.parse(localStorage.getItem(k)),KEY);assert.equal(saved.activePlans[3].inventoryTotalMg,50);assert.equal(saved.activePlans[0].inventoryTotalMg,20);
 await tab('My Peptides').click();await button('Archive '+p.compoundName).click();await button('Confirm archive '+p.compoundName).click();await page.getByText('5 active plans · each keeps its own stages, schedule, vial setup, supply and history.',{exact:true}).waitFor();await page.reload();await tab('TODAY').click();await tab('History').click();await page.getByText(p.compoundName,{exact:true}).waitFor();}
 await context.close();console.log(`PASS ${width}px / ${n} active plans`);}
 // Migrate an actual v3 payload in a separate profile; retain legacy bytes.
 const context=await browser.newContext({viewport:{width:412,height:915}}),page=await context.newPage(),f=fixture(1),legacy=JSON.stringify({version:3,active:f.active,draft:null,archives:[]});await page.addInitScript(({key,raw})=>{if(!localStorage.getItem(key))localStorage.setItem(key,raw);},{key:LEGACY,raw:legacy});await page.goto('http://localhost:8081');await page.getByText('Saved on this device',{exact:true}).waitFor();assert.equal(await page.evaluate(k=>localStorage.getItem(k),LEGACY),legacy);assert.equal((await page.evaluate(k=>JSON.parse(localStorage.getItem(k)),KEY)).activePlans.length,1);await page.getByRole('button',{name:'Quick Start — Learn More',exact:true}).click();await page.getByText('What is reconstitution?',{exact:true}).waitFor();await page.screenshot({path:'checks/integration04/quick-start.png'});for(const c of library.slice(6)){await page.getByRole('tab',{name:'Pep School',exact:true}).click();await page.getByLabel('Search Pep School',{exact:true}).fill(c.name);await page.getByRole('button',{name:c.name+' 101',exact:true}).click();await page.getByText(c.supplied.school101.whatIsIt,{exact:true}).waitFor();await page.getByRole('button',{name:'Open in Guide',exact:true}).click();await page.getByRole('button',{name:'Custom plan',exact:true}).click();const replace=page.getByRole('button',{name:'Confirm replace draft',exact:true});if(await replace.count())await replace.click();await page.getByRole('button',{name:'Edit stage 1',exact:true}).click();assert.equal(await page.getByLabel('Stage 1 amount',{exact:true}).inputValue(),'');}
 await context.close();assert.deepEqual(errors,[]);fs.writeFileSync('checks/integration04/results.json',JSON.stringify({passed:true,widths:[320,412,1366],counts:[1,3,6,10],errors},null,2));console.log('PASS migration, archive/reload history, isolated plan inventory, Quick Start and four custom-only library flows; zero console/runtime errors');
 }finally{await browser.close();}})().catch(e=>{console.error(e);process.exit(1)});
