require('./register-tests.cjs');const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs');const E=require('./app/src/engine.ts'),A=require('./app/src/active-edit-v04.ts'),M=require('./app/src/multiplan-v04.ts'),P=require('./app/src/persistence-v04.ts'),I=require('./app/src/inventory-maintenance.ts'),{library}=require('./app/src/library-v04.ts');
const now=new Date(2026,8,8,12);function plan(){return E.activate({...E.newDraft(library[0]),stages:[{id:'a',amountMg:'1',amountUnit:'mg',weeks:'1',override:null},{id:'b',amountMg:'2',amountUnit:'mg',weeks:'1',override:null}],startDate:'2026-09-06',breakWeeks:'0',vialMg:'10',waterMl:'2',initialVials:'5',defaultSchedule:{kind:'daily',days:[],times:['00:00'],interval:null},reviewed:true});}const store=p=>M.addPlan(E.blankStore(),p);
test('inventory consumption follows logged amounts only; skipped and overdue events cost nothing',()=>{let p=plan();assert.equal(I.inventoryProjection(p,now).supply,50);p=E.logEvent(p,p.events[0].id,'completed',now);assert.equal(I.inventoryProjection(p,now).supply,49);p=E.logEvent(p,p.events[1].id,'skipped',now);assert.equal(I.inventoryProjection(p,now).supply,49);assert.ok(Math.abs(I.inventoryProjection(p,now).currentMg-9)<1e-9);});
test('add ten vials, partial correction and current-vial adjustment preserve logs and reload',()=>{let p=plan();p=E.logEvent(p,p.events[0].id,'completed',now);const edit=A.beginActiveEdit(p);edit.returnTo='tracker';edit.inventoryChange={kind:'add',value:'10'};let s=A.applyActiveEdit(store(p),edit,now);assert.equal(I.inventoryProjection(s.active,now).supply,149);assert.deepEqual(s.active.events,p.events);assert.equal(s.active.inventoryLedger.length,1);assert.deepEqual(P.decodePlannerStore(P.encodePlannerStore(s)),JSON.parse(JSON.stringify(s)));let q=A.beginActiveEdit(s.active);q.inventoryChange={kind:'correct',value:'2.5'};s=A.applyActiveEdit(s,q,now);assert.equal(I.inventoryProjection(s.active,now).currentMg,5);q=A.beginActiveEdit(s.active);q.inventoryChange={kind:'current',value:'3'};s=A.applyActiveEdit(s,q,now);assert.equal(I.inventoryProjection(s.active,now).supply,23);assert.equal(s.active.events[0].status,'completed');});
test('future dose edits update actual-stage projections and retain completed/skipped records exactly',()=>{let p=plan();p=E.logEvent(p,p.events[0].id,'completed',now);p=E.logEvent(p,p.events[1].id,'skipped',now);p.inventoryTotalMg=7;const before=I.inventoryProjection(p,now),edit=A.beginActiveEdit(p);edit.draft.stages[0].amountMg='3';edit.draft.waterMl='3';edit.draft.syringeCapacityUnits=50;edit.draft.breakWeeks='2';const next=A.applyActiveEdit(store(p),edit,now).active;assert.ok(I.inventoryProjection(next,now).covered<before.covered);assert.deepEqual(next.events.filter(e=>e.status!=='pending'),p.events.filter(e=>e.status!=='pending'));assert.equal(I.inventoryProjection(next,now).supply,6);assert.equal(next.events.find(e=>new Date(e.scheduledAt)>now).amountMg,3);});
test('projections stop at actual future horizon and follow changing amounts',()=>{const p=plan();p.inventoryTotalMg=6;const r=I.inventoryProjection(p,now);assert.equal(r.covered,5);assert.equal(r.uncovered.localDate,'2026-09-14');p.inventoryTotalMg=500;const all=I.inventoryProjection(p,now);assert.equal(all.covered,11);assert.equal(all.uncovered,undefined);assert.equal(all.days,11);});
test('inventory corrections validate data and use latest completion while edit is open',()=>{const p=plan(),edit=A.beginActiveEdit(p);edit.inventoryChange={kind:'correct',value:'2.5'};const logged=E.logEvent(p,p.events[0].id,'completed',now);const s=A.applyActiveEdit(store(logged),edit,now);assert.equal(s.active.inventoryTotalMg,26);for(const value of ['', '-1','Infinity','oops'])assert.throws(()=>I.adjustedInventory(p,{kind:'correct',value},10,now));assert.throws(()=>I.adjustedInventory(p,{kind:'add',value:'1.5'},10,now));assert.throws(()=>I.adjustedInventory(p,{kind:'current',value:'11'},10,now));});
test('pause hides pending aggregate events, preserves history and resume restores them',()=>{let p=plan();p=E.logEvent(p,p.events[0].id,'completed',now);const edit=A.beginActiveEdit(p);edit.draft.pausedAt=now.toISOString();const s=A.applyActiveEdit(store(p),edit,now);assert.equal(M.aggregateEvents(s.activePlans).length,1);assert.deepEqual(s.active.events,p.events);assert.equal(I.inventoryProjection(s.active,now).future.length,0);const resume=A.beginActiveEdit(s.active);resume.draft.pausedAt=null;const restored=A.applyActiveEdit(s,resume,now);assert.equal(M.aggregateEvents(restored.activePlans).length,14);assert.deepEqual(restored.active.events,p.events);});


test('inventory and syringe maintenance preserve event arrays across time zones',()=>{const p={...plan(),timezone:'Pacific/Auckland'},edit=A.beginActiveEdit(p);edit.inventoryChange={kind:'add',value:'10'};edit.draft.syringeCapacityUnits=30;const next=A.applyActiveEdit(store(p),edit,now).active;assert.deepEqual(next.events,p.events);assert.equal(next.inventoryTotalMg,150);edit.draft.stages[0].amountMg='3';assert.throws(()=>A.applyActiveEdit(store(p),edit,now),/time zone/);});
test('completed logging can pass zero inventory without blocking and reports the deficit',()=>{let p=plan();p.inventoryTotalMg=.5;p=E.logEvent(p,p.events[0].id,'completed',now);const coverage=E.inventoryCoverage(p,now),projection=I.inventoryProjection(p,now);assert.equal(coverage.supply,-.5);assert.equal(coverage.enough,false);assert.equal(projection.vials,-.05);assert.equal(p.events[0].status,'completed');});

test('turning inventory tracking off preserves its balance for later re-enable',()=>{const p=plan(),before=I.inventoryProjection(p,now);const disable=A.beginActiveEdit(p);disable.draft.inventoryTracking=false;const off=A.applyActiveEdit(store(p),disable,now).active;assert.equal(off.inventoryTracking,false);assert.equal(off.inventoryTotalMg,p.inventoryTotalMg);const enable=A.beginActiveEdit(off);enable.draft.inventoryTracking=true;const restored=A.applyActiveEdit(store(off),enable,now).active;assert.equal(restored.inventoryTracking,true);assert.equal(restored.inventoryTotalMg,p.inventoryTotalMg);assert.equal(I.inventoryProjection(restored,now).supply,before.supply);});

test('private beta feedback is reachable from More and Community without automatic plan disclosure',()=>{const source=fs.readFileSync('./app/App.tsx','utf8');assert.match(source,/Give private beta feedback/);assert.match(source,/Beta Feedback/);assert.match(source,/Your plans and history are not included automatically/);assert.match(source,/Include active peptide names in this report/);assert.match(source,/Active peptide names: Not included by tester/);assert.match(source,/Submit private beta feedback/);});

test('beta privacy acknowledgement is local and repeats for account-linked consent',()=>{const source=fs.readFileSync('./app/App.tsx','utf8');assert.match(source,/pepplan\.beta-consent\.v1/);assert.match(source,/educational research, planning and tracking tool/);assert.match(source,/Routine authentication and reminder emails will not include peptide names/);assert.match(source,/transfer will require a preview and explicit confirmation/);assert.match(source,/Account-linked consent will be requested again/);});
test('consent-gated beta analytics stays bounded to non-sensitive event names',()=>{
 const app=fs.readFileSync('app/App.tsx','utf8'),client=fs.readFileSync('app/src/cloud/client.ts','utf8'),sql=fs.readFileSync('supabase/migrations/202609110001_beta_analytics.sql','utf8');
 assert.match(app,/By continuing, you accept the private beta terms and limited product analytics/);
 assert.match(client,/insert\(\{user_id:userId,event_name:eventName,screen:screen\?\?null,duration_seconds:duration\}\)/);
 assert.match(sql,/exists \(\s*select 1 from public\.beta_analytics_consents/s);
 assert.match(sql,/grant insert on public\.beta_analytics_events to authenticated/);
 assert.doesNotMatch(sql,/grant select.*beta_analytics_events.*authenticated/i);
});

