import test from 'node:test';import assert from 'node:assert/strict';import {handler} from './membership-foundation/backend/http.mjs';
const owner='11111111-1111-4111-8111-111111111111',other='22222222-2222-4222-8222-222222222222';
function setup(who=owner,enabled=false){let stripeCalls=0;const config={testUsers:[owner],testCheckoutEnabled:enabled,publishable:'public',secret:'rk_test_mock'};const store={membership:()=>({pro:false,beta_access:'unchanged',planner_data:'unchanged'})};const f=async(url)=>{if(url.endsWith('/auth/v1/user'))return Response.json({id:who});if(url.endsWith('/rpc/beta_access'))return Response.json(true);stripeCalls++;throw Error('UNEXPECTED_STRIPE_CALL');};return {h:handler(store,config,f),calls:()=>stripeCalls};}
const req=(op,token='Bearer mock',origin='https://app.ezpepplanner.com')=>new Request('https://builder-pepplan.aurapep.ca/membership/'+op,{method:'POST',headers:{authorization:token,origin,'content-type':'application/json'},body:'{}'});
test('owner browser status identifies server allowlist while disabled checkout creates nothing',async()=>{const {h,calls}=setup();let r=await h(req('status'));assert.equal(r.status,200);assert.deepEqual(await r.json(),{pro:false,beta_access:'unchanged',planner_data:'unchanged',test_account:true,test_checkout_enabled:false,mode:'test'});r=await h(req('checkout'));assert.equal((await r.json()).error,'BILLING_DISABLED');assert.equal(calls(),0);});
test('other beta user cannot enter checkout; unauthorized and other origin rejected',async()=>{let {h,calls}=setup(other,true);assert.equal((await h(req('checkout'))).status,403);assert.equal((await h(req('status',''))).status,401);assert.equal((await h(req('status','Bearer mock','https://other.invalid'))).status,403);assert.equal(calls(),0);});
test('CORS accepts actual browser headers; checkout return does not grant Pro',async()=>{const {h}=setup();const r=await h(new Request('https://builder-pepplan.aurapep.ca/membership/status',{method:'OPTIONS',headers:{origin:'https://app.ezpepplanner.com','access-control-request-headers':'authorization,content-type'}}));assert.equal(r.status,204);assert.equal(r.headers.get('access-control-allow-headers'),'authorization, content-type');assert.equal((await (await h(req('status'))).json()).pro,false);});

import {readFileSync} from 'node:fs';
import {stripTypeScriptTypes} from 'node:module';
const authSource=readFileSync(new URL('./app/src/cloud/auth-controller.ts',import.meta.url),'utf8');
const {AuthController}=await import('data:text/javascript;base64,'+Buffer.from(stripTypeScriptTypes(authSource,{mode:'transform'})).toString('base64'));
function authHarness(allowed=true){let state,changed=0,identity={userId:owner,email:'owner@example.test'};const port={restore:async()=>null,subscribe:()=>()=>{},eligible:async()=>allowed,requestCode:async()=>{},verifyCode:async()=>identity,passwordSignIn:async()=>identity,requestRecovery:async()=>{},updatePassword:async()=>{changed++},updateDisplayName:async()=>{},signOut:async()=>{}};const controller=new AuthController(port,s=>state=s);return {port,controller,state:()=>state,changes:()=>changed};}
test('password: existing identity and eligibility are preserved',async()=>{const h=authHarness();await h.controller.start();await h.controller.passwordSignIn('OWNER@example.test','synthetic-only-password');assert.equal(h.state().userId,owner);assert.equal(h.state().status,'eligible');});
test('password: unauthorized account remains denied',async()=>{const h=authHarness(false);await h.controller.start();await h.controller.passwordSignIn('other@example.test','synthetic-only-password');assert.equal(h.state().status,'denied');});
test('password: invalid credentials and recovery failures reveal no account existence',async()=>{const h=authHarness();h.port.passwordSignIn=async()=>{throw Error('private server details')};assert.match(await h.controller.passwordSignIn('owner@example.test','wrong'),/Sign-in could not/);const first=await h.controller.recover('absent@example.test');h.port.requestRecovery=async()=>{throw Error('rate limited')};assert.equal(await h.controller.recover('owner@example.test'),first);});
test('password: invalid and expired email codes remain rejected',async()=>{const h=authHarness();h.port.verifyCode=async()=>{throw Error('expired')};assert.match(await h.controller.verify('owner@example.test','123456'),/incorrect or expired/);});
test('password: length and confirmation enforced before update',async()=>{const h=authHarness();await h.controller.savePassword('abc12','abc12');await h.controller.savePassword('abcdef','abcdef');await h.controller.savePassword('123456','123456');await h.controller.savePassword('synthetic-strong-password1','different');assert.equal(h.changes(),0);assert.match(await h.controller.savePassword('synthetic-strong-password1','synthetic-strong-password1'),/Password saved/);assert.equal(h.changes(),1);assert.match(await h.controller.savePassword('abc123','abc123'),/Password saved/);assert.equal(h.changes(),2);});
test('password: recovery uses PKCE exchange, server identity and beta gate, never URL session injection',()=>{const s=readFileSync(new URL('./app/src/cloud/client.ts',import.meta.url),'utf8');assert.match(s,/flowType:'pkce'/);assert.match(s,/exchangeCodeForSession\(code\)/);assert.match(s,/checked\.data\.user\?\.id!==data\.session\.user\.id/);assert.match(s,/verifiedUser!==user\.id\|\|Date\.now\(\)-verifiedAt>600000/);assert.match(s,/rpc\('beta_access'\)/);assert.doesNotMatch(s,/setSession\(/);assert.match(s,/redirectTo:'https:\/\/app\.ezpepplanner\.com\/'/);});
test('password: migration code path, autofill and no signup retained',()=>{const s=readFileSync(new URL('./app/src/cloud/BetaAccount.tsx',import.meta.url),'utf8');assert.match(s,/autoComplete="current-password"/);assert.match(s,/autoComplete="new-password"/);assert.match(s,/Use an email code/);assert.match(s,/accessibilityRole="alert"/);const c=readFileSync(new URL('./app/src/cloud/client.ts',import.meta.url),'utf8');assert.doesNotMatch(c,/\.signUp\(/);assert.match(c,/storageKey:AUTH_STORAGE_KEY/);});

import vm from 'node:vm';
function adapterHarness({url='https://app.ezpepplanner.com/',valid=true,eligible=true}={}){
 const source=readFileSync(new URL('./app/src/cloud/client.ts',import.meta.url),'utf8');
 const block=source.slice(source.indexOf('let recoveryUser'),source.indexOf('export async function eligibleUser')).replace('export const authPort','const authPort');
 let callback=()=>{},updates=0,exchanges=0,session={user:{id:owner,email:'owner@example.test',user_metadata:{}}};
 const api={rpc:async()=>({data:eligible}),auth:{
 getSession:async()=>({data:{session}}),getUser:async()=>({data:{user:session?.user}}),
 exchangeCodeForSession:async()=>{exchanges++;if(!valid)return {error:Error('expired'),data:{session:null}};callback('PASSWORD_RECOVERY',session);return {data:{session}}},
 onAuthStateChange:cb=>{callback=cb;return {data:{subscription:{unsubscribe(){}}}}},
 updateUser:async()=>{updates++;return {}},signOut:async()=>{session=null;return {}}
 }};
 const context=vm.createContext({configured:()=>api,URL,URLSearchParams,Date,setTimeout,window:{location:{href:url},history:{replaceState(){}}}});
 vm.runInContext(stripTypeScriptTypes(block,{mode:'transform'})+';globalThis.port=authPort;',context);
 context.port.subscribe(()=>{});
 return {port:context.port,updates:()=>updates,exchanges:()=>exchanges};
}
test('password: expired recovery is rejected and cannot update a password',async()=>{const h=adapterHarness({url:'https://app.ezpepplanner.com/?code=synthetic',valid:false});await assert.rejects(h.port.restore(),/invalid or expired/);await assert.rejects(h.port.updatePassword('abc123'),/Fresh verification/);assert.equal(h.updates(),0);});
test('password: URL recovery flag alone never grants password-change authority',async()=>{const h=adapterHarness({url:'https://app.ezpepplanner.com/?type=recovery'});await h.port.restore();await assert.rejects(h.port.updatePassword('abc123'),/Fresh verification/);assert.equal(h.exchanges(),0);});
test('password: verified recovery retains UUID and requires eligible beta access',async()=>{const h=adapterHarness({url:'https://app.ezpepplanner.com/?code=synthetic'});assert.equal((await h.port.restore()).userId,owner);await h.port.updatePassword('abc123');assert.equal(h.updates(),1);const denied=adapterHarness({url:'https://app.ezpepplanner.com/?code=synthetic',eligible:false});await denied.port.restore();await assert.rejects(denied.port.updatePassword('abc123'),/Account unavailable/);assert.equal(denied.updates(),0);});
test('password: rejected recovery response is cleared without a code exchange',async()=>{const h=adapterHarness({url:'https://app.ezpepplanner.com/#error=access_denied'});await assert.rejects(h.port.restore(),/invalid or expired/);assert.equal(h.exchanges(),0);});

test('password: same-account verification and save retain the mounted screen',async()=>{const states=[],h=authHarness();const c=new AuthController(h.port,s=>states.push(s));await c.start();await c.passwordSignIn('owner@example.test','abc123');h.port.restore=async()=>({userId:owner,email:'owner@example.test'});states.length=0;assert.equal(await c.verify('owner@example.test','123456'),'');assert(!states.some(s=>s.status==='loading'));assert.match(await c.savePassword('abc123','abc123'),/Password saved/);assert(!states.some(s=>s.status==='loading'));assert.equal(states.at(-1).userId,owner);});
test('password: failed verification does not report successful setup',async()=>{const h=authHarness();h.port.verifyCode=async()=>{throw Error('invalid')};assert.notEqual(await h.controller.verify('owner@example.test','123456'),'');assert.equal(h.changes(),0);});
