require('./register-tests.cjs');const test=require('node:test'),assert=require('node:assert/strict');const E=require('./app/src/engine.ts'),{library}=require('./app/src/library-v04.ts'),P=require('./app/src/persistence-v04.ts');
function fixture(){return library.slice(0,2).map(c=>E.activate({...E.newDraft(c),stages:[{id:'fixture-'+c.id,amountMg:'1',amountUnit:'mg',weeks:'2',override:null}],defaultSchedule:{kind:'daily',days:[],times:['00:00'],interval:null},startDate:E.addDays(E.localDate(),-1),breakWeeks:'0',vialMg:'10',waterMl:'2',reviewed:true}));}
test('upgrade preserves every existing plan, event, log, draft and edit in v4',()=>{const plans=fixture();plans[0]=E.logEvent(plans[0],plans[0].events[0].id,'completed');const store={...E.blankStore(),draft:E.newDraft(library[3]),activePlans:plans,active:plans[0],activeEdit:require('./app/src/active-edit-v04.ts').beginActiveEdit(plans[1])};const raw=P.encodePlannerStore(store),read=P.decodePlannerStore(raw);assert.deepEqual(JSON.parse(P.encodePlannerStore(read)),JSON.parse(raw));assert.equal(read.activePlans.length,2);assert.equal(read.activePlans[0].events[0].status,'completed');});
test('transitional v3 explicit activePlans survives upgrade instead of falling back to only active',()=>{const plans=fixture(),raw=JSON.stringify({...E.blankStore(),active:plans[0],activePlans:plans});const read=P.decodePlannerStore(raw);assert.deepEqual(JSON.parse(JSON.stringify(read.activePlans)),JSON.parse(JSON.stringify(plans)));assert.equal(P.decodePlannerStore(P.encodePlannerStore(read)).activePlans.length,2);});
test('legacy single-plan migration preserves original payload; malformed collections fail closed',()=>{const plans=fixture(),legacy=JSON.stringify({...E.blankStore(),active:plans[0]});assert.equal(P.decodePlannerStore(legacy).activePlans.length,1);assert.equal(JSON.parse(legacy).version,3);assert.throws(()=>P.decodePlannerStore(JSON.stringify({...E.blankStore(),active:plans[0],activePlans:'invalid'})));assert.deepEqual(P.decodePlannerStore(JSON.stringify({...E.blankStore(),active:plans[0],activePlans:[]})).activePlans,[]);});
test('external import separates old history from future tracking duration',()=>{const now=new Date('2026-09-08T12:00:00Z'),oldDate='2020-01-06',preview={source:'Peptide Library CSV',totalRows:2,inventoryCount:0,historyCount:1,scheduleCount:1,peptides:['BPC-157'],warnings:[],duplicateKeys:[],rows:[{recordType:'log',peptideName:'BPC-157',date:oldDate,time:'08:00',doseMg:0.25,originalDoseAmount:250,originalDoseUnit:'mcg',eventType:'taken'},{recordType:'schedule',peptideName:'BPC-157',scheduleType:'daily',scheduleDays:[],scheduleTimes:['08:00'],startDate:oldDate}]};const setup={...P.externalSetups(preview)[0],doseMg:'0.25',doseUnit:'mcg',futureWeeks:'12',vialMg:'5',waterMl:'2'};assert.deepEqual(P.externalSetupErrors(setup),[]);const result=P.importReadyExternalPeptides({...E.blankStore(),activePlans:[]},preview,[setup],now),plan=result.store.activePlans[0];assert.equal(plan.stages[0].weeks,'12');assert.ok(plan.events.some(event=>event.localDate===oldDate&&event.status==='completed'));});
test('recent imported schedule keeps its source start as the editable cycle anchor',()=>{const now=new Date('2026-09-12T12:00:00Z'),start='2026-09-05',preview={source:'Peptide Library CSV',totalRows:2,inventoryCount:0,historyCount:1,scheduleCount:1,peptides:['5-Amino-1MQ'],warnings:[],duplicateKeys:[],rows:[{recordType:'log',peptideName:'5-Amino-1MQ',date:start,time:'09:00',doseMg:0.3,originalDoseAmount:300,originalDoseUnit:'mcg',eventType:'taken'},{recordType:'schedule',peptideName:'5-Amino-1MQ',scheduleType:'daily',scheduleDays:[],scheduleTimes:['09:00'],startDate:start}]};const setup={...P.externalSetups(preview)[0],doseMg:'0.3',doseUnit:'mcg',indefinite:true,vialMg:'10',waterMl:'2'};const plan=P.importReadyExternalPeptides({...E.blankStore(),activePlans:[]},preview,[setup],now).store.activePlans[0];assert.equal(plan.startDate,start);assert.equal(plan.stages[0].weeks,'104');assert.ok(plan.events.some(event=>event.localDate===start&&event.status==='completed'));});

test('logged import replaces a generated pending event at the same timestamp',()=>{const now=new Date('2026-09-08T07:00:00'),preview={source:'Peptide Library CSV',totalRows:2,inventoryCount:0,historyCount:1,scheduleCount:1,peptides:['BPC-157'],warnings:[],duplicateKeys:[],rows:[{recordType:'log',peptideName:'BPC-157',date:'2026-09-08',time:'08:00',doseMg:0.25,originalDoseAmount:0.25,originalDoseUnit:'mg',eventType:'taken'},{recordType:'schedule',peptideName:'BPC-157',scheduleType:'daily',scheduleDays:[],scheduleTimes:['08:00'],startDate:'2026-09-08'}]};const setup={...P.externalSetups(preview)[0],doseMg:'0.25',doseUnit:'mg',futureWeeks:'2',vialMg:'5',waterMl:'2'};const plan=P.importReadyExternalPeptides({...E.blankStore(),activePlans:[]},preview,[setup],now).store.activePlans[0],sameTime=plan.events.filter(event=>event.scheduledAt===new Date('2026-09-08T08:00:00').toISOString());assert.equal(sameTime.length,1);assert.equal(sameTime[0].status,'completed');});
test('compact persistence keeps durable history plus a rolling loggable and future window',()=>{
 const now=new Date('2026-09-08T12:00:00'),draft={...E.newDraft(library[0]),indefinite:true,stages:[{id:'stage',amountMg:'1',amountUnit:'mg',weeks:'104',override:null}],defaultSchedule:{kind:'daily',days:[],times:['09:00'],interval:null},startDate:'2026-09-01',breakWeeks:'0',vialMg:'10',waterMl:'2',reviewed:true};
 let plan=E.activate(draft,now),first=plan.events.find(event=>event.localDate==='2026-09-08');plan=E.logEvent(plan,first.id,'completed',new Date('2026-09-08T12:00:00'));
 const store={...E.blankStore(),activePlans:[plan],active:plan},raw=P.encodeCompactPlannerStore(store,now),read=P.decodeCompactPlannerStore(raw,now),events=read.activePlans[0].events;
 assert.equal(events.filter(event=>event.status==='completed').length,1);
 assert.ok(events.some(event=>event.status==='pending'&&event.localDate==='2026-09-07'));
 assert.ok(events.filter(event=>event.status==='pending').every(event=>event.localDate>='2026-08-09'&&event.localDate<='2026-10-08'));
 assert.ok(Buffer.byteLength(raw)<Buffer.byteLength(P.encodePlannerStore(store))/5);
});
test('indefinite calendar materializes a distant month without storing its occurrences',()=>{
 const now=new Date('2026-09-08T12:00:00'),draft={...E.newDraft(library[0]),indefinite:true,stages:[{id:'stage',amountMg:'1',amountUnit:'mg',weeks:'104',override:null}],defaultSchedule:{kind:'weekly',days:[1],times:['09:00'],interval:null,timesPerWeek:1},startDate:'2026-09-01',breakWeeks:'0',vialMg:'10',waterMl:'2',reviewed:true},plan=E.activate(draft,now),compact=P.compactPlannerStore({...E.blankStore(),activePlans:[plan],active:plan},now).activePlans[0];
 assert.equal(compact.events.some(event=>event.localDate.startsWith('2028-06')),false);
 assert.ok(E.materializeEvents(compact,'2028-06-01','2028-06-30').length>=4);
});
