require('./register-tests.cjs');const test=require('node:test'),assert=require('node:assert/strict'),Module=require('node:module');
const C=require('./app/src/quiet-release-core.ts');
test('24-hour policy and strictly newer release only',()=>{assert(C.checkDue(null,1));assert(!C.checkDue(1,86400000));assert(C.checkDue(1,86400001));const a={sha:'a'.repeat(40),publishedAt:100};assert(!C.newerRelease(a,a));assert(!C.newerRelease(a,{sha:'b'.repeat(40),publishedAt:99}));assert(C.newerRelease(a,{sha:'b'.repeat(40),publishedAt:101}));});
test('actual hook preserves drafts/unsynced work, has no timer, and defers interrupted reload',async()=>{
 const original=Module._load;let effects=[],events={},reloads=0,requests=0,pending=[],safe=true;const payload={plans:[]};const memory=new Map([['pepplan.cloud-sync.baseline.v1:owner',JSON.stringify({payload:JSON.stringify(payload)})]]);let fetched={sha:'b'.repeat(40),publishedAt:200};let interrupt=false;
 const doc={visibilityState:'visible',querySelector:q=>({getAttribute:()=>q.includes('release-time')?'100':'a'.repeat(40)}),addEventListener:(n,f)=>events[n]=f,removeEventListener:()=>{}};
 global.document=doc;global.window={location:{reload:()=>reloads++},addEventListener:(n,f)=>events[n]=f,removeEventListener:()=>{}};const oldfetch=global.fetch;global.fetch=async()=>{requests++;if(interrupt)events.pointerdown();return {ok:true,json:async()=>fetched};};
 Module._load=function(id,parent,main){if(parent?.filename.endsWith('/quiet-release.ts')){if(id==='react')return {useRef:v=>({current:v}),useEffect:f=>effects.push(f)};if(id==='react-native')return {Platform:{OS:'web'}};if(id==='./store')return {plannerStorage:{getItem:async k=>memory.get(k)??null,setItem:async(k,v)=>memory.set(k,v)}};if(id==='./persistence-v04')return {encodePlannerStore:JSON.stringify};if(id==='./cloud/feedback-attachments')return {pendingFeedbackDrafts:async()=>pending};}return original.call(this,id,parent,main);};
 const flush=()=>new Promise(r=>setImmediate(r));let cleanups=[];
 async function mount(){effects=[];delete require.cache[require.resolve('./app/src/quiet-release.ts')];require('./app/src/quiet-release.ts').useQuietRelease(safe,'owner',payload);cleanups=effects.map(f=>f()).filter(Boolean);await flush();}
 try{safe=false;await mount();assert.equal(requests,0);cleanups.forEach(f=>f());safe=true;pending=[{}];await mount();assert.equal(requests,0);cleanups.forEach(f=>f());pending=[];memory.delete('pepplan.cloud-sync.baseline.v1:owner');await mount();assert.equal(requests,0);cleanups.forEach(f=>f());memory.set('pepplan.cloud-sync.baseline.v1:owner',JSON.stringify({payload:JSON.stringify(payload)}));interrupt=true;await mount();assert.equal(requests,1);assert.equal(reloads,0);interrupt=false;events.visibilitychange();await flush();assert.equal(reloads,1);assert.equal(requests,1);cleanups.forEach(f=>f());await mount();assert.equal(requests,1);assert.equal(reloads,1);}finally{Module._load=original;global.fetch=oldfetch;delete global.document;delete global.window;}
});
test('app safety wiring protects editing, feedback, persistence and sync',()=>{const s=require('node:fs').readFileSync('app/App.tsx','utf8'),line=s.split('\n').find(x=>x.includes('useQuietRelease(saved.ready'));for(const guard of ['!betaAccount.state.recovery','!membershipOpen','!saved.saving','!saved.error','!saved.store.draft','!saved.store.activeEdit','!currentEdit','!feedbackBusy.current','!feedbackText','!feedbackShots.length','!feedbackPending.length','!importing','!restoreCandidate',"cloudSync.state.kind==='upToDate'"])assert(line.includes(guard),guard);const h=require('node:fs').readFileSync('app/src/quiet-release.ts','utf8');assert(!h.includes('setInterval'));assert(!h.includes('setTimeout'));});
