require('./register-tests.cjs');
const test=require('node:test'),assert=require('node:assert/strict'),Module=require('node:module');
const scheduled=new Map();let allowed=true,calls=0;
const mock={setNotificationHandler(){},AndroidImportance:{HIGH:4},SchedulableTriggerInputTypes:{DATE:'date',TIME_INTERVAL:'timeInterval'},setNotificationChannelAsync:async()=>{},getPermissionsAsync:async()=>({granted:allowed}),requestPermissionsAsync:async()=>({granted:allowed}),getAllScheduledNotificationsAsync:async()=>[...scheduled.values()],cancelScheduledNotificationAsync:async id=>{scheduled.delete(id)},scheduleNotificationAsync:async item=>{calls++;const id=item.identifier||'test';scheduled.set(id,{...item,identifier:id});return id;},addNotificationResponseReceivedListener:()=>({remove(){}})};
const original=Module._load;Module._load=function(request,parent,isMain){return request==='expo'?{isRunningInExpoGo:()=>false}:request==='expo-notifications'?mock:original.call(this,request,parent,isMain)};
const N=require('./app/src/reminders.native.ts');
const owner='peptide-planner-v03';const make=()=>({id:'test-plan',reminderEnabled:true,reminderOffsetMinutes:0,events:Array.from({length:65},(_,i)=>({id:'event-'+i,status:'pending',scheduledAt:new Date(Date.now()+3600000*(i+1)).toISOString()}))});
test('local reminder reconciliation is idempotent, bounded, private and scoped to this prototype',async()=>{
 scheduled.set('unrelated',{identifier:'unrelated',content:{data:{owner:'another-app'}}});const p=make();const report=await N.reconcileReminders(p);assert.equal(report.count,60);assert.equal(calls,60);assert.ok(scheduled.has('unrelated'));await N.reconcileReminders(p);assert.equal(calls,60);for(const n of scheduled.values())if(n.content.data.owner===owner){assert.ok(['Open EZPep Planner to review the amount and mark Taken, Skip or Remind Later.','This event is still waiting. Open EZPep Planner to mark Taken, Skip or Remind Later.'].includes(n.content.body));assert.ok(!/\b\d+(?:\.\d+)?\s*(?:mg|mcg|mL|units?)\b/i.test(n.content.body));}
 const initiallyCovered=new Set([...scheduled.values()].filter(n=>n.content.data.owner===owner&&!n.content.data.test).map(n=>n.content.data.eventId));p.events[0].status='completed';await N.reconcileReminders(p);assert.ok(![...scheduled.values()].some(n=>n.content.data.eventId==='event-0'));assert.ok([...scheduled.values()].some(n=>n.content.data.owner===owner&&!n.content.data.test&&!initiallyCovered.has(n.content.data.eventId)));
 p.events[1].snoozedUntil=new Date(Date.now()+900000).toISOString();const originalTime=p.events[1].scheduledAt;await N.reconcileReminders(p);const alarm=[...scheduled.values()].find(n=>n.content.data.eventId==='event-1'&&!n.content.data.urgent);assert.equal(new Date(alarm.trigger.date).toISOString(),p.events[1].snoozedUntil);assert.equal(p.events[1].scheduledAt,originalTime);
 await N.testReminder();await N.reconcileReminders(p);assert.ok(scheduled.has('test'));
 await N.reconcileReminders({...p,reminderEnabled:false});assert.ok(scheduled.has('unrelated'));assert.ok(scheduled.has('test'));assert.equal(scheduled.size,2);
 allowed=false;assert.equal((await N.reconcileReminders(p)).enabled,false);assert.equal(await N.enableReminders(),false);
});
test('multi-plan reminders retain each owner and offset, even for matching event IDs',async()=>{
 allowed=true;const p=make(),q={...make(),id:'second-plan',reminderOffsetMinutes:15};q.events=p.events.map(e=>({...e}));await N.reconcileReminders([p,q]);const alarms=[...scheduled.values()].filter(n=>n.content.data.owner===owner&&!n.content.data.test);assert.equal(alarms.length,60);assert.ok(alarms.some(n=>n.content.data.planId===p.id));assert.ok(alarms.some(n=>n.content.data.planId===q.id));const second=alarms.find(n=>n.content.data.planId===q.id&&n.content.data.eventId==='event-0');assert.equal(+second.trigger.date,new Date(q.events[0].scheduledAt).getTime()-15*60000);await N.reconcileReminders([{...p,reminderEnabled:false},q]);assert.ok([...scheduled.values()].filter(n=>n.content.data.owner===owner&&!n.content.data.test).every(n=>n.content.data.planId===q.id));
});
test('repeating cycle restart has a dedicated private reminder outside the event cap',async()=>{
 allowed=true;const today=new Date(),start=[today.getFullYear(),String(today.getMonth()+1).padStart(2,'0'),String(today.getDate()).padStart(2,'0')].join('-');
 const plan={id:'cycle-plan',compoundName:'Example peptide',reminderEnabled:true,reminderOffsetMinutes:0,cycleOnWeeks:'1',cycleOffWeeks:'1',startDate:start,defaultSchedule:{times:['09:00']},events:[]};
 const report=await N.reconcileReminders(plan),alarm=[...scheduled.values()].find(n=>n.content.data?.cycleResume===true);
 assert.equal(report.count,1);assert.ok(alarm);assert.equal(alarm.content.data.planId,plan.id);assert.match(alarm.content.title,/Cycle resumes/);assert.ok(!alarm.content.body.includes(plan.compoundName));
});
