const {chromium}=require('playwright');
const assert=require('node:assert/strict'),fs=require('fs');const pack=require('./app/src/school-content.v0.3.1.json'),KEY='peptide-planner:local:v04';
(async()=>{
 const profile=__dirname+'/checks/browser033-'+Date.now();let context=await chromium.launchPersistentContext(profile,{headless:true,...(process.env.PLAYWRIGHT_CHANNEL?{channel:process.env.PLAYWRIGHT_CHANNEL}:{}),viewport:{width:412,height:915}}),page=context.pages()[0];const errors=[];
 const observe=()=>{page.on('pageerror',e=>errors.push(e.message));page.on('console',m=>{if(m.type()==='error'||m.type()==='warning')errors.push(m.text())});page.setDefaultTimeout(12000)};observe();
 const b=n=>page.getByRole('button',{name:n,exact:true}),tab=n=>page.getByRole('tab',{name:n,exact:true}),field=n=>page.getByLabel(n,{exact:true}),txt=n=>page.getByText(n,{exact:true});
 const saved=()=>txt('Saved on this device').waitFor();const state=async()=>{await saved();return page.evaluate(k=>JSON.parse(localStorage.getItem(k)),KEY)};
 const shot=async name=>{await page.waitForTimeout(400);await page.screenshot({path:__dirname+'/checks/033-'+name+'.png'})};
 const school=async id=>{const c=pack.compounds.find(c=>c.id===id);await tab('Pep School').click();await field('Search Pep School').fill(c.canonicalName);await b(c.canonicalName+' 101').click();return c};
 const importPlan=async id=>{await school(id);await b('Model this in Guide →').click();if(await b('Confirm replace draft').count())await b('Confirm replace draft').click();await txt('Review My Plan').waitFor();return (await state()).draft};
 const noOverflow=async()=>assert.ok(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));
 const fit=async name=>{const l=b(name);await l.scrollIntoViewIfNeeded();const fits=await l.evaluate(e=>{const r=e.getBoundingClientRect();return r.left>=0&&r.right<=innerWidth&&Array.from(e.querySelectorAll('*')).every(n=>n.scrollWidth<=n.clientWidth+1)});assert.ok(fits,'Clipped: '+name)};
 const setTime=async(i,h,m,period)=>{await b('Time '+i).click();await field('Time '+i+' hour').selectOption(String(h));await field('Time '+i+' minute').selectOption(String(m));await field('Time '+i+' period').selectOption(period)};
 try{
 await page.goto('http://localhost:8081',{waitUntil:'networkidle',timeout:120000});await txt('Prototype 0.4').waitFor();await saved();
 for(const c of pack.compounds){await school(c.id);await txt(c.school101.whatIsIt).waitFor();await b('Learn More').click();await b('Research overview').click();await txt(c.learnMore).waitFor();await b('Sources').click();for(const src of c.sources)await txt(src.id).first().waitFor();await b('Back to Learn More').click();await b('Open in Guide').click();await b('Learn in Pep School').click();await tab('Guide').click();await field('Search Guide').fill(c.aliases[0]);await b(c.canonicalName+' Guide').waitFor();}
 console.log('PASS School, aliases, Learn More, sources, bidirectional Guide');
 let d=await importPlan('kpv');assert.deepEqual(d.stages.map(s=>s.amountMg),['0.2','0.3','0.4','0.5']);assert.deepEqual(d.stages.map(s=>s.weeks),['1','1','1','5']);assert.equal(d.vialMg,'10');assert.equal(d.waterMl,'2');assert.deepEqual(d.defaultSchedule.times,['09:00']);await txt('200 mcg').waitFor();await b('Complete plan').waitFor();assert.equal(await b('Looks good — Continue').count(),0);await shot('kpv-review');
 await b('Customize').click();await b('Edit stage 1').click();assert.equal(await field('Stage 1 amount').inputValue(),'200');await field('Stage 1 amount').fill('250');d=(await state()).draft;assert.equal(d.stages[0].amountMg,'0.25');assert.equal(d.customized,true);await field('Stage 1 amount').fill('200');await page.getByRole('radio',{name:'Stage 1 unit mg',exact:true}).click();assert.equal(await field('Stage 1 amount').inputValue(),'0.2');assert.equal((await state()).draft.stages[0].amountMg,'0.2');await page.getByRole('radio',{name:'Stage 1 unit mcg',exact:true}).click();assert.equal(await field('Stage 1 amount').inputValue(),'200');await b('Edit stage 1').click();await shot('stage-timeline');
 await b('Change plan default schedule').click();await b('Daily').click();await setTime(1,9,0,'AM');await b('+ Add another time').click();await field('Time 2 hour').selectOption('9');await field('Time 2 period').selectOption('PM');await b('Save schedule').click();d=(await state()).draft;assert.deepEqual(d.defaultSchedule.times,['09:00','21:00']);assert.ok(d.stages.every(s=>s.override===null));
 await b('Change stage 2 schedule').click();await b('Daily').click();await b('Save schedule').click();assert.ok((await state()).draft.stages.every(s=>!s.override));await b('Change stage 2 schedule').click();await b('Mon / Wed / Fri').click();await b('Save schedule').click();d=(await state()).draft;assert.deepEqual(d.stages[1].override.days,[1,3,5]);await txt('Stage-specific schedule').waitFor();await b('Use plan default for stage 2').click();assert.ok((await state()).draft.stages.every(s=>!s.override));
 for(const width of [412,320]){await page.setViewportSize({width,height:915});await noOverflow();await shot('stages-'+width);await b('Change plan default schedule').click();for(const name of ['Daily','Once weekly','Mon / Wed / Fri','Every other day','Specific days'])await fit(name);await b('Advanced schedules').click();for(const name of ['Every X days','X times per week','Multiple times per day','Custom interval'])await fit(name);await noOverflow();await b('Daily').scrollIntoViewIfNeeded();await shot('schedule-'+width);await b('Cancel').click();for(const name of ['Pep School','Guide','My Peptides','TODAY','More']){const box=await tab(name).boundingBox();assert.ok(box.x>=0&&box.x+box.width<=width);}}
 await page.setViewportSize({width:412,height:915});
 // Each repaired reference survives review, scheduling, calculation and activation.
 for(const id of ['kpv','ghk-cu','glow70','retatrutide','tirzepatide','semaglutide']){
 d=await importPlan(id);assert.equal(d.setupOrigin.sourceClass,'Common Research Setup');await txt('CALCULATION SETUP').waitFor();const expected={kpv:[10,2,5],retatrutide:[10,2,5],tirzepatide:[10,2,5],semaglutide:[10,2,5],'ghk-cu':[50,3,50/3],glow70:[70,3,70/3]}[id];assert.equal(d.vialMg,String(expected[0]));assert.equal(d.waterMl,String(expected[1]));assert.equal(d.setupOrigin.original.concentrationMgMl,expected[2]);const original=JSON.parse(JSON.stringify(d));await b('Complete plan').click();await txt('Schedule your plan').waitFor();
 const yesterday=await page.evaluate(()=>{const x=new Date();x.setDate(x.getDate()-1);return x.getFullYear()+'-'+String(x.getMonth()+1).padStart(2,'0')+'-'+String(x.getDate()).padStart(2,'0')});await field('Start date').fill(yesterday);if(d.breakWeeks==='')await b('No planned break').click();await b('Continue to Vial Setup').click();
 assert.equal(await field('Vial strength (mg)').inputValue(),original.vialMg);assert.equal(await field('Diluent volume (mL)').inputValue(),original.waterMl);
 if(id==='retatrutide'){await txt('40 UNITS').waitFor();assert.equal((await state()).draft.customized,false);await field('Vial strength (mg)').fill('20');await field('Diluent volume (mL)').fill('3');let edited=(await state()).draft;assert.equal(edited.setupOrigin.customized,true);assert.equal(edited.customized,false);assert.deepEqual(edited.origin,original.origin);await field('Vial strength (mg)').fill('');await txt('— UNITS').waitFor();assert.equal(await b('Start Plan').count(),0);assert.ok(await b('Complete vial setup').isDisabled());assert.equal(await txt('Ready to start?').count(),0);await txt('Confirm your vial').waitFor();await b('Vial 10 mg').click();await b('BAC water 2 mL').click();assert.equal(await page.getByRole('radio',{name:'0.5 mL syringe'}).isChecked(),true);assert.equal(await page.getByTestId('syringe-draw-mark').getAttribute('x1'),'246');await page.getByRole('radio',{name:'0.3 mL syringe'}).click();await page.getByRole('alert').waitFor();await txt('40 UNITS').waitFor();assert.equal(await page.getByTestId('syringe-draw-mark').getAttribute('x1'),'300');await shot('oversized');await page.getByRole('radio',{name:'0.5 mL syringe'}).click();}
 if(id==='kpv'){await txt('4 UNITS').waitFor();await txt('Amount: 200 mcg').waitFor();await txt('0.04 mL   ·   5 mg/mL').waitFor();assert.equal(await page.getByRole('radio',{name:'0.3 mL syringe'}).isChecked(),true);assert.equal(await page.getByTestId('syringe-draw-mark').getAttribute('x1'),'66');await page.getByTestId('syringe-units').scrollIntoViewIfNeeded();await shot('kpv-syringe');await page.getByRole('radio',{name:'1.0 mL syringe'}).click();await txt('4 UNITS').waitFor();assert.equal(await page.getByTestId('syringe-draw-mark').getAttribute('x1'),'40.8');await page.setViewportSize({width:320,height:915});await noOverflow();await shot('syringe-320');await page.setViewportSize({width:412,height:915});}if(id==='tirzepatide')await txt('50 UNITS').waitFor();if(id==='semaglutide')await txt('5 UNITS').waitFor();if(id==='ghk-cu')await txt('6 UNITS').waitFor();if(id==='glow70'){await txt('9.986 UNITS').waitFor();await txt('Reference draw · 10 units').waitFor();await txt('GHK-Cu: 1.6643 mg').waitFor();await shot('glow-calculation');}
 assert.equal(await field('Number of individual vials').inputValue(),'');await b('Back to schedule').click();await b('Back to stages').click();await b('Continue to Schedule').click();await b('Continue to Vial Setup').click();await b('Continue to Review').click();await b('Start Plan').click();await b('View '+original.compoundName+' plan').click();await b('Open Today').click();await tab('Today').waitFor();let active=(await state()).activePlans.at(-1);assert.deepEqual(active.stages,original.stages);assert.deepEqual(active.origin,original.origin);assert.deepEqual(active.defaultSchedule,original.defaultSchedule);assert.equal(active.vialMg,id==='retatrutide'?'10':original.vialMg);assert.equal(active.waterMl,original.waterMl);assert.deepEqual(active.setupOrigin.original,original.setupOrigin.original);if(id==='kpv'){assert.equal(active.syringeCapacityUnits,100);assert.equal(await page.getByRole('radio',{name:'1.0 mL syringe'}).isChecked(),true);await page.getByRole('radio',{name:'0.3 mL syringe'}).click();assert.equal((await state()).activePlans.at(-1).syringeCapacityUnits,30);}
 if(id==='kpv'){await b('Completed').click();await page.waitForTimeout(750);await saved();active=(await state()).activePlans.at(-1);assert.equal(active.events.filter(e=>e.status==='completed').length,1);await tab('History').click();await txt('Completed').first().waitFor();await tab('Calendar').click();await shot('calendar');await tab('Today').click();}
 console.log('PASS '+id+' reference → review → schedule → calculator → Tracker');
 }
 const before=await state();assert.equal(before.activePlans.length,6);assert.equal(before.archives.length,0);await context.close();context=await chromium.launchPersistentContext(profile,{headless:true,...(process.env.PLAYWRIGHT_CHANNEL?{channel:process.env.PLAYWRIGHT_CHANNEL}:{}),viewport:{width:412,height:915}});page=context.pages()[0];observe();await page.goto('http://localhost:8081',{waitUntil:'networkidle'});await saved();assert.deepEqual(await state(),before);await tab('TODAY').click();await tab('Today').waitFor();await tab('History').click();await txt('Completed').first().waitFor();
 assert.deepEqual(errors,[]);fs.writeFileSync(__dirname+'/checks/033-ui-results.json',JSON.stringify({passed:true,widths:[320,412],errors,profile},null,2));console.log('PASS browser restart persistence and archived history; no console/runtime errors');
 }finally{await context.close()}
})().catch(e=>{console.error(e);process.exit(1)});
