import {createHmac,timingSafeEqual,createHash} from 'node:crypto';
export const ACCOUNT='acct_17bPbQKz1yOMLEBX',PROJECT='https://csolruvoeukctlybiemd.supabase.co';
export function verifySignature(raw,header,secret,now=Date.now()){
 if(!secret||typeof header!=='string'||Buffer.byteLength(raw)>262144)throw Error('INVALID_SIGNATURE');const parts=header.split(','),stamp=parts.find(x=>x.startsWith('t='))?.slice(2);if(!/^\d+$/.test(stamp??'')||Math.abs(now-Number(stamp)*1000)>300000)throw Error('INVALID_SIGNATURE');
 const expected=createHmac('sha256',secret).update(stamp+'.'+raw).digest();if(!parts.filter(x=>x.startsWith('v1=')).some(x=>{const h=x.slice(3);return /^[a-f0-9]{64}$/.test(h)&&timingSafeEqual(expected,Buffer.from(h,'hex'));}))throw Error('INVALID_SIGNATURE');return JSON.parse(raw);
}
export class StripeTest {
 constructor(config,fetcher=fetch){this.c=config;this.fetch=fetcher;}
 async api(path,params=null,key=null){if(!/^(sk|rk)_test_/.test(this.c.secret??''))throw Error('STRIPE_TEST_SECRET_REQUIRED');if(!/^\/(account|prices\/price_[A-Za-z0-9]+|customers|coupons\/[A-Za-z0-9_-]+|checkout\/sessions(?:\/cs_test_[A-Za-z0-9]+)?|billing_portal\/sessions|events\/evt_[A-Za-z0-9]+|subscriptions\/sub_[A-Za-z0-9]+|invoices(?:\/in_[A-Za-z0-9]+)?|charges\/ch_[A-Za-z0-9]+|payment_intents\/pi_[A-Za-z0-9]+)(?:\?.*)?$/.test(path))throw Error('FIXED_STRIPE_OPERATION');const r=await this.fetch('https://api.stripe.com/v1'+path,{method:params?'POST':'GET',redirect:'error',headers:{authorization:'Bearer '+this.c.secret,'Stripe-Version':'2024-06-20',...(params?{'content-type':'application/x-www-form-urlencoded'}:{}),...(key?{'Idempotency-Key':key}:{})},body:params?new URLSearchParams(params).toString():undefined,signal:AbortSignal.timeout(15000)});if(!r.ok)throw Error(r.status===401||r.status===403?'STRIPE_AUTH_FAILED':'STRIPE_REQUEST_FAILED');return r.json();}
 async readiness(){const account=await this.api('/account');if(account.id!==ACCOUNT)throw Error('STRIPE_ACCOUNT_MISMATCH');const p=await this.api('/prices/'+this.c.price);if(p.livemode!==false||!p.active||p.currency!=='cad'||p.unit_amount!==899||p.recurring?.interval!=='month'||p.recurring?.interval_count!==1)throw Error('PRICE_MISMATCH');return {account_match:true,test_mode:true,currency:'cad',monthly_cents:899};}
 async checkout(attempt,user){await this.readiness();if(attempt.promotion){const p=attempt.promotion,c=await this.api('/coupons/'+p.coupon);if(c.livemode!==false||!c.valid||c.currency!=='cad'||c.amount_off!==p.amount_off||!(p.months===1&&c.duration==='once'||c.duration==='repeating'&&c.duration_in_months===p.months))throw Error('PROMOTION_MISMATCH');}const customer=await this.api('/customers',{'metadata[ezpep_user]':user,'metadata[product]':'ezpep'},'ezpep-test-customer:'+user);const params={mode:'subscription',customer:customer.id,'line_items[0][price]':this.c.price,'line_items[0][quantity]':'1',success_url:'https://app.ezpepplanner.com/website-preview/?checkout=returned',cancel_url:'https://app.ezpepplanner.com/website-preview/?checkout=cancelled','subscription_data[metadata][ezpep_user]':user,'subscription_data[metadata][attempt_id]':attempt.id,'subscription_data[metadata][product]':'ezpep','metadata[attempt_id]':attempt.id,expires_at:String(Math.floor(Date.now()/1000)+1800)};if(attempt.coupon)params['discounts[0][coupon]']=attempt.coupon;return this.api('/checkout/sessions',params,'ezpep-test-checkout:'+attempt.id);}
 async portal(customer){return this.api('/billing_portal/sessions',{customer,return_url:'https://app.ezpepplanner.com/website-preview/'},null);}
 async canonical(event){const e=await this.api('/events/'+event.id);if(e.livemode!==false||e.id!==event.id)throw Error('EVENT_ENVIRONMENT_MISMATCH');let obj=e.data.object,subid;if(e.type.startsWith('customer.subscription.'))subid=obj.id;else if(e.type.startsWith('invoice.'))subid=obj.subscription;else if(e.type==='charge.refunded'){if(!obj.invoice)return null;obj=await this.api('/invoices/'+obj.invoice);subid=obj.subscription;}else return null;if(!/^sub_[A-Za-z0-9]+$/.test(subid??''))return null;return {event:e,subscription_id:subid};}
 async snapshot(id){const s=await this.api('/subscriptions/'+id);if(s.livemode!==false||s.metadata?.product!=='ezpep')throw Error('SUBSCRIPTION_SCOPE');const list=await this.api('/invoices?subscription='+encodeURIComponent(id)+'&limit=100');if(list.has_more)throw Error('RECONCILIATION_PAGE_REQUIRED');const invoices=[];for(const i of list.data){if(!i.paid)continue;if(i.paid_out_of_band||!i.charge)throw Error('COLLECTED_REVENUE_VERIFICATION_REQUIRED');if(i.currency!=='cad'||i.livemode!==false)throw Error('INVOICE_CURRENCY_MODE');let refund=0;if(i.charge){const c=await this.api('/charges/'+i.charge);if(c.livemode!==false||c.customer!==s.customer||!c.paid||!c.captured)throw Error('CHARGE_SCOPE');refund=c.amount_refunded??0;}const revenue=Math.max(0,i.amount_paid-(i.tax??0));invoices.push({id:i.id,paid:true,revenue,refunded:Math.min(revenue,Math.floor(refund*revenue/Math.max(1,i.amount_paid))),paid_at:i.status_transitions.paid_at*1000,period_end:Math.max(...i.lines.data.map(x=>x.period.end))*1000});}
 return {subscription_id:s.id,attempt_id:s.metadata.attempt_id,user_id:s.metadata.ezpep_user,customer_id:s.customer,status:s.status,currency:s.currency,livemode:s.livemode,invoices};}
}
export class Membership {
 constructor(store,stripe){this.store=store;this.stripe=stripe;}
 async checkout(user,{testEnabled=false}={}){if(!testEnabled)throw Error('BILLING_DISABLED');const token=this.store.claim('checkout:'+user);try{const promo=this.store.promotion(),a=this.store.reserve(user,promo);if(a.promo_version){const saved=this.store.get('SELECT * FROM promotions WHERE version=?',a.promo_version);a.coupon=saved.coupon;a.promotion=saved;}if(a.state==='paid')throw Error('ALREADY_SUBSCRIBED');if(a.url)return {url:a.url,reused:true};if(Date.now()-a.created_at>23*3600000)throw Error('CHECKOUT_RECONCILIATION_REQUIRED');try{const s=await this.stripe.checkout(a,user);if(s.livemode!==false||!/^https:\/\/checkout\.stripe\.com\//.test(s.url??''))throw Error('CHECKOUT_RESPONSE_REJECTED');this.store.run("UPDATE attempts SET state='open',url=?,session_id=? WHERE id=?",s.url,s.id,a.id);return {url:s.url};}catch(e){this.store.run("UPDATE attempts SET state='uncertain' WHERE id=?",a.id);throw e;}}finally{this.store.release('checkout:'+user,token);}}
 async portal(user){const s=this.store.get('SELECT customer_id FROM subscriptions WHERE user_id=? ORDER BY snapshot_at DESC LIMIT 1',user);if(!s)throw Error('MEMBERSHIP_NOT_FOUND');const p=await this.stripe.portal(s.customer_id);if(!/^https:\/\/billing\.stripe\.com\//.test(p.url??''))throw Error('PORTAL_RESPONSE_REJECTED');return {url:p.url};}
 async webhook(event,raw){const canonical=await this.stripe.canonical(event);if(!canonical)return {ignored:true};const name=canonical.subscription_id,token=this.store.claim(name);try{const snapshot=await this.stripe.snapshot(name);return this.store.apply({id:event.id,hash:createHash('sha256').update(raw).digest('hex')},snapshot,token);}finally{this.store.release(name,token);}}
}
// Existing Supabase identity is verified server-side; no new account or planner access.
export async function authenticate(bearer,publishable,fetcher=fetch){if(!/^Bearer [A-Za-z0-9_.-]+$/.test(bearer??''))throw Error('AUTH_REQUIRED');const r=await fetcher(PROJECT+'/auth/v1/user',{headers:{authorization:bearer,apikey:publishable},redirect:'error',signal:AbortSignal.timeout(10000)});if(!r.ok)throw Error('AUTH_REQUIRED');const u=await r.json();if(!/^[a-f0-9-]{36}$/.test(u.id??''))throw Error('AUTH_REQUIRED');return u.id;}
