import React,{useRef,useState} from 'react';
import {ScrollView,View,Text,Pressable,Modal} from 'react-native';
import Svg,{Rect,Path} from 'react-native-svg';
import type {SavedPlan,ActiveEdit,Draft} from './engine';
import {uid,scheduleSummary,stageAmount,actualProgress,prettyDate,validateDraft,buildTaperStages} from './engine';
import {stageDays} from './duration';
import {calculate} from './planning';
import {inventoryProjection} from './inventory-maintenance';
import {applyActiveEdit} from './active-edit-v04';
import {blankStore} from './engine';
import StageCard from './StageCard';
import ScheduleSheet from './ScheduleSheet';
import CyclePattern,{type PlanTimingMode} from './CyclePattern';
import Syringe from './Syringe';
import {quantityFromMg} from './quantities';
import {Button,Field,Card,ProfessorHelp,u,C} from './ui';
const sectionHelp:Record<string,{body:string;note?:string}>={
 'Dose & Stages':{body:'Stages divide a plan into consecutive periods. Each stage can use its own amount, duration and schedule. Removing a stage renumbers the remaining stages and updates future events after you save.',note:'Past and already logged events retain their saved amounts and calculations.'},
 'Schedule':{body:'The default schedule applies across the plan. A stage-specific schedule changes only that stage. Review both the selected weekdays and times before saving.'},
 'Vial & Concentration':{body:'Vial strength is the total peptide amount shown on the vial. Diluent volume is the amount used in this calculation model. Together they determine concentration and draw volume.',note:'These fields model values you enter; they do not verify preparation or clinical suitability.'},
 'Syringe':{body:'The syringe selection changes the displayed U-100 scale so the draw marker is easier to read. It does not change the plan amount, concentration or calculated volume.'},
 'Inventory':{body:'Inventory records individual vials and estimates remaining mass from events marked Taken. Scheduled, skipped and unlogged events do not consume recorded supply.'},
 'Cycle / Break':{body:'Choose Run once for a plan that ends after a set length, No planned end for ongoing tracking, or Repeat with breaks for alternating active and break periods.',note:'Timing changes future events only. Saved history remains unchanged.'},
 'Reminders':{body:'The first alert follows the saved event time and offset. A follow-up can appear later when the event is still unlogged. Device settings ultimately control notification delivery.'},
 'Pause / Archive':{body:'Pause temporarily hides pending events and suppresses new reminders while dates continue. Archive removes the plan from active tracking but keeps its saved history.'},
};
function SectionTitle({name,onLayout}:{name:string;onLayout?:(y:number)=>void}){const help=sectionHelp[name];return <View onLayout={event=>onLayout?.(event.nativeEvent.layout.y)} style={[u.row,{marginTop:22,marginBottom:4}]}><Text style={[u.heading,{marginBottom:0,flex:1}]}>{name}</Text><ProfessorHelp title={name} body={help.body} note={help.note}/></View>;}
function Vials({count,compact=false}:{count:number;compact?:boolean}){const cap=compact?4:8,shown=Math.min(cap,Math.ceil(Math.max(0,count)));return <View style={[u.row,{marginVertical:compact?7:12}]} accessibilityLabel={'Estimated remaining supply '+count.toFixed(2)+' vial equivalents'}>{count<0?<View style={[u.evidence,{flex:1}]}><Text style={u.heading}>Inventory deficit: {Number(Math.abs(count).toFixed(3))} vial equivalents</Text><Text style={u.small}>Logging remains available. Add or correct inventory when convenient.</Text></View>:<>{Array.from({length:shown},(_,i)=><Svg key={i} testID="inventory-vial" width={compact?26:30} height={compact?45:52} viewBox="0 0 30 52"><Rect x={8} y={1} width={14} height={7} rx={2} fill="#933bdd"/><Path d="M9 8v7l-4 5v26q0 4 4 4h12q4 0 4-4V20l-4-5V8" stroke="#9165bf" strokeWidth={1.5} fill="#f5edfc"/><Rect x={7} y={47-Math.min(1,Math.max(0,count-i))*26} width={16} height={Math.min(1,Math.max(0,count-i))*26} rx={2} fill="#bd65df"/><Path d="M10 27h10M10 31h7" stroke="white" strokeWidth={1.5}/></Svg>)}{count>cap&&<Text style={u.small}>+ {Number((count-cap).toFixed(1))} vial equivalents</Text>}{count===0&&<Text style={u.small}>No supply recorded as remaining</Text>}</>}</View>;}
export default function ActivePeptideEditor({plan,edit,change,onSave,onCancel,onArchive,initialSection}:{plan:SavedPlan;edit:ActiveEdit;change:(edit:ActiveEdit)=>Promise<void>;onSave:()=>Promise<void>;onCancel:()=>Promise<void>;onArchive:()=>Promise<void>;initialSection?:string}){
 const [sheet,setSheet]=useState<number|null|undefined>(),[error,setError]=useState(''),[showValidation,setShowValidation]=useState(false),[busy,setBusy]=useState(false),[confirm,setConfirm]=useState(false),[showTaper,setShowTaper]=useState(false),[taperType,setTaperType]=useState<'fixed'|'percentage'>('fixed'),[taperIncrement,setTaperIncrement]=useState('1'),[taperPeriod,setTaperPeriod]=useState('1'),[taperUnit,setTaperUnit]=useState<'days'|'weeks'>('weeks'),[taperSteps,setTaperSteps]=useState('4'),[timingChoice,setTimingChoice]=useState<PlanTimingMode|null>(null);
 const [inventoryManager,setInventoryManager]=useState(initialSection==='Inventory');
 const [scrollTarget,setScrollTarget]=useState(initialSection==='Inventory'?'':initialSection??'');
 const scrollRef=useRef<ScrollView>(null),didScroll=useRef(false);
 const d=edit.draft;
 const singleStage=d.stages.length===1;
 const savedTimingMode:PlanTimingMode=d.cycleOnWeeks||d.cycleOffWeeks?'repeat':d.indefinite?'ongoing':'once';
 const timingMode=timingChoice??savedTimingMode;
 const repeatingIncomplete=timingMode==='repeat'&&(!/^\d+$/.test(d.cycleOnWeeks||'')||!/^\d+$/.test(d.cycleOffWeeks||'')||Number(d.cycleOnWeeks)<1||Number(d.cycleOffWeeks)<1);
 const validationMessages=showValidation?validateDraft({...d,reviewed:true}):[];
 const vialError=showValidation&&(!d.vialMg.trim()||!Number.isFinite(Number(d.vialMg))||Number(d.vialMg)<=0)?'Enter a positive vial strength in mg.':undefined;
 const waterError=showValidation&&(!d.waterMl.trim()||!Number.isFinite(Number(d.waterMl))||Number(d.waterMl)<=0)?'Enter a positive diluent volume in mL.':undefined;
 const startDateError=showValidation?validationMessages.find(message=>message.includes('valid start date')):undefined;
 const inventoryIssue=!!edit.inventoryChange&&(!edit.inventoryChange.value.trim()||!Number.isFinite(Number(edit.inventoryChange.value))||Number(edit.inventoryChange.value)<0||edit.inventoryChange.kind==='add'&&(!Number.isSafeInteger(Number(edit.inventoryChange.value))||Number(edit.inventoryChange.value)<1)||edit.inventoryChange.kind==='current'&&Number(edit.inventoryChange.value)>Number(d.vialMg));
 const inventoryError=showValidation&&inventoryIssue?(edit.inventoryChange?.kind==='add'?'Add a positive whole number of individual vials.':edit.inventoryChange?.kind==='current'?'Enter an amount no greater than the vial strength.':'Enter a valid non-negative supply quantity.'):undefined;
 const patch=(p:Partial<Draft>)=>change({...edit,draft:{...d,...p,customized:true,...(d.setupOrigin&&('vialMg' in p||'waterMl' in p||'syringeCapacityUnits' in p)?{setupOrigin:{...d.setupOrigin,customized:true}}:{})}}).catch(e=>setError(String(e)));
 const run=async(fn:()=>Promise<void>)=>{setBusy(true);setError('');try{await fn();}catch(e){setError(String(e));}finally{setBusy(false);}};
 let preview=plan;try{preview=applyActiveEdit({...blankStore(),active:plan,activePlans:[plan]},edit).active!;}catch{}
 const supply=inventoryProjection(preview),progress=actualProgress(preview),current=d.stages[progress.stageIndex]??d.stages[0],calc=current?calculate(d.vialMg,d.waterMl,current.amountMg):null;
 const firstHistoryDate=plan.events.filter(event=>event.status!=='pending'&&event.localDate<d.startDate).map(event=>event.localDate).sort()[0];
 const inventoryAction=(kind:'add'|'correct'|'current')=>{change({...edit,inventoryChange:{kind,value:''}}).catch(e=>setError(String(e)));};
 const generateTaper=()=>{try{const stages=buildTaperStages(d.stages[0],{type:taperType,increment:taperIncrement,period:taperPeriod,periodUnit:taperUnit,steps:taperSteps});patch({indefinite:false,stages});setShowTaper(false);setError('');}catch(e){setError(String(e));}};
 const requestedSection=(name:string)=>(y:number)=>{if(scrollTarget===name&&!didScroll.current){didScroll.current=true;setTimeout(()=>scrollRef.current?.scrollTo({y:Math.max(0,y-18),animated:false}),0);}};
 const inventoryModal=edit.inventoryChange&&<Modal transparent animationType="fade" onRequestClose={()=>change({...edit,inventoryChange:undefined}).catch(()=>{})}><View style={{flex:1,backgroundColor:'#0e1c4a77',justifyContent:'center',padding:24}}><Card><Text style={u.heading}>{edit.inventoryChange.kind==='add'?'Add new vials':edit.inventoryChange.kind==='current'?'Update open vial':'Correct total inventory'}</Text><Text style={u.body}>Current balance: {supply.vials===null?'Not entered':Number(supply.vials.toFixed(3))+' vial equivalents'}</Text><Text style={u.small}>Saved vial setup: {d.vialMg} mg vial · {d.waterMl} mL bacteriostatic water</Text><Field label={edit.inventoryChange.kind==='current'?'Amount remaining in open vial (mg)':'Number of vial equivalents'} value={edit.inventoryChange.value} numeric placeholder={edit.inventoryChange.kind==='add'?'Whole vials to add':'Correct remaining amount'} onChange={v=>{setShowValidation(false);change({...edit,inventoryChange:{...edit.inventoryChange!,value:v}}).catch(e=>setError(String(e)));}} error={inventoryError}/><Text style={u.small}>{edit.inventoryChange.kind==='add'?'Adds newly purchased whole vials to the current balance.':edit.inventoryChange.kind==='current'?'Updates only the estimated amount in the open vial. Full unopened vials stay unchanged.':'Replaces the complete remaining balance. Use this only to correct a mismatch.'}</Text><Button label="Save inventory" disabled={busy||inventoryIssue} onPress={()=>run(onSave)}/><Button label="Cancel" secondary disabled={busy} onPress={()=>change({...edit,inventoryChange:undefined}).catch(e=>setError(String(e)))}/></Card></View></Modal>;
 if(inventoryManager)return <ScrollView keyboardShouldPersistTaps="handled" contentContainerStyle={u.scroll}><Text style={u.label}>INVENTORY MANAGER</Text><Text style={u.title}>{plan.compoundName}</Text><Text style={u.body}>Update the supply you have on hand without changing the plan's dose or schedule.</Text><Card><Text style={u.label}>SAVED VIAL SETUP</Text><Text style={u.heading}>{d.vialMg} mg vial · {d.waterMl} mL bacteriostatic water</Text><Text style={u.small}>This setup is used for inventory estimates. Change it in Vial & Concentration only when the vial strength or water amount changes.</Text></Card><Card><Text style={u.label}>CURRENT SUPPLY</Text><Text testID="remaining-vials" style={u.heading}>{supply.vials===null?'Supply not entered':Number(supply.vials.toFixed(3))+' vial equivalents'}</Text>{supply.vials!==null&&<><Vials count={supply.vials}/><Text style={u.small}>Each bottle represents one saved vial equivalent. A partly filled bottle represents the estimated open vial.</Text></>}<Text style={u.body}>Open vial estimate: {supply.currentMg===null?'Unknown':Number(supply.currentMg.toFixed(3))+' mg remaining'}</Text><Text testID="supply-projection" style={u.body}>{supply.supply===null?'Enter inventory for a coverage estimate.':!supply.future.length?'No upcoming doses to estimate.':supply.covered+' scheduled doses · about '+supply.days+' days of coverage'}</Text></Card><Card><Text style={u.heading}>What would you like to update?</Text><Button label="Add newly purchased vials" onPress={()=>inventoryAction('add')}/><Button label="Update the open vial amount" secondary onPress={()=>inventoryAction('current')}/><Button label="Correct the complete inventory total" secondary onPress={()=>inventoryAction('correct')}/><Text style={u.small}>Most of the time, use Add newly purchased vials. The correction option is for fixing an inventory mismatch.</Text></Card><Button label="Edit vial setup" secondary onPress={()=>{setScrollTarget('Vial & Concentration');didScroll.current=false;setInventoryManager(false);}}/><Button label="Close inventory manager" secondary onPress={()=>initialSection==='Inventory'?run(onCancel):setInventoryManager(false)}/>{!!error&&<Text accessibilityLiveRegion="polite" style={u.error}>{error}</Text>}{inventoryModal}</ScrollView>;
 return <ScrollView ref={scrollRef} keyboardShouldPersistTaps="handled" contentContainerStyle={u.scroll}>
 <Text style={u.label}>ACTIVE PEPTIDE EDITOR</Text><Text style={u.title}>{plan.compoundName}</Text><Text style={u.small}>Maintain this peptide. Past and logged events keep their original amounts and calculations.</Text>
 <Text style={[u.small,{marginTop:10}]}>Edit any fields below, then save all changes once at the bottom. Schedule controls open in a focused window without leaving this page.</Text>
 <SectionTitle name="Dose & Stages"/><Card><Text style={u.heading}>Optional taper builder</Text><Text style={u.small}>Start with Stage 1, then generate a fixed or percentage increase. You can review and edit every stage before saving.</Text><Button label={showTaper?'Close taper builder':'Build stages from Stage 1'} secondary onPress={()=>setShowTaper(!showTaper)}/>{showTaper&&<><View style={u.row}>{(['fixed','percentage'] as const).map(type=><Pressable key={type} accessibilityRole="radio" accessibilityState={{checked:taperType===type}} onPress={()=>setTaperType(type)} style={[u.pill,taperType===type&&u.selected]}><Text style={u.body}>{type==='fixed'?'Fixed amount':'Percentage'}</Text></Pressable>)}</View><Field label={taperType==='fixed'?'Increase each stage (mg)':'Increase each stage (%)'} value={taperIncrement} numeric onChange={setTaperIncrement}/><View style={u.row}><View style={{flex:1}}><Field label="Change every" value={taperPeriod} numeric onChange={setTaperPeriod}/></View>{(['days','weeks'] as const).map(unit=><Pressable key={unit} accessibilityRole="radio" accessibilityState={{checked:taperUnit===unit}} onPress={()=>setTaperUnit(unit)} style={[u.pill,taperUnit===unit&&u.selected]}><Text style={u.body}>{unit}</Text></Pressable>)}</View><Field label="Total stages" value={taperSteps} numeric onChange={setTaperSteps}/><Button label="Generate editable stages" onPress={generateTaper}/></>}</Card>{d.stages.map((stage,i)=><StageCard key={stage.id} stage={stage} index={i} previousDays={d.stages.slice(0,i).reduce((n,s)=>n+stageDays(s),0)} startDate={d.startDate} schedule={d.defaultSchedule} last={i===d.stages.length-1} edit={p=>patch({stages:d.stages.map(s=>s.id===stage.id?{...s,...p}:s)})} startExpanded ongoing={!!d.indefinite&&d.stages.length===1} errors={validationMessages.filter(message=>message.startsWith('Stage '+(i+1)+':'))} onRemove={d.stages.length>1?()=>patch({indefinite:false,stages:d.stages.filter(item=>item.id!==stage.id)}):undefined} onToggleOngoing={undefined}/>)}<Button label="+ Add stage" secondary disabled={d.stages.length>=24} onPress={()=>patch({indefinite:false,stages:[...d.stages,{id:uid(),amountMg:'',amountUnit:'mg',weeks:'',override:null}]})}/>
 <SectionTitle name="Schedule"/><Text style={u.body}>{scheduleSummary(d.defaultSchedule)}</Text><Button label="Change default schedule" onPress={()=>setSheet(null)}/>{d.stages.map((s,i)=><Button key={s.id} label={'Change stage '+(i+1)+' schedule'} secondary onPress={()=>setSheet(i)}/>)}
 <SectionTitle name="Vial & Concentration" onLayout={requestedSection('Vial & Concentration')}/><Field label="Vial strength (mg)" value={d.vialMg} numeric onChange={v=>patch({vialMg:v})} error={vialError}/><Field label="Diluent volume (mL)" value={d.waterMl} numeric onChange={v=>patch({waterMl:v})} error={waterError}/><Text style={u.small}>{calc?calc.concentration+' mg/mL':'Enter valid setup values.'} · Existing supply mass stays unchanged. Correct inventory separately if needed.</Text>
 <SectionTitle name="Syringe"/><Text style={u.small}>Live preview for {current?'the current stage · '+stageAmount(current):'the amount you enter'}. It updates as you change the amount, vial strength or diluent.</Text><Syringe capacityOverride={d.syringeCapacityUnits??null} onCapacityChange={size=>patch({syringeCapacityUnits:size})} result={calc} amount={quantityFromMg(current?.amountMg,current?.amountUnit)} glow={d.compoundId==='glow-70'}/><Text style={u.small}>Syringe size changes the display scale, never the amount or calculation.</Text>
 <SectionTitle name="Inventory"/><Card><View style={u.row}><View style={{flex:1}}><Text style={u.heading}>{d.inventoryTracking===false?'Inventory tracking is off':supply.vials===null?'Supply not entered':Number(supply.vials.toFixed(2))+' vial equivalents'}</Text><Text style={u.body}>{d.inventoryTracking===false?'Scheduling and logging continue normally.':!supply.future.length?'No upcoming doses to estimate.':supply.covered+' doses · about '+supply.days+' days of coverage'}</Text>{d.inventoryTracking!==false&&supply.vials!==null&&<Vials count={supply.vials} compact/>}<Text style={u.small}>Saved setup: {d.vialMg} mg vial · {d.waterMl} mL bacteriostatic water</Text></View></View><Button label="Manage inventory" onPress={()=>setInventoryManager(true)}/><Pressable accessibilityRole="checkbox" accessibilityLabel="Track vial inventory and low-supply warnings" accessibilityState={{checked:d.inventoryTracking!==false}} onPress={()=>patch({inventoryTracking:d.inventoryTracking===false})} style={u.evidence}><Text style={u.body}>{d.inventoryTracking===false?'○':'✓'} Track inventory and low-supply warnings</Text></Pressable></Card>
 <SectionTitle name="Cycle / Break"/><Field label="Start date (YYYY-MM-DD)" value={d.startDate} onChange={v=>patch({startDate:v})} error={startDateError}/>{firstHistoryDate&&<Button label={'Use first saved history date · '+prettyDate(firstHistoryDate)} secondary onPress={()=>patch({startDate:firstHistoryDate})}/>}<Card><CyclePattern mode={timingMode} basic={singleStage} onWeeks={d.cycleOnWeeks} offWeeks={d.cycleOffWeeks} error={showValidation&&repeatingIncomplete?'Enter positive active and break weeks.':undefined} onMode={mode=>{setTimingChoice(mode);if(mode==='ongoing')patch({indefinite:true,breakWeeks:'0',cycleOnWeeks:undefined,cycleOffWeeks:undefined,stages:d.stages.map((stage,i)=>i===d.stages.length-1?{...stage,duration:{value:'104',unit:'weeks'},weeks:'104'}:stage)});else if(mode==='repeat')patch({indefinite:true,breakWeeks:'0',cycleOnWeeks:d.cycleOnWeeks||'',cycleOffWeeks:d.cycleOffWeeks||'',stages:d.stages.map((stage,i)=>i===d.stages.length-1?{...stage,duration:{value:'104',unit:'weeks'},weeks:'104'}:stage)});else {const legacyLength=singleStage&&Number(d.breakWeeks)>0?d.breakWeeks:'';patch({indefinite:false,breakWeeks:'0',cycleOnWeeks:undefined,cycleOffWeeks:undefined,stages:d.stages.map((stage,i)=>i===d.stages.length-1&&stageDays(stage)>=728?{...stage,duration:{value:legacyLength,unit:'weeks'},weeks:legacyLength}:stage)});}}} onChange={value=>patch({...value,indefinite:true,breakWeeks:'0'})}>{singleStage&&<View style={{marginTop:14}}><Text style={u.heading}>How long should this plan run?</Text><Field label={(d.stages[0]?.duration?.unit??'weeks')==='days'?'Number of days':'Number of weeks'} value={d.stages[0]?.duration?.value??d.stages[0]?.weeks??''} numeric placeholder={(d.stages[0]?.duration?.unit??'weeks')==='days'?'Example: 30':'Example: 8'} onChange={value=>patch({indefinite:false,breakWeeks:'0',cycleOnWeeks:undefined,cycleOffWeeks:undefined,stages:[{...d.stages[0],duration:{value,unit:d.stages[0]?.duration?.unit==='days'?'days':'weeks'},weeks:d.stages[0]?.duration?.unit==='days'?'':value}]})}/><View style={u.row}>{(['weeks','days'] as const).map(unit=><Pressable key={unit} accessibilityRole="radio" accessibilityState={{checked:(d.stages[0]?.duration?.unit??'weeks')===unit}} onPress={()=>patch({stages:[{...d.stages[0],duration:{value:d.stages[0]?.duration?.value??d.stages[0]?.weeks??'',unit},weeks:unit==='weeks'?(d.stages[0]?.duration?.value??d.stages[0]?.weeks??''):''}]})} style={[u.pill,(d.stages[0]?.duration?.unit??'weeks')===unit&&u.selected]}><Text style={u.body}>{unit==='weeks'?'Weeks':'Days'}</Text></Pressable>)}</View></View>}{!singleStage&&<Text style={[u.small,{marginTop:12}]}>The stage cards above determine how long this plan runs.</Text>}</CyclePattern></Card><Text style={u.small}>Timing changes future events only. Saved history remains unchanged.</Text>
 <SectionTitle name="Reminders"/>
 <Card><Text style={u.heading}>{d.reminderEnabled?'Reminders on':'Reminders off'}</Text><Text style={u.body}>The first alert follows this peptide's schedule. If the event is still unlogged one hour later, PepPlan prepares a more urgent follow-up.</Text><Text style={u.small}>Taken or skipped events stop future alerts when notification schedules next reconcile. Exact delivery timing is controlled by Android.</Text></Card>
 <Pressable accessibilityRole="checkbox" accessibilityLabel="Enable reminders for this peptide" accessibilityState={{checked:d.reminderEnabled}} onPress={()=>patch({reminderEnabled:!d.reminderEnabled})} style={u.evidence}><Text style={u.body}>{d.reminderEnabled?'✓':'○'} Enable reminders for {plan.compoundName}</Text></Pressable>
 {d.reminderEnabled&&<><Text style={[u.heading,{marginTop:16}]}>First alert</Text><View style={u.row}>{([0,15,30] as const).map(minutes=><Pressable key={minutes} accessibilityRole="radio" accessibilityLabel={minutes?'Remind '+minutes+' minutes before':'Remind at scheduled time'} accessibilityState={{checked:d.reminderOffsetMinutes===minutes}} onPress={()=>patch({reminderOffsetMinutes:minutes})} style={[u.pill,d.reminderOffsetMinutes===minutes&&u.selected]}><Text style={u.body}>{minutes?minutes+' min before':'At time'}</Text></Pressable>)}</View><Text style={u.small}>You can choose 15, 30 or 60 minutes when using Remind Later from Today.</Text></>}
 <SectionTitle name="Pause / Archive"/><Text style={u.body}>Pausing hides pending events from the daily schedule. Calendar dates continue; resuming restores pending events, including any needing a log. History and supply remain intact.</Text><Button label={d.pausedAt?'Resume peptide':'Pause peptide'} onPress={()=>patch({pausedAt:d.pausedAt?null:new Date().toISOString()})}/><Text style={u.small}>{d.pausedAt?'Paused after saving':'Active after saving'}</Text>{confirm?<><Text style={u.small}>Archive this peptide? Saved history stays available. Unsaved edits will be discarded.</Text><Button label="Confirm archive peptide" onPress={()=>run(onArchive)}/><Button label="Keep peptide" secondary onPress={()=>setConfirm(false)}/></>:<Button label="Archive peptide" secondary onPress={()=>setConfirm(true)}/>}
 {!!error&&<Text accessibilityLiveRegion="polite" style={u.error}>{error}</Text>}<Button label="Save changes" disabled={busy} onPress={()=>{const errors=validateDraft({...d,reviewed:true});if(errors.length||inventoryIssue||repeatingIncomplete){setShowValidation(true);setError('');return;}run(onSave);}}/><Button label="Cancel editing" secondary disabled={busy} onPress={()=>run(onCancel)}/>
 {sheet!==undefined&&<ScheduleSheet initial={sheet===null?d.defaultSchedule:d.stages[sheet].override||d.defaultSchedule} stageIndex={sheet} onClose={()=>setSheet(undefined)} onSave={(schedule,all)=>{if(all)patch({defaultSchedule:schedule,stages:d.stages.map(s=>({...s,override:null}))});else if(sheet===null)patch({defaultSchedule:schedule});else patch({stages:d.stages.map((s,i)=>i===sheet?{...s,override:schedule}:s)});setSheet(undefined);}}/>}
 </ScrollView>;
}
