import React,{useMemo,useState}from'react';
import{ScrollView,View,Text,Pressable,StyleSheet,TextInput}from'react-native';
import type{Draft,SavedPlan}from'./engine';
import{activate,addDays,localDate,prettyDate,prettyTime,eventStatus,stageAmount}from'./engine';
import{Card,u,C}from'./ui';
import{addedLibraryV04}from'./content-v04';
import{aggregateEvents,calendarDensity,eventsForDay,inventorySummary,planDashboard,stressPlanCounts,todayEvents}from'./multiplan-v04';

const ORIGINAL=[
 {id:'retatrutide',name:'Retatrutide',kind:'Investigational metabolic peptide',accent:'#2FA9FF',summary:'Triple GIP / GLP-1 / glucagon receptor agonist research.',plainEnglish:'A three-pathway metabolic research compound with human clinical trial data.',evidence:'Published human clinical research',studiedFor:'Obesity and cardiometabolic outcomes.',mechanism:'Acts at GIP, GLP-1 and glucagon receptors.',deeper:['Phase 2 and ongoing Phase 3 research should remain study-specific.','Reference plans and common vial setup must remain visibly separate in provenance.']},
 {id:'tirzepatide',name:'Tirzepatide',kind:'Approved metabolic medicine',accent:'#7C5CFF',summary:'Dual GIP / GLP-1 receptor agonist.',plainEnglish:'Two gut-hormone pathways with approved product-specific schedules.',evidence:'Approved medicine · human clinical evidence',studiedFor:'Type 2 diabetes and chronic weight management depending on product.',mechanism:'Activates GIP and GLP-1 receptors.',deeper:['Product and jurisdiction matter.','Approved labeling must stay separate from customized user plans.']},
 {id:'semaglutide',name:'Semaglutide',kind:'Approved metabolic medicine',accent:'#3A8DFF',summary:'GLP-1 receptor agonist used in multiple approved products.',plainEnglish:'One metabolic hormone pathway, with product-specific indications and schedules.',evidence:'Approved medicine · human clinical evidence',studiedFor:'Weight management, type 2 diabetes and cardiovascular-risk reduction in specific products.',mechanism:'Activates GLP-1 receptors.',deeper:['Wegovy, Ozempic and Rybelsus should not share one universal schedule.','Route and product context stay attached to each reference.']},
 {id:'glow-70',name:'Glow 70 mg',kind:'Defined research blend',accent:'#9D5CFF',summary:'Fixed 50/10/10 blend of GHK-Cu, BPC-157 and TB-500.',plainEnglish:'A blend needs component arithmetic and evidence labels, not a claim that the mixture itself has a validated clinical protocol.',evidence:'Blend · component evidence only',studiedFor:'Component-level research contexts.',mechanism:'Component mechanisms differ; the blend is not one established clinical entity.',deeper:['The fixed 5:1:1 ratio supports deterministic component math.','Blend reference conventions remain clearly labeled as non-clinically-validated.']},
 {id:'ghk-cu',name:'GHK-Cu',kind:'Copper peptide',accent:'#22B7C8',summary:'Copper-binding tripeptide with topical/cosmetic and preclinical research.',plainEnglish:'A small copper-carrying peptide studied around skin and tissue-remodeling biology.',evidence:'Human topical/cosmetic + preclinical evidence',studiedFor:'Skin, extracellular matrix and tissue-repair biology.',mechanism:'Research includes fibroblast, collagen/elastin and matrix-remodeling pathways.',deeper:['Route matters: topical evidence should not be silently converted into injectable evidence.','Common research setup is separately labeled from human evidence.']},
 {id:'kpv',name:'KPV',kind:'Tripeptide',accent:'#6F6BFF',summary:'Lys-Pro-Val fragment associated with anti-inflammatory signaling research.',plainEnglish:'A very small peptide with mainly mechanistic and preclinical evidence.',evidence:'Preclinical / mechanistic evidence',studiedFor:'Inflammatory signaling and intestinal models.',mechanism:'Research includes PepT1 transport and NF-kB/MAPK signaling.',deeper:['No robust established human reference schedule is encoded.','Common Research Practice, when shown, is explicitly separated from human clinical evidence.']}
];
const LIBRARY=[...ORIGINAL,...addedLibraryV04];
const PERSONAL=['retatrutide','ghk-cu','5-amino-1mq','ss-31','nad-plus','mots-c'];

function samplePlan(id:string,index:number):SavedPlan{
 const entry=LIBRARY.find(x=>x.id===id)!;const start=addDays(localDate(),-14);
 const amount=id==='kpv'?'.2':id==='ghk-cu'?'1':id==='retatrutide'?'2':id==='nad-plus'?'1':'1';
 const unit=id==='kpv'?'mcg':'mg';
 const draft:Draft={id:'stress-'+id,compoundId:id,compoundName:entry.name,origin:null,customized:true,stages:[{id:'stage-1',amountMg:amount,amountUnit:unit as 'mg'|'mcg',weeks:'8',override:null}],defaultSchedule:{kind:'daily',days:[],times:[String(8+(index%6)).padStart(2,'0')+':00'],interval:null},breakWeeks:'0',startDate:start,vialMg:id==='ghk-cu'?'50':id==='glow-70'?'70':'10',waterMl:id==='ghk-cu'||id==='glow-70'?'3':'2',initialVials:String((index%3+1)*5),reviewed:true,reminderEnabled:true,reminderOffsetMinutes:0};
 return activate(draft,new Date());
}

export default function MultiPlanLab(){
 const [tab,setTab]=useState<'Plans'|'Today'|'Calendar'|'Inventory'|'School'>('Plans');
 const [count,setCount]=useState<1|3|6|10>(6),[selectedDay,setSelectedDay]=useState(localDate()),[month,setMonth]=useState(localDate().slice(0,7)+'-01'),[schoolId,setSchoolId]=useState('retatrutide'),[kitMode,setKitMode]=useState(false),[kitCount,setKitCount]=useState('1'),[vialsPerKit,setVialsPerKit]=useState('10');
 const order=useMemo(()=>[...PERSONAL,...LIBRARY.map(x=>x.id).filter(id=>!PERSONAL.includes(id))].slice(0,count),[count]);
 const plans=useMemo(()=>order.map((id,i)=>samplePlan(id,i)),[order.join('|')]);
 const dashboard=planDashboard(plans),today=todayEvents(plans),selectedEvents=eventsForDay(plans,selectedDay),monthDate=new Date(Number(month.slice(0,4)),Number(month.slice(5,7))-1,1),daysInMonth=new Date(monthDate.getFullYear(),monthDate.getMonth()+1,0).getDate(),leading=(monthDate.getDay()+6)%7;
 const school=LIBRARY.find(x=>x.id===schoolId)!;
 const moveMonth=(n:number)=>{const d=new Date(monthDate);d.setMonth(d.getMonth()+n);setMonth(`${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}-01`)};
 return <ScrollView contentContainerStyle={s.scroll}>
  <View style={s.hero}><Text style={s.kicker}>PROTOTYPE 0.4 · MULTI-PLAN REVIEW</Text><Text style={s.title}>One clear view, even with many plans.</Text><Text style={s.sub}>UX stress surface · sample data only. Core 0.3.3 remains intact underneath.</Text></View>
  <Text style={s.label}>STRESS TEST</Text><View style={s.row}>{stressPlanCounts.map(n=><Pressable key={n} accessibilityRole="radio" accessibilityState={{checked:count===n}} onPress={()=>setCount(n)} style={[s.pill,count===n&&s.selected]}><Text style={s.pillText}>{n} plan{n===1?'':'s'}</Text></Pressable>)}</View>
  <View style={s.tabs}>{(['Plans','Today','Calendar','Inventory','School'] as const).map(name=><Pressable key={name} accessibilityRole="tab" accessibilityState={{selected:tab===name}} onPress={()=>setTab(name)} style={[s.tab,tab===name&&s.tabOn]}><Text style={[s.tabText,tab===name&&s.tabTextOn]}>{name}</Text></Pressable>)}</View>

  {tab==='Plans'&&<><Text style={s.section}>My Plans · {plans.length} active</Text><Text style={s.helper}>Each plan keeps its own stages, schedule, vial setup, inventory and history.</Text>{dashboard.map(({plan,progress,next})=><Card key={plan.id}><View style={s.between}><View style={{flex:1}}><Text style={u.heading}>{plan.compoundName}</Text><Text style={u.body}>{progress.started?`Week ${progress.week} of ${progress.totalWeeks}`:`Starts ${prettyDate(plan.startDate)}`}</Text></View><View style={s.status}><Text style={s.statusText}>ACTIVE</Text></View></View><Text style={u.small}>{next?`Next · ${prettyDate(next.localDate)} · ${prettyTime(next.scheduledAt)}`:'No future event'}</Text><Text style={u.small}>{plan.events.filter(e=>e.status==='completed').length} completed · {plan.events.length} scheduled in model</Text></Card>)}</>}

  {tab==='Today'&&<><Text style={s.section}>Today · {today.length} scheduled</Text><Text style={s.helper}>Events from every active plan are merged by time. Nothing is hidden behind a single-compound tracker.</Text>{today.length?today.map(({plan,event})=><Card key={event.id}><View style={s.between}><View><Text style={u.heading}>{prettyTime(event.scheduledAt)} · {plan.compoundName}</Text><Text style={u.body}>Stage {event.stageIndex+1} · {stageAmount({amountMg:String(event.amountMg),amountUnit:event.amountUnit})}</Text></View><Text style={[s.eventStatus,{color:statusColor[eventStatus(event)]}]}>{eventStatus(event)}</Text></View><Text style={u.small}>Draw · {Number(event.calculation.units.toFixed(3))} U · {Number(event.calculation.volume.toFixed(4))} mL</Text></Card>):<Card><Text style={u.body}>No events scheduled today in this stress set.</Text></Card>}</>}

  {tab==='Calendar'&&<><View style={s.between}><Pressable onPress={()=>moveMonth(-1)}><Text style={s.arrow}>‹</Text></Pressable><Text style={s.section}>{monthDate.toLocaleDateString(undefined,{month:'long',year:'numeric'})}</Text><Pressable onPress={()=>moveMonth(1)}><Text style={s.arrow}>›</Text></Pressable></View><Text style={s.helper}>Calendar shows density first. Tap a day to see the actual list instead of squeezing ten dots into one square.</Text><View style={s.calendar}>{['M','T','W','T','F','S','S'].map((d,i)=><Text key={'w'+i} style={s.weekday}>{d}</Text>)}{Array.from({length:leading},(_,i)=><View key={'b'+i} style={s.cell}/>)}{Array.from({length:daysInMonth},(_,i)=>{const day=month.slice(0,8)+String(i+1).padStart(2,'0'),density=calendarDensity(plans,day);return <Pressable key={day} accessibilityLabel={'Calendar '+day} onPress={()=>setSelectedDay(day)} style={[s.cell,selectedDay===day&&s.cellOn]}><Text style={s.day}>{i+1}</Text>{density.count>0&&<><Text style={s.count}>{density.count}</Text><View style={s.dots}>{density.statuses.slice(0,3).map(st=><View key={st} style={[s.dot,{backgroundColor:statusColor[st]}]}/>)}</View></>}</Pressable>})}</View><Text style={s.section}>{prettyDate(selectedDay)} · {selectedEvents.length} scheduled</Text>{selectedEvents.slice(0,8).map(({plan,event})=><Card key={event.id}><Text style={u.heading}>{prettyTime(event.scheduledAt)} · {plan.compoundName}</Text><Text style={u.body}>{stageAmount({amountMg:String(event.amountMg),amountUnit:event.amountUnit})} · {Number(event.calculation.units.toFixed(3))} U</Text></Card>)}{selectedEvents.length>8&&<Text style={s.helper}>+ {selectedEvents.length-8} more events</Text>}</>}

  {tab==='Inventory'&&<><Text style={s.section}>Inventory · plain English</Text><Card><Text style={u.heading}>What does “vials on hand” mean?</Text><Text style={u.body}>Enter individual vials, not kits.</Text><Text style={u.small}>Example: 1 kit containing 10 vials = 10 individual vials.</Text><Pressable accessibilityRole="checkbox" accessibilityState={{checked:kitMode}} onPress={()=>setKitMode(!kitMode)} style={[s.mode,kitMode&&s.selected]}><Text style={u.body}>{kitMode?'✓':'○'} I buy by kit</Text></Pressable>{kitMode&&<View style={s.formRow}><View style={{flex:1}}><Text style={s.label}>KITS</Text><TextInput value={kitCount} onChangeText={setKitCount} keyboardType="numeric" style={s.input}/></View><View style={{flex:1}}><Text style={s.label}>VIALS / KIT</Text><TextInput value={vialsPerKit} onChangeText={setVialsPerKit} keyboardType="numeric" style={s.input}/></View></View>}{kitMode&&<Text style={u.heading}>Total · {(Number(kitCount)||0)*(Number(vialsPerKit)||0)} individual vials</Text>}</Card>{plans.map(plan=>{const x=inventorySummary(plan);return <Card key={plan.id}><Text style={u.heading}>{plan.compoundName}</Text><Text style={u.body}>{x.individualVialsLabel}</Text><Text style={u.small}>{x.coverage.enough===null?'Coverage available after inventory is entered.':x.coverage.enough?'Enough for the modelled remaining plan':'May not cover the remaining modelled plan'}</Text></Card>})}</>}

  {tab==='School'&&<><Text style={s.section}>Pep School · 10-compound library</Text><Text style={s.helper}>101 stays short. Learn More carries the research depth.</Text><View style={s.library}>{LIBRARY.map(entry=><Pressable key={entry.id} onPress={()=>setSchoolId(entry.id)} style={[s.libraryItem,schoolId===entry.id&&{borderColor:entry.accent,borderWidth:2}]}><Text style={s.libraryName}>{entry.name}</Text><Text style={s.libraryKind}>{entry.kind}</Text></Pressable>)}</View><Card><Text style={s.kicker}>COMPOUND 101</Text><Text style={s.titleSmall}>{school.name}</Text><Text style={u.body}>{school.summary}</Text><Text style={s.label}>IN PLAIN ENGLISH</Text><Text style={u.body}>{school.plainEnglish}</Text><Text style={s.label}>EVIDENCE</Text><Text style={u.body}>{school.evidence}</Text><Text style={s.label}>STUDIED / KNOWN FOR</Text><Text style={u.body}>{school.studiedFor}</Text></Card><Card><Text style={s.kicker}>LEARN MORE</Text><Text style={u.heading}>How it works — deeper dive</Text><Text style={u.body}>{school.mechanism}</Text>{('deeper'in school?school.deeper:[]).map((item:any,i:number)=><View key={i} style={{marginTop:14}}><Text style={u.heading}>{typeof item==='string'?['Research overview','Human evidence','Reference context'][i]||'Research context':item.title}</Text><Text style={u.body}>{typeof item==='string'?item:item.body}</Text></View>)}<Text style={u.small}>Sources and study-level citations remain a dedicated layer; 0.4 does not turn unsupported evidence into a pre-filled human schedule.</Text></Card></>}
 </ScrollView>
}

const statusColor:any={Completed:'#178066',Scheduled:'#076eac',Missed:'#bd4352',Future:'#7a65b2',Skipped:'#737b87'};
const s=StyleSheet.create({scroll:{padding:18,paddingBottom:80,backgroundColor:'#F8FBFF'},hero:{padding:20,borderRadius:28,backgroundColor:'#EEF9FF',borderWidth:1,borderColor:'#DCE8F5',marginBottom:18},kicker:{fontSize:11,fontWeight:'800',letterSpacing:1.5,color:'#169ED0',marginTop:8},title:{fontSize:30,lineHeight:36,fontWeight:'800',color:'#12204A',marginTop:10},titleSmall:{fontSize:26,fontWeight:'800',color:'#12204A',marginTop:8,marginBottom:10},sub:{fontSize:13,lineHeight:19,color:'#667597',marginTop:8},label:{fontSize:11,fontWeight:'800',letterSpacing:1.2,color:'#667597',marginTop:16,marginBottom:6},row:{flexDirection:'row',gap:8,flexWrap:'wrap'},pill:{paddingVertical:10,paddingHorizontal:14,borderRadius:14,backgroundColor:'#EEF2F8',borderWidth:1,borderColor:'#DCE8F5'},selected:{backgroundColor:'#DDF6FF',borderColor:'#27B9EE'},pillText:{fontWeight:'800',color:'#12204A'},tabs:{flexDirection:'row',gap:5,marginVertical:18,backgroundColor:'#EEF2F8',padding:5,borderRadius:16},tab:{flex:1,paddingVertical:10,borderRadius:12,alignItems:'center'},tabOn:{backgroundColor:'#fff'},tabText:{fontSize:12,fontWeight:'700',color:'#667597'},tabTextOn:{color:'#12204A'},section:{fontSize:22,fontWeight:'800',color:'#12204A',marginTop:10,marginBottom:4},helper:{fontSize:12,lineHeight:18,color:'#667597',marginBottom:10},between:{flexDirection:'row',justifyContent:'space-between',alignItems:'center',gap:10},status:{backgroundColor:'#E8FAF3',paddingHorizontal:9,paddingVertical:5,borderRadius:10},statusText:{fontSize:10,fontWeight:'800',color:'#178066'},eventStatus:{fontSize:11,fontWeight:'800'},arrow:{fontSize:32,color:'#169ED0',padding:8},calendar:{flexDirection:'row',flexWrap:'wrap',marginTop:10},weekday:{width:'14.2857%',textAlign:'center',fontWeight:'700',color:'#667896',padding:5},cell:{width:'14.2857%',height:62,alignItems:'center',justifyContent:'center',borderRadius:11},cellOn:{backgroundColor:'#DFF6FF',borderWidth:1,borderColor:'#27B9EE'},day:{fontSize:15,fontWeight:'700',color:'#18305C'},count:{fontSize:11,fontWeight:'800',color:'#169ED0'},dots:{flexDirection:'row',gap:2,marginTop:2},dot:{width:5,height:5,borderRadius:3},mode:{marginTop:14,padding:12,borderRadius:14,borderWidth:1,borderColor:'#DCE8F5'},formRow:{flexDirection:'row',gap:12,marginTop:8},input:{borderWidth:1,borderColor:'#DCE8F5',backgroundColor:'#fff',borderRadius:12,padding:12,fontSize:16,color:'#12204A'},library:{flexDirection:'row',flexWrap:'wrap',gap:8},libraryItem:{width:'48%',padding:12,borderRadius:16,backgroundColor:'#fff',borderWidth:1,borderColor:'#DCE8F5'},libraryName:{fontSize:15,fontWeight:'800',color:'#12204A'},libraryKind:{fontSize:10,lineHeight:14,color:'#667597',marginTop:4}});
