import React,{useState} from 'react';
import {Text,Pressable,View,StyleSheet,TextInput} from 'react-native';
import {Card,u} from './ui';
import {reconstitutionBasics} from './school-basics';
export default function QuickStart(){
 const [open,setOpen]=useState(false);
 return <Card><Text style={u.heading}>Quick Start</Text><Text style={u.body}>New to vials and calculations? Start with the words, then the numbers.</Text>
 <Text style={u.small}>Freeze-dried powder + the correct liquid → a solution with a known concentration.</Text>
 <Pressable accessibilityRole="button" accessibilityLabel="Quick Start — Learn More" accessibilityState={{expanded:open}} onPress={()=>setOpen(!open)}><Text style={u.link}>{open?'Show less':'Learn More'} {open?'−':'+'}</Text></Pressable>
 {open&&<View>{reconstitutionBasics.details.map((text,i)=><View key={text} style={{marginTop:12}}><Text style={u.heading}>{['What is in the vial?','What is reconstitution?','What is bacteriostatic water?','Use the correct diluent','The math at a glance','Why volume changes the draw'][i]}</Text><Text style={u.body}>{text}</Text></View>)}<Text style={[u.heading,{marginTop:16}]}>Why values may be pre-filled</Text><Text style={u.body}>A reference may supply plan values. Some references also have a separately labelled Common Research Setup for the calculator. These are different sources: check the labels and confirm your vial and diluent. Editable setup defaults are not a clinical recommendation.</Text><Text style={u.small}>Reference labels: {reconstitutionBasics.sourceLabels.join(' · ')}</Text></View>}
 </Card>;
}

export function LearningPaths(){
 const paths=[
  {id:'foundations',title:'PepPlan Foundations',tag:'START HERE',summary:'Learn the vocabulary, evidence labels and calculation concepts used throughout PepPlan.',lessons:['What peptides are — and are not','Understanding evidence levels','Route and formulation matter','mg, mcg, mL and syringe units','How to read a Pep School profile']},
  {id:'planning',title:'Planning Fundamentals',tag:'GUIDE & TRACK',summary:'Understand how a reference becomes an editable model and a daily timeline.',lessons:['Individual vials versus kits','Stages, schedules and planned breaks','Concentration and draw calculations','Using Today, Calendar and History','Why logged events preserve historical truth']},
  {id:'research',title:'Research Literacy',tag:'DEEPER LEARNING',summary:'Build confidence reading studies without treating every source as equally authoritative.',lessons:['Human versus preclinical evidence','Population, route and formulation','Reading key findings and limitations','Recognizing unsupported claims','Conflicting and negative evidence']},
 ] as const;
 const [open,setOpen]=useState<string|null>(null);
 return <View style={s.paths}><View style={s.pathHeader}><View><Text style={s.eyebrow}>LEARN PEPPLAN</Text><Text style={s.pathTitle}>Short learning paths</Text></View><Text style={s.courseCount}>3 courses</Text></View><Text style={u.small}>Practical lessons that make School, Guide and Today easier to use.</Text>{paths.map(path=>{const expanded=open===path.id;return <View key={path.id} style={s.course}><Pressable accessibilityRole="button" accessibilityLabel={path.title} accessibilityState={{expanded}} onPress={()=>setOpen(expanded?null:path.id)} style={s.courseTop}><View style={{flex:1}}><Text style={s.tag}>{path.tag}</Text><Text style={s.courseTitle}>{path.title}</Text><Text style={s.courseSummary}>{path.summary}</Text><View style={s.progress}><View style={s.progressFill}/></View><Text style={s.progressText}>Preview · {path.lessons.length} lessons</Text></View><Text style={s.chevron}>{expanded?'−':'+'}</Text></Pressable>{expanded&&<View style={s.lessons}>{path.lessons.map((lesson,index)=><View key={lesson} style={s.lesson}><View style={s.lessonNumber}><Text style={s.lessonNumberText}>{index+1}</Text></View><Text style={s.lessonText}>{lesson}</Text></View>)}<Text style={s.coming}>Course progress will be saved when the learning player is connected.</Text></View>}</View>})}</View>;
}
const s=StyleSheet.create({basics:{marginTop:20},basicSearch:{flexDirection:'row',alignItems:'center',height:48,borderWidth:1,borderColor:'#d7e4f3',borderRadius:16,backgroundColor:'#fff',paddingHorizontal:12,marginTop:12,marginBottom:8},searchGlyph:{fontSize:20,color:'#126e95',marginRight:8},basicInput:{flex:1,fontSize:14,color:'#0e1c4a'},question:{marginTop:8,borderWidth:1,borderColor:'#dde8f6',borderRadius:16,backgroundColor:'#fff',overflow:'hidden'},questionTop:{minHeight:52,flexDirection:'row',alignItems:'center',gap:10,paddingHorizontal:14,paddingVertical:11},questionText:{flex:1,fontSize:13,lineHeight:18,fontWeight:'800',color:'#0e1c4a'},questionChevron:{fontSize:21,color:'#27a8d8'},answer:{fontSize:12,lineHeight:18,color:'#526482',paddingHorizontal:14,paddingBottom:14},noResults:{fontSize:12,color:'#667597',paddingVertical:18,textAlign:'center'},paths:{marginTop:16},pathHeader:{flexDirection:'row',justifyContent:'space-between',alignItems:'flex-end'},eyebrow:{fontSize:10,fontWeight:'800',letterSpacing:1.3,color:'#7557f6'},pathTitle:{fontSize:21,fontWeight:'800',color:'#0e1c4a',marginTop:4},courseCount:{fontSize:11,fontWeight:'700',color:'#667597'},course:{marginTop:10,borderWidth:1,borderColor:'#dde8f6',borderRadius:18,backgroundColor:'#fff',overflow:'hidden'},courseTop:{flexDirection:'row',gap:10,padding:14},tag:{fontSize:9,fontWeight:'800',letterSpacing:1,color:'#168bb8'},courseTitle:{fontSize:16,fontWeight:'800',color:'#0e1c4a',marginTop:4},courseSummary:{fontSize:12,lineHeight:17,color:'#667597',marginTop:4},progress:{height:5,borderRadius:3,backgroundColor:'#edf2f8',marginTop:10,overflow:'hidden'},progressFill:{width:'8%',height:'100%',backgroundColor:'#27b9ee'},progressText:{fontSize:10,color:'#667597',marginTop:5},chevron:{fontSize:23,color:'#27a8d8'},lessons:{paddingHorizontal:14,paddingBottom:14},lesson:{flexDirection:'row',alignItems:'center',gap:9,paddingVertical:8,borderTopWidth:StyleSheet.hairlineWidth,borderTopColor:'#e2eaf4'},lessonNumber:{width:24,height:24,borderRadius:12,alignItems:'center',justifyContent:'center',backgroundColor:'#eaf9ff'},lessonNumberText:{fontSize:10,fontWeight:'800',color:'#126e95'},lessonText:{flex:1,fontSize:12,fontWeight:'700',color:'#34456c'},coming:{fontSize:10,lineHeight:15,color:'#7557f6',marginTop:8}});

export function SchoolBasics(){
 const items=[
  {q:'Do I need an account to use PepPlan?',a:'No. PepPlan Starter is designed to remain useful locally without an account. A future account will add backup, device transfer and Pro access.'},
  {q:'What do the evidence labels mean?',a:'They keep approved or labelled references, published human research, human pilot research, preclinical research and common research practice visibly separate.'},
  {q:'Why does route and formulation matter?',a:'Evidence from an implant, topical product, intravenous study or intranasal study does not automatically establish an equivalent research-vial or subcutaneous model.'},
  {q:'Why does a profile sometimes have no Guide model?',a:'PepPlan only transfers values when a reviewed reference supports them. A useful profile can still explain the evidence while requiring a custom plan.'},
  {q:'What is the difference between mg and mcg?',a:'Both measure mass. One milligram equals 1,000 micrograms. PepPlan keeps the selected unit visible and performs calculations from the stored mass.'},
  {q:'What do syringe units mean?',a:'On a U-100 insulin syringe, 100 units represents 1.0 mL. The required draw still depends on the saved vial strength and diluent volume.'},
  {q:'Should inventory be entered as kits or vials?',a:'Enter individual vials. A kit containing 10 vials is entered as 10 individual vials so projections and logged consumption remain clear.'},
  {q:'Do scheduled events consume inventory?',a:'No. Inventory consumption follows events logged Taken. Scheduled, snoozed and skipped events do not consume supply.'},
  {q:'What happens when I change an active peptide?',a:'Future-effective edits update upcoming events. Completed and skipped events retain their original amounts, calculations and timestamps as historical truth.'},
  {q:'How do PepPlan reminders work?',a:'Enabled plans prepare local reminders for scheduled events. An unresolved event can receive a follow-up and remains visible in Today until marked Taken, Skip or Remind Later.'},
  {q:'Are Common Research Practice references clinical recommendations?',a:'No. They are separately labelled research-practice starting references and must not be presented as approved or established clinical schedules.'},
  {q:'Where do profile facts come from?',a:'Each profile keeps evidence classes and source links visible. Major limitations should remain attached to the relevant route, formulation, population and study context.'},
 ] as const;
 const [query,setQuery]=useState(''),[open,setOpen]=useState<string|null>(null);
 const words=query.trim().toLowerCase(),results=items.filter(item=>!words||(item.q+' '+item.a).toLowerCase().includes(words));
 return <View style={s.basics}><Text style={s.eyebrow}>PEP SCHOOL BASICS</Text><Text style={s.pathTitle}>Questions, clearly answered</Text><Text style={u.small}>Search app concepts and research-literacy fundamentals.</Text><View style={s.basicSearch}><Text style={s.searchGlyph}>⌕</Text><TextInput accessibilityLabel="Search Pep School Basics" value={query} onChangeText={setQuery} placeholder="Search questions" placeholderTextColor="#91a0bc" style={s.basicInput}/></View>{results.map(item=>{const expanded=open===item.q;return <View key={item.q} style={s.question}><Pressable accessibilityRole="button" accessibilityLabel={item.q} accessibilityState={{expanded}} onPress={()=>setOpen(expanded?null:item.q)} style={s.questionTop}><Text style={s.questionText}>{item.q}</Text><Text style={s.questionChevron}>{expanded?'−':'+'}</Text></Pressable>{expanded&&<Text style={s.answer}>{item.a}</Text>}</View>})}{!results.length&&<Text style={s.noResults}>No matching question. Try fewer words.</Text>}</View>;
}
