import React,{useState}from'react';
import{Modal,View,Text,ScrollView,Pressable,StyleSheet}from'react-native';
import{blankSchedule,scheduleError}from'./engine';
import type{Schedule}from'./engine';
import{Button,Field,ProfessorHelp,u,C}from'./ui';
import TimeChoice from './TimeChoice';
export default function ScheduleSheet({initial,stageIndex,onClose,onSave}:{initial:Schedule|null;stageIndex:number|null;onClose:()=>void;onSave:(schedule:Schedule,all:boolean)=>void}){
 const [value,setValue]=useState<Schedule>({...JSON.parse(JSON.stringify(initial||blankSchedule())),times:initial?.times.length?initial.times:['09:00']}),[all,setAll]=useState(stageIndex===null),[advanced,setAdvanced]=useState(false),[error,setError]=useState(''),[newTime,setNewTime]=useState<number|null>(null);
 const change=(patch:Partial<Schedule>)=>{setValue(v=>({...v,...patch}));setError('');};
 const weekdayError=/weekday/i.test(error)?error:undefined,intervalError=/interval|days on/i.test(error)?error:undefined,timeError=/time/i.test(error)&&!/times per week|scheduled days/i.test(error)?error:undefined,timesPerWeekError=/scheduled days per week|exactly .* weekdays/i.test(error)?error:undefined;
 const choose=(name:string)=>{
  if(name==='Daily'||name==='Multiple times per day')change({kind:'daily',days:[],interval:null,timesPerWeek:null});
  if(name==='Once weekly')change({kind:'weekly',days:[6],interval:null,timesPerWeek:1});
  if(name==='Twice weekly')change({kind:'weekly',days:[2,6],interval:null,timesPerWeek:2});
  if(name==='Mon / Wed / Fri')change({kind:'weekly',days:[1,3,5],interval:null,timesPerWeek:3});
  if(name==='Every other day')change({kind:'intervalDays',interval:2,timesPerWeek:null});
  if(name==='Specific days')change({kind:'weekly',days:[],timesPerWeek:null});
  if(name==='Every X days')change({kind:'intervalDays',interval:null,timesPerWeek:null});
  if(name==='X times per week')change({kind:'weekly',days:[],timesPerWeek:2,interval:null});
  if(name==='Custom interval')change({kind:'intervalHours',interval:null,times:value.times.slice(0,1),timesPerWeek:null});
  if(name==='5 on / 2 off')change({kind:'cycle',days:[],interval:null,timesPerWeek:null,cycleOn:5,cycleOff:2});
  if(name==='6 on / 1 off')change({kind:'cycle',days:[],interval:null,timesPerWeek:null,cycleOn:6,cycleOff:1});
  if(name==='4 on / 3 off')change({kind:'cycle',days:[],interval:null,timesPerWeek:null,cycleOn:4,cycleOff:3});
  if(name==='Custom cycle')change({kind:'cycle',days:[],interval:null,timesPerWeek:null,cycleOn:null,cycleOff:null});
 };
 return <Modal transparent animationType="slide" onRequestClose={onClose}><View style={s.shade}><View style={s.sheet}><ScrollView keyboardShouldPersistTaps="handled" contentContainerStyle={u.scroll}>
  <View style={u.row}><Text style={[u.title,{marginBottom:0}]}>Schedule</Text><ProfessorHelp title="Schedule choices" body="Quick schedules fill common calendar patterns. Specific days lets you choose weekdays. Advanced schedules add repeating intervals or multiple times. Always review the days and times shown before saving."/></View><Text style={u.body}>{stageIndex===null?'Plan default':`Stage ${stageIndex+1}`} · choose days and times</Text>
  <Text style={[u.label,{marginTop:20}]}>QUICK SCHEDULES</Text><View style={s.options}>{['Daily','Once weekly','Twice weekly','Mon / Wed / Fri','Every other day','Specific days'].map(name=><Pressable accessibilityRole="button" accessibilityLabel={name} key={name} onPress={()=>choose(name)} style={s.option}><Text style={s.optionLabel}>{name}</Text></Pressable>)}</View>
  {value.kind==='weekly'&&<><Text style={[u.label,{marginTop:16}]}>SPECIFIC DAYS</Text><View style={[s.days,weekdayError&&s.errorGroup]}>{[1,2,3,4,5,6,0].map((d,i)=><Pressable key={d} accessibilityRole="checkbox" accessibilityLabel={['Monday','Tuesday','Wednesday','Thursday','Friday','Saturday','Sunday'][i]} accessibilityState={{checked:value.days.includes(d)}} onPress={()=>change({days:value.days.includes(d)?value.days.filter(n=>n!==d):[...value.days,d].sort(),timesPerWeek:null})} style={[s.day,value.days.includes(d)&&u.selected]}><Text style={u.heading}>{['M','T','W','T','F','S','S'][i]}</Text></Pressable>)}</View>{weekdayError&&<Text accessibilityRole="alert" style={u.fieldError}>{weekdayError}</Text>}{!!value.timesPerWeek&&<Text style={u.small}>This quick schedule uses {value.timesPerWeek} {value.timesPerWeek===1?'day':'days'} each week. Selecting different days switches to a custom weekly schedule.</Text>}</>}
  <Pressable accessibilityRole="button" accessibilityLabel="Advanced schedules" onPress={()=>setAdvanced(!advanced)}><Text style={u.link}>Advanced {advanced?'−':'+'}</Text></Pressable>
  {advanced&&<><Text style={[u.label,{marginTop:14}]}>CYCLES</Text><View style={s.options}>{['5 on / 2 off','6 on / 1 off','4 on / 3 off','Custom cycle'].map(name=><Pressable accessibilityRole="button" accessibilityLabel={name} key={name} onPress={()=>choose(name)} style={s.option}><Text style={s.optionLabel}>{name}</Text></Pressable>)}</View><Text style={u.small}>Cycle days repeat from the plan or stage start date.</Text><Text style={[u.label,{marginTop:14}]}>OTHER ADVANCED OPTIONS</Text><View style={s.options}>{['Every X days','X times per week','Multiple times per day','Custom interval'].map(name=><Pressable accessibilityRole="button" accessibilityLabel={name} key={name} onPress={()=>choose(name)} style={s.option}><Text style={s.optionLabel}>{name}</Text></Pressable>)}</View></>}
  {value.kind==='cycle'&&<><Field label="Days on" value={value.cycleOn==null?'':String(value.cycleOn)} onChange={v=>change({cycleOn:v===''?null:Number(v)})} numeric error={intervalError}/><Field label="Days off" value={value.cycleOff==null?'':String(value.cycleOff)} onChange={v=>change({cycleOff:v===''?null:Number(v)})} numeric error={intervalError}/><Text style={u.small}>The cycle repeats continuously from the plan or stage start date.</Text></>}
  {value.kind==='intervalDays'&&<Field label="Every how many days" value={value.interval===null?'':String(value.interval)} onChange={v=>change({interval:v===''?null:Number(v)})} numeric error={intervalError}/>}
  {value.kind==='intervalHours'&&<><Field label="Every how many hours" value={value.interval===null?'':String(value.interval)} onChange={v=>change({interval:v===''?null:Number(v)})} numeric error={intervalError}/><Text style={u.small}>Repeats by elapsed hours from the starting time. Clock changes may shift local times.</Text></>}
  {value.kind==='weekly'&&advanced&&<Field label="Times per week (days)" value={value.timesPerWeek?String(value.timesPerWeek):''} onChange={v=>change({timesPerWeek:v===''?null:Number(v)})} numeric error={timesPerWeekError}/>}
  <View style={timeError&&s.errorGroup}><Text style={[u.label,{marginTop:16}]}>TIME</Text>
  {value.times.map((time,i)=><View key={i} style={{marginBottom:12}}><TimeChoice autoOpen={newTime===i} label={`Time ${i+1}`} value={time} onChange={t=>change({times:value.times.map((old,n)=>n===i?t:old)})}/>{value.times.length>1&&<Pressable accessibilityRole="button" accessibilityLabel={`Remove time ${i+1}`} onPress={()=>change({times:value.times.filter((_,n)=>n!==i)})}><Text style={u.link}>Remove</Text></Pressable>}</View>)}
  {timeError&&<Text accessibilityRole="alert" style={u.fieldError}>{timeError}</Text>}</View>
  {value.kind!=='intervalHours'&&value.times.length<8&&<Button label="+ Add another time" secondary onPress={()=>{setNewTime(value.times.length);const used=new Set(value.times);let hour=9;while(used.has(String(hour).padStart(2,'0')+':00'))hour=(hour+1)%24;change({times:[...value.times,String(hour).padStart(2,'0')+':00']});}}/>}
  <Pressable accessibilityRole="checkbox" accessibilityLabel="Apply this schedule to all stages" accessibilityState={{checked:all}} onPress={()=>stageIndex!==null&&setAll(!all)} style={[u.evidence,all&&{borderLeftColor:C.blue}]}><View style={u.row}><Text style={u.body}>{all?'✓ ':'○ '}Apply this schedule to all stages</Text><ProfessorHelp title="Apply to all stages" body="When selected, this becomes the plan default and replaces existing stage-specific schedules. When unselected, it changes only the stage you opened."/></View>{all&&<Text style={u.small}>Replaces existing stage overrides.</Text>}</Pressable>
  {!all&&<Text style={u.small}>Save for this stage only.</Text>}
  <Button label="Save schedule" onPress={()=>{const err=scheduleError(value);if(err)setError(err);else onSave({...value,times:[...value.times].sort()},all);}}/>
  <Button label="Cancel" secondary onPress={onClose}/>
 </ScrollView></View></View></Modal>;
}
const s=StyleSheet.create({shade:{flex:1,backgroundColor:'#0e1c4a66',justifyContent:'flex-end'},sheet:{backgroundColor:'#fff',borderTopLeftRadius:28,borderTopRightRadius:28,maxHeight:'94%'},days:{flexDirection:'row',justifyContent:'space-between'},options:{gap:8,marginTop:8},option:{alignSelf:'stretch',padding:14,minHeight:50,borderRadius:14,backgroundColor:'#f2f6fc'},optionLabel:{fontSize:16,lineHeight:24,color:C.ink,flexShrink:1},day:{flex:1,marginHorizontal:2,minHeight:44,borderRadius:10,alignItems:'center',justifyContent:'center',backgroundColor:'#f1f5fa',marginTop:8},errorGroup:{borderWidth:2,borderColor:'#bd4352',borderRadius:14,padding:8,backgroundColor:'#fffafb'}});
