import {stageDuration,stageDays,durationLabel,durationPatch} from './duration';
import React,{useEffect,useState}from'react';import{View,Text,Pressable,StyleSheet}from'react-native';import Svg,{Path}from'react-native-svg';
import type{Stage,Schedule}from'./engine';import{stageAmount,displayedAmount,storedAmount,scheduleSummary,addDays,parseDate,prettyDate}from'./engine';import{Button,Field,ProfessorHelp,u,C}from'./ui';
function TrashIcon(){return <Svg width={17} height={17} viewBox="0 0 24 24" fill="none" accessibilityElementsHidden><Path d="M4 7h16M9 7V4h6v3m3 0-1 13H7L6 7m4 4v5m4-5v5" stroke="#a72f46" strokeWidth={1.9} strokeLinecap="round" strokeLinejoin="round"/></Svg>;}
export default function StageCard({stage,index,previousDays,startDate,schedule,last,edit,changeSchedule,useDefault,onRemove,errors=[],startExpanded=false,ongoing=false,onToggleOngoing}:{stage:Stage;index:number;previousDays:number;startDate:string;schedule:Schedule|null;last:boolean;edit?:(patch:Partial<Stage>)=>void;changeSchedule?:()=>void;useDefault?:()=>void;onRemove?:()=>void;errors?:string[];startExpanded?:boolean;ongoing?:boolean;onToggleOngoing?:()=>void}){
 const [editing,setEditing]=useState(startExpanded),[confirmRemove,setConfirmRemove]=useState(false);const amountError=errors.find(message=>message.includes('positive amount')),durationError=errors.find(message=>message.includes('weeks')||message.includes('days'));useEffect(()=>{if(errors.length)setEditing(true);},[errors.join('|')]);const color=[C.blue,C.purple,'#29a5ab'][index%3];const duration=stageDuration(stage),days=stageDays(stage);const start=parseDate(startDate)&&Number.isFinite(previousDays)&&Number.isFinite(days)?addDays(startDate,previousDays):null;
 return <View style={s.row}><View style={s.rail}><View style={[s.dot,{backgroundColor:color}]}><Text style={s.number}>{index+1}</Text></View>{!last&&<View style={[s.line,{backgroundColor:color+'55'}]}/>}</View><View style={[s.card,{borderTopColor:color},errors.length>0&&s.cardError]}>
 <View style={s.cardHeader}><Text style={[u.label,{color,marginBottom:0}]}>STAGE {index+1}</Text>{edit&&onRemove&&<Pressable accessibilityRole="button" accessibilityLabel={'Remove stage '+(index+1)} accessibilityHint="Opens a confirmation before removing this stage" hitSlop={6} onPress={()=>setConfirmRemove(true)} style={({pressed})=>[s.removeControl,pressed&&s.removePressed]}><Text style={s.removeControlText}>Remove</Text><TrashIcon/></Pressable>}</View><Text style={u.small}>{ongoing?'No planned end date':durationLabel(stage)}</Text>
 <Text testID={'stage-amount-'+index} style={s.amount}>{stageAmount(stage)}</Text><Text style={u.body}>{start?prettyDate(start)+' → '+prettyDate(addDays(start,days-1)):'Choose a start date to see stage dates'}</Text>
 {edit&&onRemove&&confirmRemove&&<View style={s.removeConfirm}><Text style={u.heading}>Remove Stage {index+1}?</Text><Text style={u.small}>The remaining stages will be renumbered automatically.</Text><Button label={'Confirm remove Stage '+(index+1)} onPress={()=>{setConfirmRemove(false);onRemove();}}/><Button label="Keep stage" secondary onPress={()=>setConfirmRemove(false)}/></View>}
 {edit&&<Pressable accessibilityRole="button" accessibilityLabel={'Edit stage '+(index+1)} onPress={()=>setEditing(!editing)}><Text style={u.link}>{editing?'Done':'Change amount / duration ›'}</Text></Pressable>}
 {edit&&editing&&<><View style={u.row}><Text style={[u.label,{marginBottom:0}]}>AMOUNT & DURATION</Text><ProfessorHelp title="Stage amount and duration" body="The amount is the value assigned to each scheduled event in this stage. Duration controls how long this stage lasts. Choose mg or mcg carefully—the unit changes how the entered number is interpreted." note="Professor Lynch explains the fields; the app does not choose an amount or duration for you."/></View><Field label={'Stage '+(index+1)+' amount'} value={displayedAmount(stage)} numeric placeholder={'Choose '+(stage.amountUnit||'mg')} onChange={v=>edit({amountMg:storedAmount(v,stage.amountUnit)})} error={amountError?.replace(/^Stage \d+: /,'')}/><View style={u.row}>{(['mg','mcg'] as const).map(unit=><Pressable key={unit} accessibilityRole="radio" accessibilityLabel={'Stage '+(index+1)+' unit '+unit} accessibilityState={{checked:stage.amountUnit===unit}} aria-checked={stage.amountUnit===unit} onPress={()=>edit({amountUnit:unit})} style={[u.pill,stage.amountUnit===unit&&u.selected]}><Text style={u.body}>{unit}</Text></Pressable>)}</View>{ongoing?<><Text style={u.small}>This single-stage plan continues without a displayed end date.</Text>{onToggleOngoing&&<Button label="Set a planned end date" secondary onPress={onToggleOngoing}/>}</>:<><Field label={'Stage '+(index+1)+' duration'} value={duration.value} numeric placeholder="Choose duration" onChange={v=>edit(durationPatch(v,duration.unit))} error={durationError?.replace(/^Stage \d+: /,'' )}/><View style={u.row}>{(['days','weeks'] as const).map(unit=><Pressable key={unit} accessibilityRole="radio" accessibilityLabel={'Stage '+(index+1)+' duration '+unit} accessibilityState={{checked:duration.unit===unit}} aria-checked={duration.unit===unit} onPress={()=>edit(durationPatch(duration.value,unit))} style={[u.pill,duration.unit===unit&&u.selected]}><Text style={u.body}>{unit==='days'?'Days':'Weeks'}</Text></Pressable>)}</View>{index===0&&onToggleOngoing&&<Button label="No planned end date" secondary onPress={onToggleOngoing}/>}</>}</>}
 <View style={s.schedule}><View style={u.row}><Text style={[u.label,{marginBottom:0}]}>SCHEDULE</Text>{edit&&<ProfessorHelp title="Stage schedule" body="A stage normally inherits the plan default schedule. A stage-specific override changes only this stage; choosing “Use plan default” reconnects it to the plan-wide schedule."/>}</View><Text style={u.body}>{scheduleSummary(stage.override||schedule)}</Text>{stage.override&&<Text style={u.small}>Stage-specific schedule</Text>}{changeSchedule&&<Pressable accessibilityRole="button" accessibilityLabel={'Change stage '+(index+1)+' schedule'} onPress={changeSchedule}><Text style={u.link}>Change schedule ›</Text></Pressable>}{stage.override&&useDefault&&<Pressable accessibilityRole="button" accessibilityLabel={'Use plan default for stage '+(index+1)} onPress={useDefault}><Text style={u.link}>Use plan default</Text></Pressable>}</View>
 </View></View>;
}
const s=StyleSheet.create({row:{flexDirection:'row',marginTop:16},rail:{width:30,alignItems:'center'},dot:{width:28,height:28,borderRadius:14,alignItems:'center',justifyContent:'center'},number:{color:'#fff',fontWeight:'800'},line:{width:3,flex:1,marginTop:6,marginBottom:-10},card:{flex:1,minWidth:0,marginLeft:10,borderRadius:22,borderWidth:1,borderColor:C.border,borderTopWidth:3,padding:16,backgroundColor:'#fff'},amount:{fontSize:30,lineHeight:38,fontWeight:'800',color:C.ink,marginTop:8},schedule:{marginTop:14,paddingTop:12,borderTopWidth:1,borderColor:C.border},cardHeader:{minHeight:30,flexDirection:'row',alignItems:'center',justifyContent:'space-between',gap:10},removeControl:{minHeight:36,minWidth:88,paddingHorizontal:10,borderRadius:12,flexDirection:'row',alignItems:'center',justifyContent:'center',gap:6,backgroundColor:'#fff5f6',borderWidth:1,borderColor:'#efc5ce'},removePressed:{opacity:.7},removeControlText:{color:'#a72f46',fontSize:13,fontWeight:'800'},removeConfirm:{marginTop:12,padding:14,borderRadius:16,backgroundColor:'#fff5f6',borderWidth:1,borderColor:'#efc5ce'},cardError:{borderColor:'#bd4352',borderWidth:2}});
