import React,{useState} from 'react';
import {View,Text,Pressable,StyleSheet} from 'react-native';
import type {SavedPlan,Event} from './engine';
import {prettyDate,prettyTime,stageAmount} from './engine';
import MiniSyringe from './MiniSyringe';
import SwipeEvent from './SwipeEvent';
import {u} from './ui';
export default function TodayEventCard({plan,event:e,now,today,active,expanded,onExpand,onAction,onEdit,inventoryAttention=false,onInventory,disabled,children,color}:{plan:SavedPlan;event:Event;now:Date;today:boolean;active:boolean;expanded:boolean;onExpand:()=>void;onAction:(a:'completed'|'skipped'|'later',minutes?:number)=>void;onEdit:()=>void;inventoryAttention?:boolean;onInventory?:()=>void;disabled:boolean;children:React.ReactNode;color:string}){
 const [choosingSnooze,setChoosingSnooze]=useState(false);
 const canLog=active&&e.status==='pending'&&Date.parse(e.scheduledAt)<=now.getTime(),canComplete=active&&e.status==='pending'&&(canLog||today),done=e.status!=='pending',snoozed=e.status==='pending'&&Date.parse(e.snoozedUntil||'')>now.getTime();
 const overdueMinutes=canLog&&!snoozed?Math.floor((now.getTime()-Date.parse(e.scheduledAt))/60000):0,urgent=overdueMinutes>=60;
 const status=done?e.status==='completed'?'Completed':'Skipped':snoozed?'Reminded':urgent?'! Needs attention':canLog?'Due now':today?'Later today':'Scheduled';
 const action=(label:string,name:string,fn:()=>void,primary=false)=><Pressable accessibilityRole="button" accessibilityLabel={name} disabled={disabled} onPress={fn} style={[s.action,primary&&s.primary]}><Text style={[s.actionText,primary&&{color:'#fff'}]}>{label}</Text></Pressable>;
 return <SwipeEvent enabled={today&&active} canLog={canLog} canComplete={canComplete} name={plan.compoundName} onComplete={()=>onAction('completed')} onSkip={()=>onAction('skipped')} onLater={()=>onAction('later')} onEdit={onEdit} disabled={disabled}><View testID={done?'completed-event-card':'pending-event-card'} style={[s.card,done&&s.done,urgent&&s.urgentCard]}>
 <View style={s.row}><View style={[s.dot,{backgroundColor:urgent?'#bd4352':color}]}/><Text style={s.name}>{plan.compoundName}</Text><Text style={[s.status,{color:done?'#178066':canLog?'#ac3545':'#61728f'}]}>{status}</Text></View>
 {today&&active&&inventoryAttention&&onInventory&&<Pressable accessibilityRole="button" accessibilityLabel={'Inventory needs attention for '+plan.compoundName} disabled={disabled} onPress={onInventory} style={s.inventoryAttention}><Text style={s.inventoryAttentionText}>Inventory needs attention ›</Text></Pressable>}
 <Text style={s.meta}>{today?'':prettyDate(e.localDate)+' · '}{prettyTime(e.scheduledAt)} · Stage {e.stageIndex+1}{snoozed?' · reminder '+prettyTime(e.snoozedUntil!):urgent?' · '+overdueMinutes+' min overdue':''}</Text>
 <Text style={s.amount}>{stageAmount({amountMg:String(e.amountMg),amountUnit:e.amountUnit})} · {Number(e.calculation.units.toFixed(3))} units · {Number(e.calculation.volume.toFixed(5))} mL</Text>
 {urgent&&<Text accessibilityLiveRegion="polite" style={s.urgentText}>This event is still waiting. Mark Taken, Skip, or Remind Later.</Text>}
 {!e.calculationUnavailable&&(!done||expanded)&&<View style={s.quickReference}><View style={s.vialIcon}><Text style={s.vialCap}>VIAL SETUP</Text><Text style={s.vialValue}>{plan.vialMg} mg</Text><Text style={s.vialWater}>+ {plan.waterMl} mL</Text></View><View style={s.referenceMain}><View style={s.drawInfo}><Text style={s.drawLabel}>DRAW TO</Text><Text style={s.drawValue}>{Number(e.calculation.units.toFixed(3))} units</Text><Text style={s.drawMeta}>{Number(e.calculation.volume.toFixed(5))} mL · U-100</Text></View><View style={s.doseBlock}><View style={s.doseShine}/><Text style={s.doseLabel}>YOUR DOSE</Text><Text style={s.doseValue}>{stageAmount({amountMg:String(e.amountMg),amountUnit:e.amountUnit})}</Text></View></View></View>}
 {(!done||expanded)&&!e.calculationUnavailable&&<MiniSyringe units={e.calculation.units} capacity={plan.syringeCapacityUnits??null}/>}
 <View style={s.actions}>{canComplete&&action('Taken','Complete '+plan.compoundName+' '+prettyTime(e.scheduledAt),()=>onAction('completed'),true)}{canLog&&<>{action('Skip','Skip '+plan.compoundName+' '+prettyTime(e.scheduledAt),()=>onAction('skipped'))}{action('Later','Choose reminder delay for '+plan.compoundName,()=>setChoosingSnooze(v=>!v))}</>}{active&&action('Edit','Edit event plan '+plan.compoundName+' '+e.id,onEdit)}{action(expanded?'Less':'Details','Event details '+plan.compoundName+' '+e.id,onExpand)}</View>
 {choosingSnooze&&canLog&&<View style={s.snoozeWrap}><Text style={s.snoozeLabel}>Remind me again in</Text><View style={s.snoozeRow}>{([15,30,60] as const).map(minutes=><Pressable key={minutes} accessibilityRole="button" accessibilityLabel={'Remind '+plan.compoundName+' in '+minutes+' minutes'} disabled={disabled} onPress={()=>{setChoosingSnooze(false);onAction('later',minutes);}} style={s.snoozeChoice}><Text style={s.snoozeChoiceText}>{minutes===60?'1 hour':minutes+' min'}</Text></Pressable>)}</View></View>}
 {expanded&&<>{e.completedAt&&<Text style={u.small}>Completed {new Date(e.completedAt).toLocaleString()}</Text>}{e.skippedAt&&<Text style={u.small}>Skipped {new Date(e.skippedAt).toLocaleString()}</Text>}{children}</>}
 </View></SwipeEvent>;
}
const s=StyleSheet.create({inventoryAttention:{alignSelf:'flex-start',marginTop:6,paddingHorizontal:10,paddingVertical:6,borderRadius:10,backgroundColor:'#fff0f1',borderWidth:1,borderColor:'#d55b69'},inventoryAttentionText:{fontSize:11,fontWeight:'900',color:'#a52f3d'},quickReference:{flexDirection:'row',alignItems:'center',gap:8,marginTop:8,padding:8,borderRadius:12,backgroundColor:'#f2fbff'},vialIcon:{width:66,height:66,alignItems:'center',justifyContent:'center',borderRadius:10,borderWidth:2,borderColor:'#58bfe5',backgroundColor:'#fff'},vialCap:{fontSize:8,fontWeight:'800',letterSpacing:1,color:'#087da8'},vialValue:{fontSize:13,fontWeight:'800',color:'#10204a'},vialWater:{fontSize:9,fontWeight:'700',color:'#61728f'},referenceMain:{flex:1,minWidth:0,flexDirection:'row',alignItems:'center',justifyContent:'space-between',gap:6},drawInfo:{flex:1,minWidth:0,justifyContent:'center'},doseBlock:{width:156,height:62,alignItems:'flex-end',justifyContent:'center',paddingHorizontal:10,paddingVertical:6,borderRadius:11,borderWidth:2,borderColor:'#078db9',backgroundColor:'#32c7ee',overflow:'hidden',shadowColor:'#087da8',shadowOffset:{width:0,height:3},shadowOpacity:0.24,shadowRadius:5,elevation:4},doseShine:{position:'absolute',top:0,left:0,right:0,height:15,backgroundColor:'rgba(255,255,255,0.34)'},doseLabel:{fontSize:9,fontWeight:'900',letterSpacing:1.1,color:'#075f80'},doseValue:{fontSize:25,lineHeight:30,fontWeight:'900',color:'#10204a'},drawLabel:{fontSize:8,fontWeight:'800',letterSpacing:1,color:'#61728f'},drawValue:{fontSize:15,fontWeight:'800',color:'#087da8',marginTop:2},drawMeta:{fontSize:8,lineHeight:11,color:'#61728f',marginTop:2},card:{padding:10,marginTop:8,borderWidth:1,borderColor:'#dce7f5',borderRadius:16,backgroundColor:'#fff'},done:{backgroundColor:'#f7faf9'},urgentCard:{borderColor:'#e59aa5',backgroundColor:'#fff8f8'},row:{flexDirection:'row',alignItems:'center',gap:6},dot:{width:7,height:7,borderRadius:4},name:{fontSize:15,fontWeight:'800',color:'#10204a',flex:1},status:{fontSize:10,fontWeight:'800'},meta:{fontSize:11,lineHeight:16,color:'#61728f',marginTop:3},amount:{fontSize:14,lineHeight:20,fontWeight:'800',color:'#10204a',marginTop:4},urgentText:{fontSize:11,lineHeight:16,fontWeight:'700',color:'#9c2f3e',marginTop:3},snoozeWrap:{marginTop:8,padding:8,borderRadius:10,backgroundColor:'#f4f0ff'},snoozeLabel:{fontSize:11,fontWeight:'800',color:'#4f3da5',marginBottom:6},snoozeRow:{flexDirection:'row',gap:6},snoozeChoice:{flex:1,minHeight:40,alignItems:'center',justifyContent:'center',borderRadius:9,backgroundColor:'#fff'},snoozeChoiceText:{fontSize:11,fontWeight:'800',color:'#4f3da5'},actions:{flexDirection:'row',gap:4,marginTop:2},action:{minHeight:44,flex:1,alignItems:'center',justifyContent:'center',borderRadius:9,backgroundColor:'#eef8fc'},actionText:{fontSize:11,fontWeight:'800',color:'#067da7'},primary:{backgroundColor:'#13ace0'} });
