import {stageDays,durationLabel} from './duration';
import React,{useRef,useState}from'react';
import{Text,View,Pressable,StyleSheet,PanResponder}from'react-native';
import type{SavedPlan,Event,Store}from'./engine';
import{actualProgress,localDate,parseDate,prettyDate,prettyTime,eventStatus,logEvent,addDays,stageAmount,daysBetween,materializeEvents}from'./engine';
import{Button,Card,u}from'./ui';
import Syringe from'./Syringe';
import SetupSummary from './SetupSummary';
import{quantityFromMg}from'./quantities';
import{getActivePlans,replacePlan}from'./multiplan-v04';
export default function Tracker({plan,archives,now,update,initialTab='Today'}:{plan:SavedPlan;archives:SavedPlan[];now:Date;update:(fn:(s:Store)=>Store)=>Promise<void>;initialTab?:string}){
 const [tab,setTab]=useState(initialTab),[selected,setSelected]=useState(localDate(now)),[month,setMonth]=useState(localDate(now).slice(0,7)+'-01'),[error,setError]=useState(''),[message,setMessage]=useState(''),[historyFilter,setHistoryFilter]=useState<'all'|'completed'|'skipped'>('all');
 const actionLock=useRef(false),tabRef=useRef(tab);tabRef.current=tab;const [logging,setLogging]=useState(false);
 const tabOrder=['Today','Tomorrow','Calendar','History'];
 const swipe=useRef(PanResponder.create({onMoveShouldSetPanResponder:(_,gesture)=>Math.abs(gesture.dx)>18&&Math.abs(gesture.dx)>Math.abs(gesture.dy)*1.3,onMoveShouldSetPanResponderCapture:(_,gesture)=>Math.abs(gesture.dx)>18&&Math.abs(gesture.dx)>Math.abs(gesture.dy)*1.3,onPanResponderTerminationRequest:()=>false,onPanResponderRelease:(_,gesture)=>{if(Math.abs(gesture.dx)<60)return;const index=tabOrder.indexOf(tabRef.current),next=Math.max(0,Math.min(tabOrder.length-1,index+(gesture.dx<0?1:-1)));if(next!==index)setTab(tabOrder[next]);}})).current;
 const p=actualProgress(plan,now),pending=plan.events.filter(e=>e.status==='pending'),due=pending.filter(e=>new Date(e.scheduledAt)<=now),future=pending.find(e=>new Date(e.scheduledAt)>now);
 const candidate=due.find(e=>e.localDate===localDate(now))||due[due.length-1]||future;
 const action=async(e:Event,value:'completed'|'skipped'|'later')=>{if(actionLock.current)return;actionLock.current=true;setLogging(true);try{await update(s=>{const current=getActivePlans(s).find(candidate=>candidate.id===plan.id);if(!current)throw Error('This plan is no longer active.');const saved=current.events.find(candidate=>candidate.id===e.id),generated=saved?null:materializeEvents(current,e.localDate,e.localDate).find(candidate=>candidate.id===e.id),event=saved??generated;if(!event||event.status!=='pending')throw Error('This event changed before it could be saved.');const hydrated=saved?current:{...current,events:[...current.events,event].sort((a,b)=>a.scheduledAt.localeCompare(b.scheduledAt))};return replacePlan(s,logEvent(hydrated,e.id,value,new Date()));});setMessage(value==='later'?'Reminder moved 15 minutes later. The scheduled event time is unchanged.':'Event saved.');setError('');}catch(err){setError(String(err));}finally{setTimeout(()=>{actionLock.current=false;setLogging(false);},700);}};
 const eventCard=(e:Event,owner=plan,actions=false)=><Card key={e.id}><Text style={u.heading}>{owner.compoundName} · Stage {e.stageIndex+1}</Text><Text style={u.body}>{prettyDate(e.localDate)} · {prettyTime(e.scheduledAt)}</Text><Text style={[u.label,{color:colors[eventStatus(e,now)],marginTop:8}]}>{eventStatus(e,now)}</Text><Text style={u.body}>{stageAmount({amountMg:String(e.amountMg),amountUnit:e.amountUnit})} · {Number(e.calculation.units.toFixed(3))} units · {Number(e.calculation.volume.toFixed(4))} mL</Text>{e.completedAt&&<Text style={u.small}>Completed {new Date(e.completedAt).toLocaleString()}</Text>}{e.skippedAt&&<Text style={u.small}>Skipped {new Date(e.skippedAt).toLocaleString()}</Text>}{e.snoozedUntil&&e.status==='pending'&&<Text style={u.small}>Reminder: {new Date(e.snoozedUntil).toLocaleString()}</Text>}{actions&&e.status==='pending'&&new Date(e.scheduledAt)<=now&&<><Button label="Completed" disabled={logging} onPress={()=>action(e,'completed')}/><View style={u.row}><View style={{flex:1}}><Button label="Skip" disabled={logging} secondary onPress={()=>action(e,'skipped')}/></View><View style={{flex:2}}><Button label="Remind me later" disabled={logging} secondary onPress={()=>action(e,'later')}/></View></View></>}</Card>;
 const monthDate=parseDate(month)!,daysInMonth=new Date(monthDate.getFullYear(),monthDate.getMonth()+1,0).getDate(),leading=(monthDate.getDay()+6)%7;
 const moveMonth=(n:number)=>{const d=parseDate(month)!;d.setMonth(d.getMonth()+n);setMonth(localDate(d));};
 const history=materializeEvents(plan,plan.startDate,localDate(now)).filter(e=>e.status!=='pending'||new Date(e.scheduledAt)<now).map(e=>({e,owner:plan})).sort((a,b)=>b.e.scheduledAt.localeCompare(a.e.scheduledAt));
 const logged=plan.events.filter(e=>e.status==='completed'||e.status==='skipped'),completed=logged.filter(e=>e.status==='completed'),skipped=logged.filter(e=>e.status==='skipped');
 const firstCompleted=[...completed].sort((a,b)=>a.localDate.localeCompare(b.localDate))[0],lastCompleted=[...completed].sort((a,b)=>b.localDate.localeCompare(a.localDate))[0];
 const spanEnd=plan.pausedAt&&lastCompleted?lastCompleted.localDate:localDate(now),recordedWeeks=firstCompleted?Math.max(1,Math.ceil((daysBetween(firstCompleted.localDate,spanEnd)+1)/7)):0;
 const plannedDays=plan.stages.reduce((sum,stage)=>sum+stageDays(stage),0),plannedWeeks=Math.max(1,Math.ceil(plannedDays/7));
 const totalMg=completed.reduce((sum,e)=>sum+e.amountMg,0),vialMg=Number(plan.vialMg),vialEquivalents=vialMg>0?totalMg/vialMg:null,thirtyDaysAgo=addDays(localDate(now),-29),recent=completed.filter(e=>e.localDate>=thirtyDaysAgo),recentMg=recent.reduce((sum,e)=>sum+e.amountMg,0);
 const filteredHistory=history.filter(({e})=>historyFilter==='all'||e.status===historyFilter);
 const [historyLimit,setHistoryLimit]=useState(30);
 return <View {...swipe.panHandlers} style={{touchAction:'pan-y'} as any} accessibilityLabel="Today tracker. Swipe left or right to change views.">
  <View style={u.row}>{tabOrder.map(name=><Pressable key={name} accessibilityRole="tab" accessibilityLabel={name} accessibilityState={{selected:tab===name}} onPress={()=>setTab(name)} style={[u.pill,tab===name&&u.selected]}><Text style={u.heading}>{name}</Text></Pressable>)}</View>
  {!!error&&<Text style={u.error}>{error}</Text>}{!!message&&<Text accessibilityLiveRegion="polite" style={u.small}>{message}</Text>}
  {tab==='Today'&&<>
   <Card><Text style={u.title}>{plan.compoundName}</Text><Text style={u.heading}>{!p.started?'Starts '+prettyDate(plan.startDate):p.inBreak?'Planned break':p.ended?'End of modelled plan':`Day ${p.day} of ${p.totalDays}`}</Text>
    {p.stageIndex>=0&&<Text style={u.body}>Stage {p.stageIndex+1} · Day {p.stageDay} · {durationLabel(plan.stages[p.stageIndex])}</Text>}
    <Text style={u.body}>{p.daysRemaining} days remaining in the stages</Text><Text style={u.body}>{p.completed} of {p.due} scheduled events completed</Text><Text style={u.small}>{p.total} events in the full plan. Calendar progress is independent of completions.</Text>
    {p.nextTransition&&<Text style={u.body}>Next: {p.stageIndex<plan.stages.length-1?'Stage '+(p.stageIndex+2):Number(plan.breakWeeks)>0?'Planned break':'End of plan stages'} · {prettyDate(p.nextTransition)}</Text>}
    <Text style={u.small}>Planned break: {Number(plan.breakWeeks)>0?prettyDate(p.breakStart)+' to '+prettyDate(addDays(p.breakEnd,-1)):'None selected'}</Text>
    <SetupSummary plan={plan}/>{plan.origin&&<Text style={u.small}>{plan.customized?'Customized from: ':'Modelled from: '}{plan.origin.sourceTitle}</Text>}
    {p.ended&&plan.origin&&<Text style={u.small}>This is the end of encoded stages, not a treatment-stop instruction. Refer to the original source context in My Plan.</Text>}
   </Card>
   <Card><Text style={u.heading}>Next scheduled event</Text><Text style={u.body}>{future?prettyDate(future.localDate)+' · '+prettyTime(future.scheduledAt):'No future events in this model.'}</Text>{due.length>0&&<Text style={u.small}>{due.length} past event(s) awaiting a log. Review them in Calendar or History.</Text>}</Card>
   {candidate?<>{eventCard(candidate,plan,true)}<Syringe capacityOverride={plan.syringeCapacityUnits??null} onCapacityChange={size=>update(s=>s.active?.id===plan.id?{...s,active:{...s.active,syringeCapacityUnits:size,setupOrigin:s.active.setupOrigin?{...s.active.setupOrigin,customized:s.active.setupOrigin.customized||size!==s.active.setupOrigin.original.defaultSyringeCapacityUnits}:undefined}}:s).catch(e=>setError(String(e)))} result={candidate.calculation} amount={quantityFromMg(candidate.amountMg,candidate.amountUnit)} glow={plan.compoundId==='glow-70'}/></>:<Text style={u.body}>All generated events have been logged.</Text>}
  </>}
  {tab==='Tomorrow'&&<><Text style={u.heading}>Tomorrow · {prettyDate(addDays(localDate(now),1))}</Text>{plan.events.filter(e=>e.localDate===addDays(localDate(now),1)).map(e=>eventCard(e,plan,false))}{!plan.events.some(e=>e.localDate===addDays(localDate(now),1))&&<Text style={u.body}>Nothing scheduled tomorrow.</Text>}</>}
  {tab==='Calendar'&&<>
   <View style={[u.row,{justifyContent:'space-between',marginTop:18}]}><Pressable accessibilityRole="button" accessibilityLabel="Previous month" onPress={()=>moveMonth(-1)}><Text style={u.link}>‹</Text></Pressable><Text style={u.heading}>{monthDate.toLocaleDateString(undefined,{month:'long',year:'numeric'})}</Text><Pressable accessibilityRole="button" accessibilityLabel="Next month" onPress={()=>moveMonth(1)}><Text style={u.link}>›</Text></Pressable></View>
   <View style={s.grid}>{['M','T','W','T','F','S','S'].map((day,i)=><Text key={i} style={s.weekday}>{day}</Text>)}{Array.from({length:leading},(_,i)=><View key={'blank'+i} style={s.cell}/>)}{Array.from({length:daysInMonth},(_,i)=>{
    const day=month.slice(0,8)+String(i+1).padStart(2,'0'),events=materializeEvents(plan,day,day),statuses=[...new Set(events.map(e=>eventStatus(e,now)))];
    let offset=0;const stageStart=plan.stages.some(stage=>{const hit=addDays(plan.startDate,offset)===day;offset+=stageDays(stage);return hit;});const isBreak=day===p.breakStart&&Number(plan.breakWeeks)>0,isBreakEnd=day===p.breakEnd&&Number(plan.breakWeeks)>0;
    return <Pressable key={day} accessibilityRole="button" accessibilityLabel={'Calendar '+day} onPress={()=>setSelected(day)} style={[s.cell,day===selected&&s.daySelected]}><Text style={s.dayText}>{i+1}</Text><View style={{flexDirection:'row',gap:2}}>{statuses.map(status=><View key={status} style={[s.dot,{backgroundColor:colors[status]}]}/>)}</View>{(stageStart||isBreak||isBreakEnd)&&<Text style={s.marker}>{isBreak?'B':isBreakEnd?'E':'S'}</Text>}</Pressable>;
   })}</View>
   <View style={u.row}>{Object.entries(colors).map(([status,color])=><Text key={status} style={[u.small,{color}]}>● {status}</Text>)}</View><Text style={u.small}>S = stage begins · B = break begins · E = break ends</Text>
   <Text style={[u.heading,{marginTop:18}]}>{prettyDate(selected)}</Text>
   {(()=>{let offset=0;return plan.stages.map((stage,i)=>{const date=addDays(plan.startDate,offset);offset+=stageDays(stage);return date===selected?<Text key={stage.id} style={u.body}>Stage {i+1} begins</Text>:null;});})()}
   {Number(plan.breakWeeks)>0&&selected===p.breakStart&&<Text style={u.body}>Planned break begins</Text>}{Number(plan.breakWeeks)>0&&selected===p.breakEnd&&<Text style={u.body}>Planned break ends</Text>}
   {materializeEvents(plan,selected,selected).map(e=>eventCard(e,plan,true))}
   {!materializeEvents(plan,selected,selected).length&&<Text style={u.body}>No events on this day.</Text>}
  </>}
  {tab==='History'&&<><Card><Text style={u.title}>{plan.compoundName} history</Text><Text style={u.small}>A factual summary of saved activity for this peptide.</Text><View style={s.summaryGrid}><View style={s.summaryFact}><Text style={s.summaryLabel}>START DATE</Text><Text style={s.summaryValue}>{prettyDate(firstCompleted?.localDate||plan.startDate)}</Text></View><View style={s.summaryFact}><Text style={s.summaryLabel}>TIME TRACKED</Text><Text style={s.summaryValue}>{recordedWeeks?recordedWeeks+' '+(recordedWeeks===1?'week':'weeks'):'No doses yet'}</Text></View><View style={s.summaryFact}><Text style={s.summaryLabel}>TAKEN / SKIPPED</Text><Text style={s.summaryValue}>{completed.length} / {skipped.length}</Text></View><View style={s.summaryFact}><Text style={s.summaryLabel}>TOTAL TAKEN</Text><Text style={s.summaryValue}>{Number(totalMg.toFixed(3))} mg</Text></View><View style={s.summaryFact}><Text style={s.summaryLabel}>LAST 30 DAYS</Text><Text style={s.summaryValue}>{recent.length} taken · {Number(recentMg.toFixed(3))} mg</Text></View><View style={s.summaryFact}><Text style={s.summaryLabel}>VIAL EQUIVALENTS</Text><Text style={s.summaryValue}>{vialEquivalents===null?'Unavailable':Number(vialEquivalents.toFixed(2))+' at '+plan.vialMg+' mg'}</Text></View></View><Text style={u.small}>{firstCompleted&&lastCompleted?'Recorded doses: '+prettyDate(firstCompleted.localDate)+' to '+prettyDate(lastCompleted.localDate):'No completed dose has been recorded.'}</Text>{recordedWeeks>plannedWeeks&&<View style={s.durationFlag}><Text style={s.durationFlagTitle}>Tracking span exceeds the current model</Text><Text style={s.durationFlagText}>{recordedWeeks} weeks since the first recorded dose · current modeled stages cover {plannedWeeks} weeks. This is a tracking comparison, not a medical stop instruction.</Text></View>}</Card><Text style={[u.small,{marginTop:12}]}>Saved timestamps and original event calculations. Future events are in Calendar.</Text><View style={s.historyFilters}>{([{key:'all',label:'All',count:history.length},{key:'completed',label:'Taken',count:completed.length},{key:'skipped',label:'Skipped',count:skipped.length}] as const).map(item=><Pressable key={item.key} accessibilityRole="tab" accessibilityState={{selected:historyFilter===item.key}} onPress={()=>{setHistoryFilter(item.key);setHistoryLimit(30);}} style={[s.historyFilter,historyFilter===item.key&&s.historyFilterSelected]}><Text style={[s.historyFilterText,historyFilter===item.key&&s.historyFilterTextSelected]}>{item.label} · {item.count}</Text></Pressable>)}</View>{filteredHistory.slice(0,historyLimit).map(({e,owner})=>eventCard(e,owner,true))}{!filteredHistory.length&&<Text style={u.body}>No {historyFilter==='all'?'past activity':historyFilter} entries yet.</Text>}{filteredHistory.length>historyLimit&&<Button label="Show more history" secondary onPress={()=>setHistoryLimit(n=>n+30)}/>}</>}
 </View>;
}
const colors={Completed:'#178066',Scheduled:'#076eac',Missed:'#bd4352',Future:'#7a65b2',Skipped:'#737b87'};
const s=StyleSheet.create({summaryGrid:{flexDirection:'row',flexWrap:'wrap',gap:8,marginTop:14,marginBottom:10},summaryFact:{width:'48%',padding:10,borderRadius:12,backgroundColor:'#f2f9fd'},summaryLabel:{fontSize:9,fontWeight:'800',letterSpacing:1,color:'#667597'},summaryValue:{fontSize:14,lineHeight:19,fontWeight:'800',color:'#10204a',marginTop:4},durationFlag:{marginTop:12,padding:12,borderRadius:12,backgroundColor:'#fff6df',borderWidth:1,borderColor:'#e4bd5c'},durationFlagTitle:{fontSize:13,fontWeight:'800',color:'#77530b'},durationFlagText:{fontSize:11,lineHeight:17,color:'#77530b',marginTop:3},historyFilters:{flexDirection:'row',gap:6,marginTop:10,marginBottom:4},historyFilter:{flex:1,minHeight:42,alignItems:'center',justifyContent:'center',borderRadius:11,backgroundColor:'#f2f6fc'},historyFilterSelected:{backgroundColor:'#dff6ff',borderWidth:1,borderColor:'#19b3e3'},historyFilterText:{fontSize:10,fontWeight:'800',color:'#667597'},historyFilterTextSelected:{color:'#10204a'},grid:{flexDirection:'row',flexWrap:'wrap',marginTop:12},weekday:{width:'14.2857%',textAlign:'center',fontWeight:'700',color:'#667896',padding:6},cell:{width:'14.2857%',height:59,alignItems:'center',justifyContent:'center',borderRadius:10},daySelected:{backgroundColor:'#dff6ff',borderWidth:1,borderColor:'#19b3e3'},dayText:{fontSize:16,color:'#18305c',marginBottom:4},dot:{width:5,height:5,borderRadius:3},marker:{fontSize:8,color:'#0b7192'}});

