import {RESEARCH_PRACTICE_NOTICE} from './research-practice';
import React,{useState} from 'react';
import {Text,View,Pressable,TextInput,StyleSheet,Modal,Image} from 'react-native';
const professorImages=[
 require('../assets/professor-lynch-avatar.webp'),
 require('../assets/professor-lynch-pointing-right.webp'),
 require('../assets/professor-lynch-checklist.webp'),
 require('../assets/professor-lynch-thinking.webp'),
];
export const C={ink:'#10204a',muted:'#61728f',blue:'#13ace0',purple:'#7557f6',border:'#dce7f5',pale:'#eefaff'};
export function Button({label,onPress,secondary=false,disabled=false,accessibilityLabel}:{accessibilityLabel?:string;label:string;onPress:()=>void;secondary?:boolean;disabled?:boolean}){return <Pressable accessibilityRole="button" accessibilityLabel={accessibilityLabel??label} disabled={disabled} onPress={onPress} style={[u.button,secondary&&u.secondary,disabled&&{opacity:.4}]}><Text style={[u.buttonText,secondary&&{color:C.ink}]}>{label}</Text></Pressable>;}
export function Field({label,value,onChange,placeholder='Choose…',numeric=false,editable=true,error}:{label:string;value:string;onChange:(v:string)=>void;placeholder?:string;numeric?:boolean;editable?:boolean;error?:string}){return <View style={u.field}><Text style={[u.label,error&&u.fieldLabelError]}>{label}</Text><TextInput accessibilityLabel={label} accessibilityHint={error} value={value} onChangeText={onChange} placeholder={placeholder} keyboardType={numeric?'decimal-pad':'default'} style={[u.input,error&&u.inputError]} editable={editable}/>{error&&<Text accessibilityRole="alert" style={u.fieldError}>{error}</Text>}</View>;}
export function Card({children,error=false}:{children:React.ReactNode;error?:boolean}){return <View style={[u.card,error&&u.cardError]}>{children}</View>;}
export function Evidence({kind,text}:{kind:string;text?:string}){
 const approved=/approved/i.test(kind),human=/human clinical/i.test(kind),common=/common research/i.test(kind),blend=/blend/i.test(kind),user=/user|customized/i.test(kind);
 const color=approved?'#087d85':human?'#2459b4':common?'#94600a':blend?'#7d479d':user?'#536176':'#6346ae';
 const title=/US FDA/i.test(kind)?'US FDA · PRODUCT-SPECIFIC EVIDENCE':approved?'APPROVED CANADIAN LABELING':human?'PUBLISHED HUMAN CLINICAL RESEARCH':common?'COMMON RESEARCH PRACTICE':blend?'BLEND — COMPONENT EVIDENCE ONLY':user?'USER-CREATED PLAN':'PUBLISHED RESEARCH / PRECLINICAL / MECHANISTIC';
 return <View style={[u.evidence,{borderLeftColor:color}]}><Text style={[u.label,{color}]}>{title}</Text>{text&&<Text style={u.body}>{text}</Text>}{common&&<Text style={u.small}>{RESEARCH_PRACTICE_NOTICE}</Text>}</View>;
}

export function ProfessorHelp({title,body,note,label}:{title:string;body:string;note?:string;label?:string}){
 const[open,setOpen]=useState(false),accessibleLabel=label??('Learn more about '+title),imageIndex=[...title].reduce((sum,char)=>sum+char.charCodeAt(0),0)%professorImages.length;
 return <><Pressable accessibilityRole="button" accessibilityLabel={accessibleLabel} accessibilityHint="Opens an explanation from Professor Lynch" onPress={()=>setOpen(true)} hitSlop={10} style={({pressed})=>[h.trigger,pressed&&{opacity:.7}]}><Text style={h.question}>?</Text></Pressable><Modal visible={open} transparent animationType="fade" onRequestClose={()=>setOpen(false)}><View style={h.backdrop}><Pressable accessibilityRole="button" accessibilityLabel="Close Professor Lynch explanation" onPress={()=>setOpen(false)} style={StyleSheet.absoluteFill}/><View accessibilityViewIsModal style={h.sheet}><Pressable accessibilityRole="button" accessibilityLabel="Close" onPress={()=>setOpen(false)} hitSlop={10} style={h.close}><Text style={h.closeText}>×</Text></Pressable><View style={h.headingRow}><Image accessibilityLabel="Professor Lynch" source={professorImages[imageIndex]} resizeMode="contain" style={h.avatar}/><View style={h.headingCopy}><Text style={h.kicker}>PROFESSOR LYNCH EXPLAINS</Text><Text style={h.title}>{title}</Text></View></View><View style={h.bubble}><View style={h.tail}/><Text style={h.body}>{body}</Text>{note&&<Text style={h.note}>{note}</Text>}</View><Pressable accessibilityRole="button" accessibilityLabel="Got it" onPress={()=>setOpen(false)} style={h.button}><Text style={h.buttonText}>Got it</Text></Pressable></View></View></Modal></>;
}
const h=StyleSheet.create({trigger:{width:27,height:27,borderRadius:14,alignItems:'center',justifyContent:'center',backgroundColor:'#eefaff',borderWidth:1,borderColor:'#45bde7',marginLeft:7},question:{fontSize:16,lineHeight:19,fontWeight:'900',color:'#087fa9'},backdrop:{flex:1,justifyContent:'flex-end',backgroundColor:'rgba(8,20,55,.45)',padding:12},sheet:{width:'100%',maxWidth:560,alignSelf:'center',backgroundColor:'#fff',borderRadius:26,padding:18,paddingTop:16,borderWidth:1,borderColor:'#cfe1f2',boxShadow:'0px 8px 24px rgba(8,20,55,.22)'},close:{position:'absolute',right:12,top:9,width:38,height:38,alignItems:'center',justifyContent:'center',zIndex:3},closeText:{fontSize:29,lineHeight:31,color:'#536581'},headingRow:{flexDirection:'row',alignItems:'center',paddingRight:35},avatar:{width:92,height:108},headingCopy:{flex:1,paddingLeft:10},kicker:{fontSize:10,fontWeight:'900',letterSpacing:1.25,color:'#16a9dc',marginBottom:5},title:{fontSize:22,lineHeight:27,fontWeight:'900',color:'#10204a'},bubble:{marginTop:5,marginLeft:15,padding:15,borderRadius:18,backgroundColor:'#f7fbff',borderWidth:1,borderColor:'#bedcf0'},tail:{position:'absolute',left:20,top:-7,width:14,height:14,backgroundColor:'#f7fbff',borderTopWidth:1,borderLeftWidth:1,borderColor:'#bedcf0',transform:[{rotate:'45deg'}]},body:{fontSize:15,lineHeight:22,color:'#26375e',fontWeight:'600'},note:{fontSize:12,lineHeight:18,color:'#687792',marginTop:10},button:{minHeight:48,borderRadius:15,backgroundColor:'#18addd',alignItems:'center',justifyContent:'center',marginTop:16},buttonText:{fontSize:15,fontWeight:'900',color:'#fff'}});

export const u=StyleSheet.create({scroll:{padding:20,paddingBottom:40},title:{fontSize:29,fontWeight:'800',color:C.ink,marginBottom:8},heading:{fontSize:18,fontWeight:'800',color:C.ink,marginBottom:8},body:{fontSize:14,lineHeight:22,color:C.muted},small:{fontSize:12,lineHeight:18,color:C.muted,marginTop:6},label:{fontSize:12,fontWeight:'800',color:C.muted,marginBottom:5},card:{backgroundColor:'#fff',borderWidth:1,borderColor:C.border,borderRadius:22,padding:16,marginTop:14},field:{marginTop:12},input:{borderWidth:1,borderColor:C.border,borderRadius:12,padding:12,minHeight:46,fontSize:16,color:C.ink,backgroundColor:'#fff'},button:{minHeight:50,borderRadius:16,backgroundColor:C.blue,alignItems:'center',justifyContent:'center',padding:12,marginTop:14},secondary:{backgroundColor:C.pale,borderWidth:1,borderColor:C.border},buttonText:{fontSize:15,fontWeight:'800',color:'#fff',textAlign:'center'},row:{flexDirection:'row',gap:10,alignItems:'center',flexWrap:'wrap'},link:{color:'#067da7',fontSize:14,fontWeight:'700',paddingVertical:12},evidence:{borderLeftWidth:4,borderRadius:14,padding:12,backgroundColor:'#f5f8fc',marginTop:12},error:{color:'#a82a40',fontSize:13,lineHeight:20,marginTop:10},pill:{paddingHorizontal:12,paddingVertical:10,borderRadius:12,backgroundColor:'#f2f6fc',margin:3},selected:{backgroundColor:'#d8f2ff',borderWidth:1,borderColor:C.blue},cardError:{borderColor:'#bd4352',borderWidth:2,backgroundColor:'#fffafb'},inputError:{borderColor:'#bd4352',borderWidth:2,backgroundColor:'#fff8f9'},fieldLabelError:{color:'#a82a40'},fieldError:{color:'#a82a40',fontSize:12,lineHeight:18,fontWeight:'700',marginTop:5}});
