import React,{useState}from'react';import{Text,View,Pressable}from'react-native';
import SetupSummary from './SetupSummary';
import type{Draft}from'./engine';import{Card,Field,ProfessorHelp,u}from'./ui';
export default function VialSetup({draft:d,change,showErrors=false}:{draft:Draft;change:(patch:Partial<Draft>,structural:boolean)=>void;showErrors?:boolean}){
 const [customVial,setCustomVial]=useState(false),[customWater,setCustomWater]=useState(false);
 const validPositive=(value:string)=>value.trim()!==''&&Number.isFinite(Number(value))&&Number(value)>0;
 const vialError=showErrors&&!validPositive(d.vialMg)?'Enter a positive vial strength in mg.':undefined,waterError=showErrors&&!validPositive(d.waterMl)?'Enter a positive diluent volume in mL.':undefined;
 const vial=(value:string)=>change({vialMg:value},!d.setupOrigin&&d.origin?.originalReference.vialStrengthMg!=null);
 const water=(value:string)=>change({waterMl:value},!d.setupOrigin&&(d.origin?.originalReference.diluentMl??d.origin?.originalReference.reconstitutionVolumeMl)!=null);
 return <Card><SetupSummary plan={d}/><View style={[u.row,{marginTop:16}]}><Text style={[u.heading,{marginBottom:0}]}>Confirm your vial</Text><ProfessorHelp title="Vial and diluent setup" body="Vial strength is the total peptide amount printed on the vial. Diluent volume is the amount of BAC water used in this model. Together they determine concentration and the calculated draw volume." note="Copy the values from the specific vial and setup you are modelling. The calculator does not verify product preparation or clinical suitability."/></View><Text style={u.body}>Use the strength on your vial and the BAC-water volume for your setup.</Text><Text style={u.small}>Quick choices are setup conveniences, not clinical reference values.</Text>
 <View style={[u.row,{marginTop:16}]}><Text style={[u.label,{marginBottom:0}]}>VIAL STRENGTH</Text><ProfessorHelp title="Vial strength" body="This is the total amount contained in the vial, measured here in milligrams. It is not the amount for a single event."/></View>
 {<View style={u.row}>{[10,20,30,50].map(v=><Pressable key={v} accessibilityRole="button" accessibilityLabel={'Vial '+v+' mg'} onPress={()=>{vial(String(v));setCustomVial(false)}} style={[u.pill,d.vialMg===String(v)&&u.selected]}><Text style={u.body}>{v} mg</Text></Pressable>)}<Pressable accessibilityRole="button" accessibilityLabel="Custom vial strength" onPress={()=>setCustomVial(true)} style={u.pill}><Text style={u.body}>Custom</Text></Pressable></View>}
 <Field label="Vial strength (mg)" value={d.vialMg} numeric editable placeholder={customVial?'Enter strength in mg':'Select above or enter mg'} onChange={vial} error={vialError}/>
 <View style={[u.row,{marginTop:16}]}><Text style={[u.label,{marginBottom:0}]}>BAC WATER</Text><ProfessorHelp title="Diluent volume" body="This is the volume of BAC water used for the calculation. Changing it changes concentration and syringe volume, while the stage amount remains separate."/></View><View style={u.row}>{[1,2,3,5].map(v=><Pressable key={v} accessibilityRole="button" accessibilityLabel={'BAC water '+v+' mL'} onPress={()=>{water(String(v));setCustomWater(false)}} style={[u.pill,d.waterMl===String(v)&&u.selected]}><Text style={u.body}>{v} mL</Text></Pressable>)}<Pressable accessibilityRole="button" accessibilityLabel="Custom BAC water" onPress={()=>setCustomWater(true)} style={u.pill}><Text style={u.body}>Custom</Text></Pressable></View>
 <Field label="Diluent volume (mL)" value={d.waterMl} numeric placeholder={customWater?'Enter BAC-water mL':'Select above or enter mL'} onChange={water} error={waterError}/>
 {d.compoundId==='glow-70'&&<Text style={u.small}>Reference blend: GHK-Cu 50 mg + BPC-157 10 mg + TB-500 10 mg = 70 mg. Component calculations retain the 5:1:1 ratio at your entered vial strength.</Text>}
 </Card>;
}
