import React,{useEffect,useState} from 'react';
import {Pressable,Text,View,StyleSheet} from 'react-native';
import {callMembership} from './client';
export default function MembershipPanel({userId,onClose}:{userId:string;onClose:()=>void}){
 const [status,setStatus]=useState<any>(null),[busy,setBusy]=useState(false),[message,setMessage]=useState('');
 async function load(){setBusy(true);try{setStatus(await callMembership(userId,'status'));setMessage('');}catch(e){setMessage((e as Error).message);}finally{setBusy(false);}}
 useEffect(()=>{void load();},[userId]);
 async function open(operation:'checkout'|'portal'){
  if(busy)return;setBusy(true);setMessage('');
  try{const result=await callMembership(userId,operation),url=new URL(result.url);if(url.protocol!=='https:'||url.hostname!==(operation==='checkout'?'checkout.stripe.com':'billing.stripe.com'))throw Error('Payment destination could not be verified.');window.location.assign(url.href);}catch(e){setMessage((e as Error).message);setBusy(false);}
 }
 const button=(label:string,action:()=>void,disabled=false,primary=false)=><Pressable accessibilityRole="button" accessibilityLabel={label} accessibilityState={{disabled:busy||disabled}} disabled={busy||disabled} onPress={action} style={[s.button,primary&&s.primaryButton,(busy||disabled)&&{opacity:.5}]}><Text style={[s.buttonText,primary&&s.primaryButtonText]}>{label}</Text></Pressable>;
 return <View style={s.card}><Text style={s.kicker}>MEMBERSHIP</Text><Text accessibilityRole="header" style={s.title}>Your plan & membership</Text><Text style={s.body}>See your current access and manage your membership.</Text>
 <View style={s.accessSection}><Text accessibilityRole="header" style={s.sectionTitle}>Current access</Text>{status&&<><Text accessibilityLiveRegion="polite" style={s.status}>{status.pro?'Pro access verified (TEST)':(status.test_account?'No active Pro subscription (TEST)':'Free membership · beta access retained')}</Text>{status.test_account&&<><Text style={s.body}>Owner-only Stripe TEST · CAD $8.99/month · use test card details only.</Text>{button('Open TEST checkout',()=>void open('checkout'),!status.test_checkout_enabled||status.pro)}{button('Manage TEST billing',()=>void open('portal'))}</>}</>}
 </View><View style={s.proSection}><Text style={s.kicker}>COMING AFTER THE PRIVATE BETA</Text><Text style={s.sectionTitle}>EZPep Pro</Text><Text style={s.price}>CAD $8.99 <Text style={s.priceUnit}>/ month</Text></Text><Text style={s.body}>Public subscriptions are not open yet. The full Free / Pro comparison and tax details will be available before launch.</Text></View><Text style={s.caption}>Your beta access and saved planner data remain available when a subscription ends.</Text>
 {busy&&<Text accessibilityLiveRegion="polite" style={s.body}>Loading membership…</Text>}
 {!!message&&<Text accessibilityRole="alert" style={s.error}>{message}</Text>}{button('Refresh membership status',()=>void load())}{button('Return to planner',onClose,false,true)}</View>;
}
const s=StyleSheet.create({status:{padding:14,borderRadius:12,backgroundColor:'#F2EDFF',color:'#0E1C4A',fontSize:17,fontWeight:'700',lineHeight:24},body:{color:'#334466',fontSize:15,lineHeight:23},error:{color:'#A33A2B',padding:12,backgroundColor:'#FFF0ED',borderRadius:10},kicker:{fontSize:11,fontWeight:'800',letterSpacing:1.5,color:'#6850B5'},sectionTitle:{fontSize:18,fontWeight:'800',color:'#0E1C4A'},accessSection:{gap:12,padding:16,borderRadius:18,backgroundColor:'#F9FBFE',borderWidth:1,borderColor:'#DDE8F6'},proSection:{gap:10,padding:18,borderRadius:18,backgroundColor:'#EAF9FF'},price:{fontSize:30,lineHeight:38,fontWeight:'800',color:'#0E1C4A'},priceUnit:{fontSize:15,fontWeight:'500'},caption:{color:'#53617B',fontSize:13,lineHeight:20},card:{padding:24,gap:16,backgroundColor:'#fff',width:'100%',maxWidth:680,alignSelf:'center',borderRadius:26,borderWidth:1,borderColor:'#DDE8F6'},title:{fontSize:28,lineHeight:34,fontWeight:'800',color:'#0E1C4A'},button:{minHeight:48,padding:14,backgroundColor:'#eaf9ff',borderRadius:12,borderWidth:1,borderColor:'#DDE8F6'},buttonText:{color:'#0E1C4A',fontWeight:'700',fontSize:15,textAlign:'center'},primaryButton:{backgroundColor:'#0E1C4A',borderColor:'#0E1C4A'},primaryButtonText:{color:'#fff'}});
